### ISSUE TITLE
Force Update does not work (Kia/UK/EU)

### ISSUE THREAD

**Issue by DJBenson** [Hyundai-Kia-Connect/kia_uvo#441]
The "force update" results in the following error;

This error originated from a custom integration.

Logger: homeassistant.helpers.script.websocket_api_script
Source: custom_components/kia_uvo/coordinator.py:120
Integration: Hyundai / Kia Connect (documentation, issues)
First occurred: 21:26:23 (2 occurrences)
Last logged: 21:26:37

websocket_api script: Error executing script. Unexpected error for call_service at pos 1: 'vehicleStatusInfo'
websocket_api script: Error executing script. Unexpected error for call_service at pos 1: string indices must be integers
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 451, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 684, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1744, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1781, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/config/custom_components/kia_uvo/services.py", line 45, in async_handle_force_update
    await coordinator.async_force_update_all()
  File "/config/custom_components/kia_uvo/coordinator.py", line 120, in async_force_update_all
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 84, in force_refresh_all_vehicles_states
    self.force_refresh_vehicle_state(self.get_vehicle(vehicle_id))
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 87, in force_refresh_vehicle_state
    self.api.force_refresh_vehicle_state(self.token, vehicle)
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 185, in force_refresh_vehicle_state
    state = self._get_forced_vehicle_state(token, vehicle)
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 420, in _get_forced_vehicle_state
    return response["resMsg"]["vehicleStatusInfo"]
KeyError: 'vehicleStatusInfo'

**Comment by DJBenson** [comment]
It seems simultaneous errors are thrown - here's the second error;

Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/kia_uvo/coordinator.py:120
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 21:25:14 (3 occurrences)
Last logged: 21:26:37

[139850226406672] 'vehicleStatusInfo'
[139850226406672] Error handling message: Unknown error (unknown_error) from 192.168.1.44 (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/107.0.0.0 Safari/537.36)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 200, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1744, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1781, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/config/custom_components/kia_uvo/services.py", line 45, in async_handle_force_update
    await coordinator.async_force_update_all()
  File "/config/custom_components/kia_uvo/coordinator.py", line 120, in async_force_update_all
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 84, in force_refresh_all_vehicles_states
    self.force_refresh_vehicle_state(self.get_vehicle(vehicle_id))
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 87, in force_refresh_vehicle_state
    self.api.force_refresh_vehicle_state(self.token, vehicle)
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 185, in force_refresh_vehicle_state
    state = self._get_forced_vehicle_state(token, vehicle)
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 420, in _get_forced_vehicle_state
    return response["resMsg"]["vehicleStatusInfo"]
KeyError: 'vehicleStatusInfo'
