### ISSUE TITLE
Error on server unavailable

### ISSUE THREAD

**Issue by hmmbob** [Hyundai-Kia-Connect/kia_uvo#522]
**Region and Brand of car**
EU, Hyundai

**Version of the integration**
2.1.0

**Describe the bug**
Error gets raised when server is unavailable (this should be a warning). Furthermore, the `{err}` placeholder does not get replaced with the actual error (see first line of log below)

**Debug logs if an error occurred**
```py
2022-12-20 17:55:36.116 ERROR (MainThread) [custom_components.kia_uvo.coordinator] Force update failed, falling back to cached: {err}
Traceback (most recent call last):
File "/config/custom_components/kia_uvo/coordinator.py", line 118, in _async_update_data
await self.hass.async_add_executor_job(
File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 81, in check_and_force_update_vehicles
self.update_vehicle_with_cached_state(vehicle)
File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 64, in update_vehicle_with_cached_state
self.api.update_vehicle_with_cached_state(self.token, vehicle)
File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 232, in update_vehicle_with_cached_state
state = self._get_cached_vehicle_state(token, vehicle)
File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 523, in _get_cached_vehicle_state
_check_response_for_errors(response)
File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 71, in _check_response_for_errors
raise error_code_mapping[response["resCode"]](response["resMsg"])
hyundai_kia_connect_api.exceptions.APIError: Unavailable remote control - Service Temporary Unavailable
```

**Comment by cdnninja** [comment]
I think I fixed the placeholder issue. 

As for not raising an exception are you able to help me understand why?  Did it recover correctly?  In the above I would expect it to fall back to cached if that fails throw another exception which HA caches and now knows to try again shortly.

**Comment by hmmbob** [comment]
Because it is falling back to cached data, it isn't really an error but a warning: "hey, something went wrong but no worries, I've got your back: I still remember the previous data".

**Comment by cdnninja** [comment]
I think in the above case it failed cached as well.  So we need to tell home assistant about that.  It is done via an exception.  This allows HA to know the data is no longer valid.

**Comment by cdnninja** [comment]
Another comment as I close this.  HA itself picks the warning vs level.   They catch the exception if it fails more than once levels it up to an error.  Which is why my home assistant alert section is full of issues that happened at some point since last time clearing.   I don't fully agree since it doesn't clear but nothing I can do.
