### ISSUE TITLE
`unconverted data remains:` after update to 2.3.1

### ISSUE THREAD

**Issue by hmmbob** [Hyundai-Kia-Connect/kia_uvo#537]
**Region and Brand of car**
Hyundai Tucson

**Version of the integration**
2.3.1

**Describe the bug**
Error in the logs, component doesn't initialise

**Debug logs if an error occurred**

```py
2022-12-25 17:11:57.044 ERROR (MainThread) [custom_components.kia_uvo.coordinator] Unexpected error fetching kia_uvo data: unconverted data remains: 0
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 225, in _async_refresh
self.data = await self._async_update_data()
File "/config/custom_components/kia_uvo/coordinator.py", line 102, in _async_update_data
await self.async_check_and_refresh_token()
File "/config/custom_components/kia_uvo/coordinator.py", line 159, in async_check_and_refresh_token
await self.hass.async_add_executor_job(
File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 93, in check_and_refresh_token
self.initialize()
File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 55, in initialize
self.update_all_vehicles_with_cached_state()
File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 62, in update_all_vehicles_with_cached_state
self.update_vehicle_with_cached_state(self.get_vehicle(vehicle_id))
File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 65, in update_vehicle_with_cached_state
self.api.update_vehicle_with_cached_state(self.token, vehicle)
File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 266, in update_vehicle_with_cached_state
self._update_vehicle_properties(vehicle, state)
File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 534, in _update_vehicle_properties
vehicle.ev_first_departure_time = self._get_time_from_string(get_child_value(state, "vehicleStatus.evStatus.reservChargeInfos.reservChargeInfo.reservChargeInfoDetail.reservInfo.time.time"))
File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 261, in _get_time_from_string
value = dt.datetime.strptime(value, '%H%M').time()
File "/usr/local/lib/python3.10/_strptime.py", line 568, in _strptime_datetime
tt, fraction, gmtoff_fraction = _strptime(data_string, format)
File "/usr/local/lib/python3.10/_strptime.py", line 352, in _strptime
raise ValueError("unconverted data remains: %s" %
ValueError: unconverted data remains: 0
```

**Comment by cdnninja** [comment]
Could you either 1. Roll back to the previous version and post your data sensor attributes?  Or 2. Enable debug logs and post the logs of the cached vehicle status.

**Comment by hmmbob** [comment]
I did rollback, that works fine.

```yaml
vehicle_data:
  vehicleLocation:
    coord:
      lat: 51.658253
      lon: 5.633992
      alt: 0
      type: 0
    head: 343
    speed:
      value: 0
      unit: 0
    accuracy:
      hdop: 0
      pdop: 0
    time: '20221225162508'
  vehicleStatus:
    airCtrlOn: false
    engine: false
    doorLock: true
    doorOpen:
      frontLeft: 0
      frontRight: 0
      backLeft: 0
      backRight: 0
    trunkOpen: false
    airTemp:
      value: 00H
      unit: 0
      hvacTempType: 1
    defrost: false
    lowFuelLight: false
    acc: false
    evStatus:
      batteryCharge: false
      batteryStatus: 99
      batteryPlugin: 0
      remainTime2:
        etc2:
          value: 3
          unit: 1
        etc3:
          value: 1
          unit: 1
        atc:
          value: 3
          unit: 1
      drvDistance:
        - rangeByFuel:
            gasModeRange:
              value: 372
              unit: 1
            evModeRange:
              value: 0
              unit: 1
            totalAvailableRange:
              value: 372
              unit: 1
          type: 2
      reservChargeInfos:
        reservChargeInfo:
          reservChargeInfoDetail:
            reservInfo:
              day:
                - 9
              time:
                time: '1270'
                timeSection: 0
            reservChargeSet: false
        offpeakPowerInfo:
          offPeakPowerTime1:
            starttime:
              time: '1200'
              timeSection: 0
            endtime:
              time: '1200'
              timeSection: 0
          offPeakPowerFlag: 0
        reserveChargeInfo2:
          reservChargeInfoDetail:
            reservInfo:
              day:
                - 9
              time:
                time: '1270'
                timeSection: 0
            reservChargeSet: false
        reservFlag: 0
        ect:
          start:
            day: 0
            time:
              time: '0000'
              timeSection: 0
          end:
            day: 0
            time:
              time: '0000'
              timeSection: 0
    ign3: false
    hoodOpen: false
    transCond: true
    steerWheelHeat: 0
    sideBackWindowHeat: 0
    tirePressureLamp:
      tirePressureLampAll: 0
      tirePressureLampFL: 0
      tirePressureLampFR: 0
      tirePressureLampRL: 0
      tirePressureLampRR: 0
    seatHeaterVentState:
      frSeatHeatState: 2
      flSeatHeatState: 2
      rlSeatHeatState: 2
      rrSeatHeatState: 2
    battery:
      batSoc: 83
      batState: 0
      sjbDeliveryMode: 1
      batSignalReferenceValue:
        batWarning: 65
      powerAutoCutMode: 2
    lampWireStatus:
      stopLamp:
        stopLampStatus: false
        leftLamp: false
        rightLamp: false
      headLamp:
        headLampStatus: false
        leftLowLamp: false
        rightLowLamp: false
        leftHighLamp: false
        rightHighLamp: false
        leftBifuncLamp: false
        rightBifuncLamp: false
      turnSignalLamp:
        turnSignalLampStatus: false
        leftFrontLamp: false
        rightFrontLamp: false
        leftRearLamp: false
        rightRearLamp: false
    windowOpen:
      frontLeft: 0
      frontRight: 0
      backLeft: 0
      backRight: 0
    smartKeyBatteryWarning: false
    fuelLevel: 52
    washerFluidStatus: false
    breakOilStatus: false
    sleepModeCheck: true
    time: '20221225162509'
    remoteWaitingTimeAlert:
      remoteControlAvailable: 1
      remoteControlWaitingTime: 168
      elapsedTime: '00:03:42'
    systemCutOffAlert: 0
    tailLampStatus: 0
    hazardStatus: 0
  odometer:
    value: 4706.7
    unit: 1
vehicle_name: TUCSON
friendly_name: TUCSON Data
```

**Comment by cdnninja** [comment]
Can you check what your charging schedules show in app for time? 

Your data shows a 1270 start time which is failing to parse since it isn't a time.

**Comment by hmmbob** [comment]
Never used that....

![Screenshot_20221225_190100_Bluelink](https://user-images.githubusercontent.com/33529490/209477942-5666a360-3d48-4616-a903-7935f983421b.jpg)

**Comment by cdnninja** [comment]
I assume that first menu button is the schedules.  Could I grab that as a screenshot? 

I may just need to adjust to ignore when disabled.

**Comment by hmmbob** [comment]
![Screenshot_20221225_190211_Bluelink](https://user-images.githubusercontent.com/33529490/209477996-a7c5e620-fb16-4f3a-a078-8320c0047046.jpg)

**Comment by cdnninja** [comment]
So looks like 1270 to them is 1:10. Odd approach but I'll work with it.  Thank you.   I'll work on a fix later today or tomorrow.

**Comment by hmmbob** [comment]
> So looks like 1270 to them is 1:10. Odd approach but I'll work with it. Thank you. I'll work on a fix later today or tomorrow.

Thanks! Agree, that way of describing time is rather.... Unique 😂

**Comment by cdnninja** [comment]
I have made some rather large changes for this. Could you go into HACS and redownload and select version "master" and let me know if it works?

**Comment by hmmbob** [comment]
Works!

**Comment by cdnninja** [comment]
Great thanks for the quick reply!

**Comment by hmmbob** [comment]
Of course! Thanks for the quick fixing!
