### ISSUE TITLE
Invalid vehicle for current session, AuthError

### ISSUE THREAD

**Issue by nprez83** [Hyundai-Kia-Connect/kia_uvo#540]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/kia_uvo/blob/master/README.md
**Region and Brand of car**
Kia Telluride 2020, USA

**Version of the integration**
2.3.1

**Describe the bug**
I'm still getting the above error from the hyundai_kia_api, when trying to run any of the services. Unlike before, the entities appear to be ok and are no longer becoming unavailable. Reloading the integration fixes things for one service call (any service, update, start or stop climate) but the error comes back after one service call, and needs the integration to be reloaded again.

The log below is after having tried a stop command that failed, then an update command that also failed, and then a start climate command, which also failed.

**Debug logs if an error occurred**
```
Logger: hyundai_kia_connect_api.KiaUvoAPIUSA
Source: /usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoAPIUSA.py:76
First occurred: 07:58:48 (8 occurrences)
Last logged: 08:28:35

hyundai_kia_connect_api - error: unknown error response {"status":{"statusCode":1,"errorType":1,"errorCode":1005,"errorMessage":"Invalid vehicle for current session"}}
hyundai_kia_connect_api - error: unknown error response {"status":{"statusCode":1,"errorType":1,"errorCode":9001,"errorMessage":"Incorrect request payload format"})
```
```
This error originated from a custom integration.

Logger: homeassistant.helpers.script.websocket_api_script
Source: custom_components/kia_uvo/coordinator.py:198
Integration: Hyundai / Kia Connect (documentation, issues)
First occurred: 08:15:07 (4 occurrences)
Last logged: 08:21:01

websocket_api script: Error executing script. Unexpected error for call_service at pos 1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoAPIUSA.py", line 35, in request_with_active_session_wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoAPIUSA.py", line 75, in request_with_logging_wrapper
    raise AuthError
hyundai_kia_connect_api.KiaUvoAPIUSA.AuthError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 451, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 684, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1745, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1782, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/config/custom_components/kia_uvo/services.py", line 75, in async_handle_stop_climate
    await coordinator.async_stop_climate(vehicle_id)
  File "/config/custom_components/kia_uvo/coordinator.py", line 198, in async_stop_climate
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 106, in stop_climate
    return self.api.stop_climate(self.token, self.get_vehicle(vehicle_id))
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoAPIUSA.py", line 500, in stop_climate
    response = self.get_request_with_logging_and_active_session(
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoAPIUSA.py", line 50, in request_with_active_session_wrapper
    response = func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoAPIUSA.py", line 77, in request_with_logging_wrapper
    raise RequestException
requests.exceptions.RequestException
```
```
This error originated from a custom integration.

Logger: homeassistant.helpers.script.websocket_api_script
Source: custom_components/kia_uvo/coordinator.py:191
Integration: Hyundai / Kia Connect (documentation, issues)
First occurred: 08:28:35 (1 occurrences)
Last logged: 08:28:35

websocket_api script: Error executing script. Unexpected error for call_service at pos 1:
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 451, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 684, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1745, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1782, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/config/custom_components/kia_uvo/services.py", line 70, in async_handle_start_climate
    await coordinator.async_start_climate(vehicle_id, climate_request_options)
  File "/config/custom_components/kia_uvo/coordinator.py", line 191, in async_start_climate
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 103, in start_climate
    return self.api.start_climate(self.token, self.get_vehicle(vehicle_id), options)
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoAPIUSA.py", line 493, in start_climate
    response = self.post_request_with_logging_and_active_session(
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoAPIUSA.py", line 35, in request_with_active_session_wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoAPIUSA.py", line 77, in request_with_logging_wrapper
    raise RequestException
requests.exceptions.RequestException
```
```
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/kia_uvo/coordinator.py:191
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 08:28:35 (1 occurrences)
Last logged: 08:28:35

[547166414560] Error handling message: Unknown error (unknown_error) from 73.54.153.140 (Mozilla/5.0 (Linux; Android 13; Pixel 7 Build/TQ1A.221205.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/108.0.5359.128 Mobile Safari/537.36 Home Assistant/2022.12.0-3026 (Android 13; Pixel 7))
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 646, in handle_execute_script
    await script_obj.async_run(msg.get("variables"), context=context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1524, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 409, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 453, in _async_step
    self._handle_exception(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 476, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 451, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 684, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1745, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1782, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/config/custom_components/kia_uvo/services.py", line 70, in async_handle_start_climate
    await coordinator.async_start_climate(vehicle_id, climate_request_options)
  File "/config/custom_components/kia_uvo/coordinator.py", line 191, in async_start_climate
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 103, in start_climate
    return self.api.start_climate(self.token, self.get_vehicle(vehicle_id), options)
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoAPIUSA.py", line 493, in start_climate
    response = self.post_request_with_logging_and_active_session(
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoAPIUSA.py", line 35, in request_with_active_session_wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoAPIUSA.py", line 77, in request_with_logging_wrapper
    raise RequestException
requests.exceptions.RequestException
```

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by johnanders** [comment]
I had the same issue for about 30 minutes (all of my sensors were unavailable as well) and a force refresh didn't work either. Waited 10 minutes and tried again, and then it suddenly loaded. Maybe Kia's API was just having issues?

**Comment by nprez83** [comment]
Hmm, I'm not sure that's it for me, the Kia app was working normally. It's also been happening for the past 2 days, I just didn't have a chance to look into it given the holidays.

**Comment by cdnninja** [comment]
@nprez83  are you able to enable debug logs? I think I have an idea of what is happening. In particular in the debug logs looking for a line that states: 

`got invalid session, attempting to repair and resend`

**Comment by cdnninja** [comment]
I have made some rather large changes to KIA USA. Could you go into HACS and redownload and select version "master" and let me know if 1 it works and 2 if this issue is resolved?  I wouldn't doubt it if I have some mistakes in it.

**Comment by nprez83** [comment]
Seems to be working great so far. Nice job! Have run several start, stop, and force_update commands without issues. The only thing different I'm noticing between now and the 1.8 version is that the sensors don't seem to update to the latest cached data after the command completes, but I can easily fix that by running the update command after running the other commands.

**Comment by cdnninja** [comment]
Interesting to see.  Today for KIA USA we call force update and then automatically call the cached update.  I wonder if the cached call is too fast.  In other regions we actually parse the forced update data, this is new in 2.x where as all regions in 1.X did force call followed by cached and only looked at cached. 

Could you do me a favor and with debug enabled call a forced update and look for the line that says `got response` followed by some details. I want to see if the format and data of this matches a cached call. If so we can parse it upfront and solve this efficiently.

**Comment by nprez83** [comment]
Might have spoken too soon. All the entities just went unavailable, with the error below.
```
This error originated from a custom integration.

Logger: custom_components.kia_uvo.coordinator
Source: custom_components/kia_uvo/coordinator.py:159
Integration: Hyundai / Kia Connect (documentation, issues)
First occurred: 13:18:47 (2 occurrences)
Last logged: 14:18:51

Unexpected error fetching kia_uvo data: 'dict' object has no attribute 'id'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 225, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/kia_uvo/coordinator.py", line 102, in _async_update_data
    await self.async_check_and_refresh_token()
  File "/config/custom_components/kia_uvo/coordinator.py", line 159, in async_check_and_refresh_token
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 98, in check_and_refresh_token
    self.vehicles = self.api.refresh_vehicles(self.token, self.vehicles)
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoAPIUSA.py", line 228, in refresh_vehicles
    if vehicle.id == entry["vehicleIdentifier"]:
AttributeError: 'dict' object has no attribute 'id'
```

**Comment by cdnninja** [comment]
To confirm do you have one car in the app or multiple?

**Comment by cdnninja** [comment]
Please download the latest from "master" and try again.   As a note the token in kia usa is invalidated when the app is used which is one of the reasons this can happen.  So we attempt to catch that and relogin.   Unfortunately some of the vehicle data also changes when that happens so working on handling that. 

More logging has been added too so if you get the above again please go into the full logs to grab what happened right before it.

**Comment by nprez83** [comment]
> To confirm do you have one car in the app or multiple? 

Only one. I may have to wait till tomorrow to try again, but I'll report back.

**Comment by nprez83** [comment]
Alright, I was able to install it and it all seems ok for now. Ran update, start, and stop commands without issues. I also logged into the native at after the start command to kick the tires and it seemed to handle it well. Will see what happens overnight and will report back.

**Comment by nprez83** [comment]
Thought I'd report back that all seems well with this version (2.3.2), no more disconnect/unavailable issues and all services working well. I just upgraded to 2.3.3, excited to no longer have to specify device for service calls. Thanks as always for the hard work.

**Comment by cdnninja** [comment]
Great news! Thanks for the support.
