### ISSUE TITLE
Missing entities from previous version

### ISSUE THREAD

**Issue by MdXMaxX** [Hyundai-Kia-Connect/kia_uvo#543]
Hello,

I have a US Kia EV6.  I've been on version 1.8.1 for a while and decided to upgrade to the latest version 2.3.2 today.

I noticed some of the entities I was using before have disappeared.  In particular:
- binary_sensor: charging
  - It seems the latest version of binary_sensor.py has "ev_battery_is_charging", which looks equivalent, but that entity does not appear for my EV6
- sensor: target_capacity_of_charge_ac and target_capacity_of_charge_dc
  - I don't see equivalents in the code, it looks like "ev_target_range_charge_AC" and "ev_target_rance_charge_DC" exist, but those are in terms of distance, not state of charge, and those don't appear for my EV6 either

I deleted and removed the integration, redownloaded and reconfigured it, but have the same issue.  Is there a way to get these entities back?

Thanks

**Comment by cdnninja** [comment]
Yes! This is just a mapping exercise specific to your region.  

Could you post your attributes of the data sensor?  Other option is check out the api repo under this account. It has a file for usa Kia that does the mapping.  Most likely these items are missing.

**Comment by cdnninja** [comment]
So for target it is now moved to a slider with number for setting purposes: https://github.com/Hyundai-Kia-Connect/kia_uvo/blob/master/custom_components/kia_uvo/number.py

When something in number, sensor or binary sensor doesn't show up it means the data doesn't exist. Either because it isn't mapped for that region/brand or the car doesn't support it.  In this case most likely just hasn't been mapped since none of the devs are in the USA.  Here is where I will do that mapping: https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/blob/6baad7b8a041c3a333aa13f0fa6d1fe2a30de5a9/hyundai_kia_connect_api/KiaUvoAPIUSA.py#L248-L387

Post post the attributes and we can get this fixed up.

**Comment by MdXMaxX** [comment]
Got it, thank you for the info!  Here are the contents of the Vehicle Data attribute (with a few [redactions] for privacy):
```
vinKey: [vinKey]
vehicleConfig:
  vehicleDetail:
    vehicle:
      vin: [vin]
      trim:
        modelYear: '2022'
        salesModelCode: N4362
        optionGroupCode: '014'
        modelName: EV6
        factoryCode: AS
        projectCode: CV
        trimName: GT-LINE
        driveType: '1'
        transmissionType: '1'
        ivrCategory: '10'
        btSeriesCode: 'Y'
      telematics: 1
      mileage: '9490.7'
      mileageSyncDate: '20230101093639'
      exteriorColor: YACHT BLUE
      exteriorColorCode: DU3
      fuelType: 4
      invDealerCode: [invDealerCode]
      testVehicle: '0'
      supportedApps:
        - appType: '0'
        - appType: '5'
          appImage:
            imageName: uvo-app.png
            imagePath: /content/dam/kia/us/owners/image/common/app/access/
            imageType: '2'
            imageSize:
              length: '100'
              width: '100'
              uom: 0
      activationType: 2
    images:
      - imageName: 2022-ev6-gt-line-du3.png
        imagePath: /content/dam/kia/us/owners/image/vehicle-app/2022/ev6/gt-line/
        imageType: '1'
        imageSize:
          length: '100'
          width: '100'
          uom: 0
    device:
      launchType: '0'
      swVersion: CVEV.USA.S5W_M.V008.001.220504
      telematics:
        generation: '3'
        platform: '1'
        tmsCenter: '1'
        billing: true
      versionNum: ECO
      headUnitType: '0'
      hdRadio: X40HAF
      ampType: NA
      modem:
        meid: [meid]
        mdn: [mdn]
      headUnitName: avn5em
      bluetoothRef: '20'
      headUnitDesc: AVN5.0W
  maintenance:
    nextServiceMile: 6509.3
    maintenanceSchedule:
      - 8000
      - 16000
      - 24000
      - 32000
      - 40000
      - 48000
      - 56000
      - 64000
      - 72000
      - 80000
      - 88000
      - 96000
  billingPeriod:
    freeTrial:
      value: 12
      unit: 0
    freeTrialExtension:
      value: 12
      unit: 1
    servicePeriod:
      value: 60
      unit: 1
lastVehicleInfo:
  vehicleNickName: EV6
  preferredDealer: [preferredDealer]
  customerType: 0
  enrollment:
    provStatus: '4'
    enrollmentStatus: '1'
    enrollmentType: '0'
    registrationDate: '20220312'
    expirationDate: '20230312'
    expirationMileage: '100000'
    freeServiceDate:
      startDate: '20220312'
      endDate: '20230312'
    evEnrollmentCode: [evEnrollmentCode]
  activeDTC:
    dtcActiveCount: '0'
  vehicleStatusRpt:
    statusType: '2'
    reportDate:
      utc: '20230102013332'
      offset: -8
    vehicleStatus:
      climate:
        airCtrl: false
        defrost: false
        airTemp:
          value: '72'
          unit: 1
        heatingAccessory:
          steeringWheel: 0
          sideMirror: 0
          rearWindow: 0
      engine: false
      doorLock: true
      doorStatus:
        frontLeft: 0
        frontRight: 0
        backLeft: 0
        backRight: 0
        trunk: 0
        hood: 0
      lowFuelLight: false
      evStatus:
        batteryCharge: false
        batteryStatus: 73
        batteryPlugin: 0
        batteryPrecondition: false
        remainChargeTime:
          - remainChargeType: 1
            timeInterval:
              value: 0
              unit: 4
          - remainChargeType: 2
            timeInterval:
              value: 0
              unit: 4
          - remainChargeType: 3
            timeInterval:
              value: 0
              unit: 4
        drvDistance:
          - type: 2
            rangeByFuel:
              evModeRange:
                value: 212
                unit: 3
              totalAvailableRange:
                value: 212
                unit: 3
        syncDate:
          utc: '20230102003639'
          offset: -8
        targetSOC:
          - plugType: 0
            targetSOClevel: 0
            dte:
              type: 2
              rangeByFuel:
                gasModeRange:
                  value: 0
                  unit: 3
                evModeRange:
                  value: 212
                  unit: 3
                totalAvailableRange:
                  value: 212
                  unit: 3
          - plugType: 1
            targetSOClevel: 0
            dte:
              type: 2
              rangeByFuel:
                gasModeRange:
                  value: 0
                  unit: 3
                evModeRange:
                  value: 212
                  unit: 3
                totalAvailableRange:
                  value: 212
                  unit: 3
      ign3: false
      transCond: true
      tirePressure:
        all: 0
      dateTime:
        utc: '20230102013332'
        offset: -8
      syncDate:
        utc: '20230102003639'
        offset: -8
      batteryStatus:
        stateOfCharge: 84
        deliveryMode: 1
        warning: 65
        powerAutoCutMode: 2
      sleepMode: false
      lampWireStatus:
        headLamp:
          headLampStatus: false
          lampLL: false
          lampRL: false
          lampLH: false
          lampRH: false
          lampLB: false
          lampRB: false
        stopLamp:
          leftLamp: false
          rightLamp: false
        turnSignalLamp:
          lampLF: false
          lampRF: false
          lampLR: false
          lampRR: false
      windowStatus:
        windowFL: 0
        windowFR: 0
        windowRL: 0
        windowRR: 0
      smartKeyBatteryWarning: false
      washerFluidStatus: false
      brakeOilStatus: false
      engineRuntime: {}
      remoteControlAvailable: 1
      valetParkingMode: 0
      rsaStatus: 0
      lightStatus:
        tailLampStatus: 0
        hazardStatus: 0
  location:
    coord:
      lat: [lat]
      lon: [lon]
      alt: 166
      type: 0
      altdo: 0
    head: 190
    speed:
      value: 0
      unit: 1
    accuracy:
      hdop: 8
      pdop: 14
    syncDate:
      utc: '20230102003639'
      offset: -8
  financed: true
  financeRegistered: false
  linkStatus: 0
  rsaStatus: 0
```

**Comment by cdnninja** [comment]
Could you "redownload" in HACS and select Master in the version list and let me know if it works for SOC and charging sensors?

**Comment by fitchlay** [comment]
Master worked for SOC and charging sessions on my US Hyundai Ioniq 5.

Hope it worked the OP.

**Comment by MdXMaxX** [comment]
I do see the SOC and charging sensors now with master, thanks!

I do however get "Failed to call service number.set_value" when I try to change the limit value with the slider.  Here's what I see in the home assistant log:
```
2023-01-02 11:00:03.518 ERROR (SyncWorker_6) [hyundai_kia_connect_api.KiaUvoAPIUSA] hyundai_kia_connect_api - error: unknown error response {"status":{"statusCode":1,"errorType":1,"errorCode":9001,"errorMessage":"Incorrect request payload format"}}
2023-01-02 11:00:03.519 ERROR (MainThread) [homeassistant.core] Error executing service: <ServiceCall number.set_value (c:01GNSPS39KADMDHH8Y9EXG6VMX): value=100.0, entity_id=['number.ev6_ac_charging_limit']>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1763, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1782, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 678, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 943, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 715, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/number/__init__.py", line 358, in async_set_value
    await entity.async_set_native_value(native_value)
  File "/config/custom_components/kia_uvo/number.py", line 109, in async_set_native_value
    await self.coordinator.set_charge_limits(self.vehicle.id, ac, dc)
  File "/config/custom_components/kia_uvo/coordinator.py", line 219, in set_charge_limits
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 121, in set_charge_limits
    return self.api.set_charge_limits(self.token, self.get_vehicle(vehicle_id), ac, dc)
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoAPIUSA.py", line 559, in set_charge_limits
    response = self.post_request_with_logging_and_active_session(
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoAPIUSA.py", line 36, in request_with_active_session_wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoAPIUSA.py", line 79, in request_with_logging_wrapper
    raise RequestException
requests.exceptions.RequestException
2023-01-02 11:01:21.856 ERROR (SyncWorker_4) [hyundai_kia_connect_api.KiaUvoAPIUSA] hyundai_kia_connect_api - error: unknown error response {"status":{"statusCode":1,"errorType":1,"errorCode":9001,"errorMessage":"Incorrect request payload format"}}
2023-01-02 11:01:21.857 ERROR (MainThread) [homeassistant.core] Error executing service: <ServiceCall number.set_value (c:01GNSPW1JA4FFY8N0ZEWBB0E6P): value=100.0, entity_id=['number.ev6_dc_charging_limit']>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1763, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1782, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 678, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 943, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 715, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/number/__init__.py", line 358, in async_set_value
    await entity.async_set_native_value(native_value)
  File "/config/custom_components/kia_uvo/number.py", line 109, in async_set_native_value
    await self.coordinator.set_charge_limits(self.vehicle.id, ac, dc)
  File "/config/custom_components/kia_uvo/coordinator.py", line 219, in set_charge_limits
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 121, in set_charge_limits
    return self.api.set_charge_limits(self.token, self.get_vehicle(vehicle_id), ac, dc)
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoAPIUSA.py", line 559, in set_charge_limits
    response = self.post_request_with_logging_and_active_session(
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoAPIUSA.py", line 36, in request_with_active_session_wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoAPIUSA.py", line 79, in request_with_logging_wrapper
    raise RequestException
requests.exceptions.RequestException
```

**Comment by cdnninja** [comment]
I have made another update in the master branch. Please redownload and let me know if any different.  If not I may need to add some logging to figure this one out.  The API doesn't like our command for some reason.

**Comment by MdXMaxX** [comment]
Looks like that change fixed it, great.

Thank you for the help!  I think that's all for this issue.
