### ISSUE TITLE
Service force update fails

### ISSUE THREAD

**Issue by 4homeassistant** [Hyundai-Kia-Connect/kia_uvo#549]
Force update stopped working in the past days on our EU-Account with Hyundai Kona EV and our EU-Account with Hyundai Ioniq 5 and linked Kona EV.

Everything is running the latest versions.

Here's the log entry:
```
Logger: homeassistant.helpers.script.websocket_api_script
Source: custom_components/kia_uvo/coordinator.py:152 
Integration: Hyundai / Kia Connect (documentation, issues) 
First occurred: 01:30:06 (2 occurrences) 
Last logged: 01:30:29

websocket_api script: Error executing script. Unexpected error for call_service at pos 1: unhashable type: 'Vehicle'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 451, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 684, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1755, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1792, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/config/custom_components/kia_uvo/services.py", line 49, in async_handle_force_update
    await coordinator.async_force_update_all()
  File "/config/custom_components/kia_uvo/coordinator.py", line 152, in async_force_update_all
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 102, in force_refresh_all_vehicles_states
    self.force_refresh_vehicle_state(self.get_vehicle(vehicle_id))
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 105, in force_refresh_vehicle_state
    vehicle = self.get_vehicle(vehicle_id)
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 65, in get_vehicle
    return self.vehicles[vehicle_id]
TypeError: unhashable type: 'Vehicle'
```

**Comment by zadigre** [comment]
same here... 
I believe it stopped working with 2.4.0 installed earlier today.

**Comment by cdnninja** [comment]
Sorry about that!  2.4.1 resolves.

**Comment by 4homeassistant** [comment]
Thank you @cdnninja, it's working again. 😊

**Comment by zadigre** [comment]
Working for me too.
Thank you
