### ISSUE TITLE
Hyundai i30N does not work / No Data Found v2 - No Data Found v2

### ISSUE THREAD

**Issue by roederm94** [Hyundai-Kia-Connect/kia_uvo#560]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/kia_uvo/blob/master/README.md
**Region and Brand of car**
Germany (EU) / Hyundai i30N Facelift

**Version of the integration**
2.4.1

**Describe the bug**
After configuring the configuration, the initialisation does not work.

**Debug logs if an error occurred**
Logger: custom_components.kia_uvo.coordinator
Source: custom_components/kia_uvo/coordinator.py:135
Integration: Hyundai / Kia Connect ([documentation](https://github.com/fuatakgun/kia_uvo), [issues](https://github.com/fuatakgun/kia_uvo/issues))
First occurred: 22:05:02 (4 occurrences)
Last logged: 22:05:43

Unexpected error fetching kia_uvo data: No Data Found v2 - No Data Found v2
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 225, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/kia_uvo/coordinator.py", line 135, in _async_update_data
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 69, in update_all_vehicles_with_cached_state
    self.update_vehicle_with_cached_state(vehicle_id)
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 74, in update_vehicle_with_cached_state
    self.api.update_vehicle_with_cached_state(self.token, vehicle)
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 278, in update_vehicle_with_cached_state
    state = self._get_cached_vehicle_state(token, vehicle)
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 682, in _get_cached_vehicle_state
    _check_response_for_errors(response)
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 91, in _check_response_for_errors
    raise error_code_mapping[response["resCode"]](response["resMsg"])
hyundai_kia_connect_api.exceptions.NoDataFound: No Data Found v2 - No Data Found v2

Outlined here: https://github.com/fuatakgun/kia_uvo/blob/master/README.md

**To Reproduce**
I can reproduce this issue every time. The implementation does not work for my car.

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by cdnninja** [comment]
This is a duplicate to this item: https://github.com/Hyundai-Kia-Connect/kia_uvo/issues/514

Do you have a second car in the mobile app that doesn't show data when you click on it?

**Comment by roederm94** [comment]
Hello, no, i dont have a second car registered.

**Comment by cdnninja** [comment]
Does your single car load data in the app?

**Comment by roederm94** [comment]
Yes, the app is working without any issues.

**Comment by roederm94** [comment]
Nevermind, you are right. The app is not working as well. Im going to fix this.

**Comment by roederm94** [comment]
I think you can close this issue.
