### ISSUE TITLE
Cannot add integration

### ISSUE THREAD

**Issue by noltondyer** [Hyundai-Kia-Connect/kia_uvo#562]
When trying to add the integration in the main “Devices” tab, I get an “Unexpected error occurred” message and I’m presented with these logs: 

`This error originated from a custom integration.`

`Logger: aiohttp.server
Source: custom_components/kia_uvo/config_flow.py:166 
Integration: Hyundai / Kia Connect (documentation, issues) 
First occurred: 6:50:18 PM (3 occurrences) 
Last logged: 6:52:42 PM`

`Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 435, in _handle_request
    resp = await request_handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_app.py", line 504, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 60, in security_filter_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 81, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 236, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 136, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 180, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 73, in wrapper
    result = await method(view, request, data, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 286, in async_configure
    result = await self._async_handle_step(
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 374, in _async_handle_step
    result: FlowResult = await getattr(flow, method)(user_input)
  File "/config/custom_components/kia_uvo/config_flow.py", line 166, in async_step_user
    if self._reauth_entry is False:
AttributeError: 'ConfigFlow' object has no attribute '_reauth_entry'`

_Originally posted by @noltondyer in https://github.com/Hyundai-Kia-Connect/kia_uvo/issues/561#issuecomment-1374985597_

**Comment by cdnninja** [comment]
Give 2.5.2 a go.

**Comment by noltondyer** [comment]
Let me give my system a restart and give it a go!

**Comment by noltondyer** [comment]
It looks to be resolved! No error logs given. You, my friend, are a genius.
