### ISSUE TITLE
Odd behavior with set charge limit on PHEV

### ISSUE THREAD

**Issue by dblacknc** [Hyundai-Kia-Connect/kia_uvo#580]
US region
2021 Kia Niro PHEV
Integration 2.5.5

This car only has AC charging.  It does send an accurate SOC for the HV battery, no problem there.   I'd like to set the charging limit to something other than the default of 100%.   Seems like when I don't check the DC box too, it doesn't show anything in the log.  When I do also check DC and set it to some number - here DC 50, AC 90, this is what happens:

2023-01-25 17:44:21.202 DEBUG (SyncWorker_0) [hyundai_kia_connect_api.KiaUvoAPIUSA] hyundai_kia_connect_api - sending https://api.owners.kia.com/apigw/v1/evc/sts request with {'targetSOClist': [{'plugType': 0, 'targetSOClevel': 50}, {'plugType': 1, 'targetSOClevel': 90}]}
2023-01-25 17:45:05.063 DEBUG (SyncWorker_0) [hyundai_kia_connect_api.KiaUvoAPIUSA] hyundai_kia_connect_api got response {"status":{"statusCode":1,"errorType":1,"errorCode":554,"errorMessage":"Invalid Status Response"}}
2023-01-25 17:45:05.063 ERROR (SyncWorker_0) [hyundai_kia_connect_api.KiaUvoAPIUSA] hyundai_kia_connect_api - Error: unknown error response {"status":{"statusCode":1,"errorType":1,"errorCode":554,"errorMessage":"Invalid Status Response"}}
2023-01-25 17:45:05.073 ERROR (MainThread) [homeassistant.core] Error executing service: <ServiceCall kia_uvo.set_charge_limits (c:01GQNHN0JDXS9TE5PWDKRYHZXP): device_id=89c7027a094fdc54854e0d43d83b1aeb, ac_limit=90, dc_limit=50>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1773, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1792, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/config/custom_components/kia_uvo/services.py", line 114, in async_handle_set_charge_limit
    await coordinator.set_charge_limits(vehicle_id, int(ac), int(dc))
  File "/config/custom_components/kia_uvo/coordinator.py", line 226, in set_charge_limits
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 149, in set_charge_limits
    return self.api.set_charge_limits(
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoAPIUSA.py", line 651, in set_charge_limits
    response = self.post_request_with_logging_and_active_session(
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoAPIUSA.py", line 36, in request_with_active_session_wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoAPIUSA.py", line 81, in request_with_logging_wrapper
    raise RequestException

...and...

023-01-25 17:50:12.004 DEBUG (SyncWorker_4) [hyundai_kia_connect_api.KiaUvoAPIUSA] hyundai_kia_connect_api - last_updated_at - before 20230125224746
2023-01-25 17:50:12.004 DEBUG (SyncWorker_4) [hyundai_kia_connect_api.KiaUvoAPIUSA] hyundai_kia_connect_api - last_updated_at - after 2023-01-25 22:47:46+00:00
2023-01-25 17:50:12.005 DEBUG (SyncWorker_4) [hyundai_kia_connect_api.KiaUvoAPIUSA] hyundai_kia_connect_api - SOC Levels couldn't be found. May not be an EV.
2023-01-25 17:50:12.411 DEBUG (MainThread) [custom_components.kia_uvo.coordinator] Finished fetching kia_uvo data in 3.727 seconds (success: True)
2023-01-25 17:50:12.476 DEBUG (SyncWorker_1) [hyundai_kia_connect_api.VehicleManager] hyundai_kia_connect_api - Time differential in seconds: 146.476049
2023-01-25 17:50:12.476 DEBUG (SyncWorker_1) [hyundai_kia_connect_api.KiaUvoAPIUSA] hyundai_kia_connect_api - sending https://api.owners.kia.com/apigw/v1/cmm/gvi request with {'vehicleConfigReq': {'airTempRange': '0', 'maintenance': '1', 'seatHeatCoolOption': '0', 'vehicle': '1', 'vehicleFeature': '0'}, 'vehicleInfoReq': {'drivingActivty': '0', 'dtc': '1', 'enrollment': '1', 'functionalCards': '0', 'location': '1', 'vehicleStatus': '1', 'weather': '0'}, 'vinKey': ['REMOVED']}

and later:

2023-01-25 17:53:25.052 DEBUG (MainThread) [custom_components.kia_uvo.coordinator] Finished fetching kia_uvo data in 1.986 seconds (success: True)
2023-01-25 17:53:25.071 ERROR (MainThread) [homeassistant.core] Error executing service: <ServiceCall number.set_value (c:01GQNJ49J33YCTYHT0BD4BCW09): value=90.0, entity_id=['number.evie_ac_charging_limit']>
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/core.py", line 1773, in catch_exceptions
    await coro_or_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1792, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 213, in handle_service
    await service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 678, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 958, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 715, in _handle_entity_call
    await result
  File "/usr/src/homeassistant/homeassistant/components/number/__init__.py", line 388, in async_set_value
    await entity.async_set_native_value(native_value)
  File "/config/custom_components/kia_uvo/number.py", line 114, in async_set_native_value
    await self.coordinator.set_charge_limits(self.vehicle.id, ac, dc)
  File "/config/custom_components/kia_uvo/coordinator.py", line 226, in set_charge_limits
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 149, in set_charge_limits
    return self.api.set_charge_limits(
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoAPIUSA.py", line 643, in set_charge_limits
    "targetSOClevel": int(dc),
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'

Let me know if there's more info you need.  These are clips from the full debug log.  It's otherwise full of of info I'd have to scrub to be comfortable posting publicly.

**Comment by cdnninja** [comment]
Our code currently expects both values.   I can update to only send a single and we can see if that works?

**Comment by dblacknc** [comment]
Yes, I'm happy to test.  I'm not sure the function even works with my car, though feel it's worth the time to try.

FYI my Kia Connect Android app also has this apparent function, both DC and AC limits - again noting DC is N/A for the PHEV.    When I similarly attempt to set a charge limit in the app, it churns for about 30 seconds then returns "Invalid Status Response."

**Comment by cdnninja** [comment]
Does any value work in the Kia app?

**Comment by dblacknc** [comment]
I haven't tried all values but know at least 80 and 90 don't.   The DC percent slider also being there (and shouldn't be) is strange for a supposed production-quality app.   My two guesses:

1. It does work with the PHEV, but only if the DC percent isn't passed.  This would also mean the Kia Connect app just has a bug - what I'm hoping.  That app does a few other strange things, so it's possible.

2. It actually works only for the EV, and the API is mistakenly presenting SOC limit info for my PHEV.   However, the car does know its HV battery SOC, and can stop and start the charge on a schedule and/or manually via the app/API.  That is, the charging system, albeit lacking a DC connection and with a smaller HV battery, seems to work basically the same as the EV.

**Comment by cdnninja** [comment]
Today we request both values.  So it sounds like if we check if no AC is passed we just send the DC it should work?

**Comment by dblacknc** [comment]
From the vehicle info you should get for targetSOC both AC and DC from a current EV, or from a PHEV, just AC.    At some point Kia/Hyundai PHEVs may also get DC fast charging.  None I'm aware of have it today.

If vehicle info only returns a targetSOClevel for plugType 1 (AC) then I believe a max charge level request should also contain only a reference to plugType 1, and not one for plugType 0.  The proper form of the request - assuming the API will accept something for it, could be:

'targetSOC":[{'plugType':1,'targetSOClevel':90}] - as seen in info, or maybe

'targetSOClist':[{'plugType':1,'targetSOClevel': 90}] - request without DC plugType 0

Happy to test either/both.

**Comment by cdnninja** [comment]
Since this doesn't work in the native app I'm not sure we fight with it?  Would be quick to test in python though if you are willing to do that.  I'm not comfortable putting it into this release though. 

I can walk you through testing it with our library if interested.

**Comment by dblacknc** [comment]
If you could tell me how to test it myself - yes, thank you.   Understood you don't want to put an experiment into the release.

**Comment by cdnninja** [comment]
Head over here and download the files either with github desktop or manually: https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api

Then create a text file that contains this.   Edit the file to put your username password and regions in based on the link above.  Region and brand need to be set to the correct number for you.  You will also need to input your vehicle ID into the last line.  You can get that from your home assistant logs.  Or running print(vm.vehicles) where the set charge limits command is. 

`from pathlib import Path
import logging
import sys
import os

path_root = r"C:\Users\jayde\OneDrive\Documents\GitHub\main\hyundai_kia_connect_api"
sys.path.append(str(path_root))
from hyundai_kia_connect_api import *
from hyundai_kia_connect_api.exceptions import *

logging.basicConfig(stream=sys.stdout, level=logging.DEBUG, format='%(asctime)s %(name)s %(levelname)s:%(message)s')
logger = logging.getLogger(__name__)

vm = VehicleManager(region=2, brand=1, username="email", password="password", pin="pin")

vm.update_all_vehicles_with_cached_state()
vm.set_charge_limits("vehicleID", 80, 80)
`

Once you have the above working report back.  I will need to edit and provide you a modified version of this: https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/blob/817de72b47bcf9c3f1fc7e1d1ccb65b8f629bfea/hyundai_kia_connect_api/KiaUvoAPIUSA.py#L639-L650

Essentially removing the lines for DC.

**Comment by dblacknc** [comment]
Do you mean VIN for vehicleID below? I'm in region 3 (USA) and put my email, password and left PIN a null string since it's unset. 

Here's what I see: 

./test.py 
Traceback (most recent call last): 
File "/rebo/tmp/hyundai_kia_connect_api/./test.py", line 19, in <module> 
vm.set_charge_limits(" my_VIN ", 80, 80) 
File "/rebo/tmp/hyundai_kia_connect_api/hyundai_kia_connect_api/VehicleManager.py", line 150, in 
set_charge_limits 
self.token, self.get_vehicle(vehicle_id), ac, dc 
File "/rebo/tmp/hyundai_kia_connect_api/hyundai_kia_connect_api/VehicleManager.py", line 67, in 
get_vehicle 
return self.vehicles[vehicle_id] 
KeyError: ' my_VIN '

**Comment by dblacknc** [comment]
Looks like I needed to add:
vm.check_and_refresh_token()

Starting to get some output now, will update within the next few hours.

**Comment by dblacknc** [comment]
Let me know if you need lines prior to this.

2023-01-30 16:56:37,205 hyundai_kia_connect_api.KiaUvoAPIUSA DEBUG:hyundai_kia_connect_api - SOC Levels couldn't be found. May not be an EV.
2023-01-30 16:56:37,205 hyundai_kia_connect_api.KiaUvoAPIUSA DEBUG:hyundai_kia_connect_api - sending https://api.owners.kia.com/apigw/v1/evc/sts request with {'targetSOClist': [{'plugType': 0, 'targetSOClevel': 80}, {'plugType': 1, 'targetSOClevel': 80}]}
2023-01-30 16:56:37,206 urllib3.connectionpool DEBUG:Starting new HTTPS connection (1): api.owners.kia.com:443
2023-01-30 16:57:21,712 urllib3.connectionpool DEBUG:https://api.owners.kia.com:443 "POST /apigw/v1/evc/sts HTTP/1.1" 200 98
2023-01-30 16:57:21,715 hyundai_kia_connect_api.KiaUvoAPIUSA DEBUG:hyundai_kia_connect_api got response {"status":{"statusCode":1,"errorType":1,"errorCode":554,"errorMessage":"Invalid Status Response"}}
2023-01-30 16:57:21,716 hyundai_kia_connect_api.KiaUvoAPIUSA ERROR:hyundai_kia_connect_api - Error: unknown error response {"status":{"statusCode":1,"errorType":1,"errorCode":554,"errorMessage":"Invalid Status Response"}}
Traceback (most recent call last):
  File "/rebo/tmp/hyundai_kia_connect_api/./test.py", line 20, in <module>
    vm.set_charge_limits("463355", 80, 80)
  File "/rebo/tmp/hyundai_kia_connect_api/hyundai_kia_connect_api/VehicleManager.py", line 148, in set_charge_limits
    return self.api.set_charge_limits(
  File "/rebo/tmp/hyundai_kia_connect_api/hyundai_kia_connect_api/KiaUvoAPIUSA.py", line 651, in set_charge_limits
    response = self.post_request_with_logging_and_active_session(
  File "/rebo/tmp/hyundai_kia_connect_api/hyundai_kia_connect_api/KiaUvoAPIUSA.py", line 36, in request_with_active_session_wrapper
    return func(*args, **kwargs)
  File "/rebo/tmp/hyundai_kia_connect_api/hyundai_kia_connect_api/KiaUvoAPIUSA.py", line 81, in request_with_logging_wrapper
    raise RequestException
requests.exceptions.RequestException

**Comment by cdnninja** [comment]
Looks like it doesn't like not having DC.  Could try sending blank DC value.

**Comment by dblacknc** [comment]
For DC:
 10-99, 100: 554 Invalid status response
 1, 0, -1, '': 9001 Incorrect request payload format

For the invalid status response - looks like it's talking the car, because there's a 30 sec or so pause.   The payload error comes back right away.

**Comment by cdnninja** [comment]
My gut is this won't work, Since the native app doesn't work either.

**Comment by dblacknc** [comment]
Thanks for the help in how to directly use the API.   I'll likely continue to experiment and pursue this on my own.   The "feature" being there in the app yet not working is strange.   Perhaps for the PHEV it's a different call than evc/sts (just speculating).

Closing for now then.  I'll reopen and share details if I discover there's a way to make it work.
