### ISSUE TITLE
set_charge_limits not working

### ISSUE THREAD

**Issue by alexmace** [Hyundai-Kia-Connect/kia_uvo#597]
I recently upgraded from 1.x to 2.6.0, and it seems like `set_charge_limits` in my automations has stopped working. I try and manually call it using the "Services" in Developer tools, I get this error:

```
Logger: homeassistant.helpers.script.websocket_api_script
Source: custom_components/kia_uvo/__init__.py:110 
Integration: Kia Uvo / Hyundai Bluelink ([documentation](https://github.com/fuatakgun/kia_uvo), [issues](https://github.com/fuatakgun/kia_uvo/issues)) 
First occurred: 15:31:38 (2 occurrences) 
Last logged: 15:32:40

websocket_api script: Error executing script. Unexpected error for call_service at pos 1: 'vehicle'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 451, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 684, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1787, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1824, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/config/custom_components/kia_uvo/__init__.py", line 110, in async_handle_set_charge_limits
    vehicle: Vehicle = hass.data[DOMAIN][DATA_VEHICLE_INSTANCE]
KeyError: 'vehicle'
```

Any help fixing this would be much appreciated - thank you for this integration, it has been reallty useful.

**Comment by cdnninja** [comment]
To confirm when you use the developer menu you are selecting the car from the drop down menu?

**Comment by patsch9** [comment]
i have problems with charge limit too, there comes either the error "request timeout" or "dulicate request". Starting and Stopping the charge works as expected.

**Comment by cdnninja** [comment]
What brand and region?  Also just to rule it out could you uninstall the integration and re-add it? 

@patsch9  you have a different issue by the sounds of it.

**Comment by patsch9** [comment]
> What brand and region? Also just to rule it out could you uninstall the integration and re-add it?
> 
> @patsch9 you have a different issue by the sounds of it.

the car is a kia ceed phev in the EU region. it was a new instalation of the integration.

**Comment by gasman1844** [comment]
I am showing the same issue as described by patsch9, showing the same error messages. I have a Hyundai Kona EV in the EU region. I can turn on debug logging if that would be helpful.

**Comment by Sab44** [comment]
Same issue here, Hyundai Kona EV in EU. 
It seems like the force update isn't working which is executed at the start of the set_charge_limits call. Trying to call force update directly also will produce the same error for me. I assume the `Duplicate Request` message pops up if you try to send another request while the previous one is still in the process of timing out.

The force update that occurs when you restart HA / the integration will also fail.

```
2023-02-20 09:53:34.330 DEBUG (SyncWorker_6) [hyundai_kia_connect_api.KiaUvoApiEU] hyundai_kia_connect_api - get_stamp 2023-02-20 05:01:49.665000+00:00 120000 115 998 115.87221327500001
2023-02-20 09:55:29.749 DEBUG (SyncWorker_6) [hyundai_kia_connect_api.KiaUvoApiEU] hyundai_kia_connect_api - Received forced vehicle data: {'retCode': 'F', 'resCode': '4081', 'resMsg': 'Request timeout. - Request timeout.', 'msgId': '7597dc14-64b9-4032-a530-2640bd74c548'}
2023-02-20 09:55:29.752 ERROR (MainThread) [homeassistant.core] Error executing service: <ServiceCall kia_uvo.force_update (c:01GSQ0EFZKECWG1EAXMCE2QBKH)>
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/core.py", line 1805, in catch_exceptions
await coro_or_task
File "/usr/src/homeassistant/homeassistant/core.py", line 1824, in _execute_service
await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
File "/config/custom_components/kia_uvo/services.py", line 49, in async_handle_force_update
await coordinator.async_force_update_all()
File "/config/custom_components/kia_uvo/coordinator.py", line 159, in async_force_update_all
await self.hass.async_add_executor_job(
File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
result = self.fn(*self.args, **self.kwargs)
File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 105, in force_refresh_all_vehicles_states
self.force_refresh_vehicle_state(vehicle_id)
File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 110, in force_refresh_vehicle_state
self.api.force_refresh_vehicle_state(self.token, vehicle)
File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 314, in force_refresh_vehicle_state
state = self._get_forced_vehicle_state(token, vehicle)
File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 729, in _get_forced_vehicle_state
_check_response_for_errors(response)
File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 108, in _check_response_for_errors
raise error_code_mapping[response["resCode"]](response["resMsg"])
hyundai_kia_connect_api.exceptions.RequestTimeoutError: Request timeout. - Request timeout.
```

**Comment by alexmace** [comment]
> To confirm when you use the developer menu you are selecting the car from the drop down menu?

I was not, there wasn't an option there, but there is now, how strange. I repeatedly checked if it was needed and saw no sign of it! I will try this out and see.

**Comment by alexmace** [comment]
Ok, I have tried that now, but instead I get the same issue as others in this thread about a duplicate request:

```
Logger: homeassistant.helpers.script.websocket_api_script
Source: custom_components/kia_uvo/coordinator.py:226 
Integration: Kia Uvo / Hyundai Bluelink ([documentation](https://github.com/fuatakgun/kia_uvo), [issues](https://github.com/fuatakgun/kia_uvo/issues)) 
First occurred: 20:53:12 (1 occurrences) 
Last logged: 20:53:12

websocket_api script: Error executing script. Unexpected error for call_service at pos 1: Duplicate request - Duplicate request
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 451, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 684, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1787, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1824, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/config/custom_components/kia_uvo/services.py", line 114, in async_handle_set_charge_limit
    await coordinator.set_charge_limits(vehicle_id, int(ac), int(dc))
  File "/config/custom_components/kia_uvo/coordinator.py", line 226, in set_charge_limits
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 150, in set_charge_limits
    return self.api.set_charge_limits(
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 1050, in set_charge_limits
    _check_response_for_errors(response)
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 108, in _check_response_for_errors
    raise error_code_mapping[response["resCode"]](response["resMsg"])
hyundai_kia_connect_api.exceptions.DuplicateRequestError: Duplicate request - Duplicate request
```
I think I will revert to 1.x instead for now.

**Comment by cdnninja** [comment]
This thread is for a vehicle missing error.  Please look at other issues to see if you have the same error as someone else and if not open a new one.

**Comment by alexmace** [comment]
Closing the issue as obviously my original problem was a cache or mistake.
