### ISSUE TITLE
SSL: WRONG_SIGNATURE_TYPE

### ISSUE THREAD

**Issue by YeloMelo95** [Hyundai-Kia-Connect/kia_uvo#600]
Having the same issue as in #362, kind of out of the blue. I am on v2.5.9 (was on v2.6.0 when issue started, re-installed v2.5.9 to try roll-back), haven't made any significant changes that I can recall however this add-on is stuck in an error state. This is the error I am getting:

Config entry 'Kia Canada #######@#####.com' for kia_uvo integration not ready yet: Config Not Ready: HTTPSConnectionPool(host='www.kiaconnect.ca', port=443): Max retries exceeded with url: /tods/api/lgn (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:997)'))); Retrying in background

No issue using the app or anything to login and start the car / lock the doors. After deleting the integration and trying to re-add it, I get an unexpected error. This is the log entry for that error:

This error originated from a custom integration.

Logger: custom_components.kia_uvo.config_flow
Source: deps/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoApiCA.py:92
Integration: Hyundai / Kia Connect (documentation, issues)
First occurred: 7:33:59 AM (2 occurrences)
Last logged: 7:35:03 AM

Unexpected exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.10/site-packages/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/local/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/local/lib/python3.10/ssl.py", line 1071, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.10/ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='www.kiaconnect.ca', port=443): Max retries exceeded with url: /tods/api/lgn (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:997)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/kia_uvo/config_flow.py", line 159, in async_step_user
    await validate_input(self.hass, user_input)
  File "/config/custom_components/kia_uvo/config_flow.py", line 63, in validate_input
    token: Token = await hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/deps/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoApiCA.py", line 92, in login
    response = requests.post(url, json=data, headers=headers)
  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/requests/adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='www.kiaconnect.ca', port=443): Max retries exceeded with url: /tods/api/lgn (Caused by SSLError(SSLError(1, '[SSL: WRONG_SIGNATURE_TYPE] wrong signature type (_ssl.c:997)')))

**Comment by cdnninja** [comment]
Yes I started getting that last night.  Looks like Kia Canada has changed ssl.  This will take an update to get working.   Hope to figure it out this week.

**Comment by YeloMelo95** [comment]
Looks like 2.6.1 fixed this, had no problems logging back into the integration and all functionality is working
