### ISSUE TITLE
Start Climate - EV6 - Error

### ISSUE THREAD

**Issue by kunalkhosla** [Hyundai-Kia-Connect/kia_uvo#608]
```
File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoAPIUSA.py", line 41, in request_with_active_session_wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoAPIUSA.py", line 86, in request_with_logging_wrapper
    raise RequestException
requests.exceptions.RequestException
```

Above exception when the service.start_climate is invoked

**Comment by cdnninja** [comment]
I will need more logs to troubleshoot that.  Atleast the full trace.

**Comment by cdnninja** [comment]
What region what brand and what version?    The questions in the template for issues is important.

**Comment by kunalkhosla** [comment]
> What region what brand and what version? The questions in the template for issues is important.

Apologies, the template didn't show up on mobile for some reason.

V 2.6.1
USA

I'll upload more logs soon

**Comment by kunalkhosla** [comment]
Here you go

```
2023-03-14 09:20:59.703 ERROR (SyncWorker_7) [hyundai_kia_connect_api.KiaUvoAPIUSA] hyundai_kia_connect_api - Error: unknown error response {"status":{"statusCode":1,"errorType":1,"errorCode":9001,"errorMessage":"Incorrect request payload format"}}
2023-03-14 09:20:59.707 ERROR (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Error executing script. Unexpected error for call_service at pos 1: 
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 451, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 684, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1808, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1845, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/config/custom_components/kia_uvo/services.py", line 70, in async_handle_start_climate
    await coordinator.async_start_climate(vehicle_id, climate_request_options)
  File "/config/custom_components/kia_uvo/coordinator.py", line 198, in async_start_climate
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 128, in start_climate
    return self.api.start_climate(self.token, self.get_vehicle(vehicle_id), options)
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoAPIUSA.py", line 648, in start_climate
    response = self.post_request_with_logging_and_active_session(
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoAPIUSA.py", line 41, in request_with_active_session_wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoAPIUSA.py", line 86, in request_with_logging_wrapper
    raise RequestException
requests.exceptions.RequestException
2023-03-14 09:20:59.714 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140675332289008] Error handling message: Unknown error (unknown_error) Kunal Khosla from 192.168.86.39 (Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 26, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 647, in handle_execute_script
    await script_obj.async_run(msg.get("variables"), context=context)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 1524, in async_run
    await asyncio.shield(run.async_run())
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 409, in async_run
    await self._async_step(log_exceptions=False)
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 453, in _async_step
    self._handle_exception(
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 476, in _handle_exception
    raise exception
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 451, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 684, in _async_call_service_step
    await service_task
  File "/usr/src/homeassistant/homeassistant/core.py", line 1808, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1845, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/config/custom_components/kia_uvo/services.py", line 70, in async_handle_start_climate
    await coordinator.async_start_climate(vehicle_id, climate_request_options)
  File "/config/custom_components/kia_uvo/coordinator.py", line 198, in async_start_climate
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 128, in start_climate
    return self.api.start_climate(self.token, self.get_vehicle(vehicle_id), options)
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoAPIUSA.py", line 648, in start_climate
    response = self.post_request_with_logging_and_active_session(
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoAPIUSA.py", line 41, in request_with_active_session_wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoAPIUSA.py", line 86, in request_with_logging_wrapper
    raise RequestException
requests.exceptions.RequestException
```

**Comment by cdnninja** [comment]
What yaml did you provide and how does that compare to what is available in the mobile app?

**Comment by kunalkhosla** [comment]
I just tried to use the "Service" section in "developer tools"

The YAML it posted looks like:

```
service: kia_uvo.start_climate
data:
  duration: 5
  climate: true
  defrost: false
  heating: "3"
  device_id: <my_device_id>
  temperature: 70
  flseat: "8"

```

**Comment by kunalkhosla** [comment]
ok looks like Kia app doesnt let me set steering and seat heating. So once I removed it, it worked. Sorry about the false alarm. Will withdraw
