### ISSUE TITLE
Error fetching kia_uvo data: 'int_user_id'

### ISSUE THREAD

**Issue by MrDadoo** [Hyundai-Kia-Connect/kia_uvo#626]
It seems to me that remote end have changed and the integration does not work.

Below is my logfile error that indicates taht int_user_id cannot be fectchec bprobably becuase a "redirectUrl" is not present in http response from kia web end.

```
Logger: custom_components.kia_uvo.coordinator
Source: custom_components/kia_uvo/coordinator.py:104
Integration: Kia Uvo / Hyundai Bluelink ([documentation](https://github.com/fuatakgun/kia_uvo), [issues](https://github.com/fuatakgun/kia_uvo/issues))
First occurred: 8 april 2023 kl. 16:22:38 (5357 occurrences)
Last logged: 21:56:09

Unexpected error fetching kia_uvo data: 'int_user_id'
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 103, in login
    authorization_code = self._get_authorization_code_with_redirect_url(
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 563, in _get_authorization_code_with_redirect_url
    parsed_url = urlparse(response["redirectUrl"])
KeyError: 'redirectUrl'
```

**Comment by cdnninja** [comment]
Which version? This was solved a few days back.

**Comment by MrDadoo** [comment]
I was on old version. Updated now successfully. This time via hacks so I get new versions more smoothly.
