### ISSUE TITLE
Kia Connect / Kia Uvo / Kia BlueLink

### ISSUE THREAD

**Issue by rikardkjell** [Hyundai-Kia-Connect/kia_uvo#664]
**Region and Brand of car**
EU

**Version of the integration**
v2.10.2

**Describe the bug**
Lost connection to my car in the integration as well as in the App "Kia UVO" However I can connect and get information from the car in Android App "Kia Connect". One could argue that Kia is making life difficult launching several Apps doing the same thing obviously slightly different (since one app can communicate with my car and the other can't)

**Debug logs if an error occurred**
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/kia_uvo/coordinator.py", line 107, in _async_update_data
    await self.async_check_and_refresh_token()
  File "/config/custom_components/kia_uvo/coordinator.py", line 166, in async_check_and_refresh_token
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 120, in check_and_refresh_token
    self.initialize()
  File "/usr/local/lib/python3.11/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 64, in initialize
    self.token: Token = self.api.login(self.username, self.password)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 198, in login
    device_id = self._get_device_id(stamp)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 1104, in _get_device_id
    _check_response_for_errors(response)
  File "/usr/local/lib/python3.11/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 110, in _check_response_for_errors
    raise APIError(f"Server returned: '{response['resMsg']}'")
hyundai_kia_connect_api.exceptions.APIError: Server returned: 'Invalid request body - Invalid parameter.'
2023-06-30 10:14:41.189 DEBUG (MainThread) [custom_components.kia_uvo.coordinator] Finished fetching kia_uvo data in 0.455 seconds (success: False)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
When connection to my account via MyKia (https://www.kia.com/se/mykia) I get this responce:
"MyKia is not available at the moment. We are rebuilding the platform but expect to be up and running again soon."

**Comment by VerbruggenBart** [comment]
I seem to have a similar issue (Belgium)
When opening UVO app: "Netwerkfout. neem contact op met uw dealer als de foutmelding blijft bestaan"
EN: "network error. contact your dealer if the error persists"
In home assistant> devices and services the Hyundai / Kia connect integration says "needs attention" and is stuck at "retrying setup"

**Comment by MikeSpike666** [comment]
Same problem here (SE) since yesterday night. I get "Invalid request body - Invalid parameter."
From home-assistant.log:

File "/usr/local/lib/python3.11/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 1104, in _get_device_id
    _check_response_for_errors(response)
  File "/usr/local/lib/python3.11/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 110, in _check_response_for_errors
    raise APIError(f"Server returned: '{response['resMsg']}'")
hyundai_kia_connect_api.exceptions.APIError: Server returned: 'Invalid request body - Invalid parameter.'
2023-06-30 10:11:15.286 ERROR (MainThread) [custom_components.kia_uvo.coordinator] Unexpected error fetching kia_uvo data: Server returned: 'Invalid request body - Invalid parameter.'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/kia_uvo/coordinator.py", line 107, in _async_update_data
    await self.async_check_and_refresh_token()
  File "/config/custom_components/kia_uvo/coordinator.py", line 166, in async_check_and_refresh_token
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)

**Comment by RuneNyhuus** [comment]
Yeah i have the same error..
Unexpected error fetching kia_uvo data: Server returned: 'Invalid request body - Invalid parameter.'

**Comment by fuatakgun** [comment]
resolving here, check open issues first.
https://github.com/Hyundai-Kia-Connect/kia_uvo/issues/660
