### ISSUE TITLE
Unknown error when setting up kia/hyundai integration

### ISSUE THREAD

**Issue by hmorkemo** [Hyundai-Kia-Connect/kia_uvo#668]
My car is a Hyundai Kona 2020.
The integration version is 2.10.3

My hyundai integration started failing some days ago (I don't know if it's related to HA version or not).
It worked fine up until then. Now there are just of error messages in the log because of missing services and entities.

I deleted and added the integration, restarting HA after each step.
After filling in user name, password, region, pin and car type, I just get "Unexpected error", and nothing happens.
The parameters are correct, identical to the ones used in the bluelink app.

My log file contains this:
`2023-07-03 16:20:24.030 WARNING (MainThread) [hyundai_kia_connect_api.KiaUvoApiEU] Unsupported language: nb, fallback to en
2023-07-03 16:20:24.881 ERROR (MainThread) [custom_components.kia_uvo.config_flow] Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/kia_uvo/config_flow.py", line 159, in async_step_user
    await validate_input(self.hass, user_input)
  File "/config/custom_components/kia_uvo/config_flow.py", line 63, in validate_input
    token: Token = await hass.async_add_executor_job(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 199, in login
    device_id = self._get_device_id(stamp)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 1106, in _get_device_id
    _check_response_for_errors(response)
  File "/usr/local/lib/python3.11/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 111, in _check_response_for_errors
    raise APIError(f"Server returned: '{response['resMsg']}'")
hyundai_kia_connect_api.exceptions.APIError: Server returned: 'Invalid request body - Invalid parameter.'`

**Comment by Wolf-Code** [comment]
Here's my own formatted trace for clarity:

```Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/kia_uvo/coordinator.py", line 107, in _async_update_data
    await self.async_check_and_refresh_token()
  File "/config/custom_components/kia_uvo/coordinator.py", line 166, in async_check_and_refresh_token
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 120, in check_and_refresh_token
    self.initialize()
  File "/usr/local/lib/python3.11/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 64, in initialize
    self.token: Token = self.api.login(self.username, self.password)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 199, in login
    device_id = self._get_device_id(stamp)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 1106, in _get_device_id
    _check_response_for_errors(response)
  File "/usr/local/lib/python3.11/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 111, in _check_response_for_errors
    raise APIError(f"Server returned: '{response['resMsg']}'")
hyundai_kia_connect_api.exceptions.APIError: Server returned: 'Invalid request body - Invalid parameter.'```

**Comment by Anobium** [comment]
Not working here.
----
UK/Ioniq5/2023
-----
![image](https://github.com/Hyundai-Kia-Connect/kia_uvo/assets/17933379/ae703edb-ebd6-4e56-b06a-79a92691aa1d)

I pulled down from Master and latest version.
-----

Logger: custom_components.kia_uvo.coordinator
Source: custom_components/kia_uvo/coordinator.py:166
Integration: Kia Uvo / Hyundai Bluelink ([documentation](https://github.com/fuatakgun/kia_uvo), [issues](https://github.com/fuatakgun/kia_uvo/issues))
First occurred: 16:44:31 (4 occurrences)
Last logged: 16:45:30

Unexpected error fetching kia_uvo data: Server returned: 'Invalid request body - Invalid parameter.'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/kia_uvo/coordinator.py", line 107, in _async_update_data
    await self.async_check_and_refresh_token()
  File "/config/custom_components/kia_uvo/coordinator.py", line 166, in async_check_and_refresh_token
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 120, in check_and_refresh_token
    self.initialize()
  File "/usr/local/lib/python3.11/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 64, in initialize
    self.token: Token = self.api.login(self.username, self.password)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 199, in login
    device_id = self._get_device_id(stamp)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 1106, in _get_device_id
    _check_response_for_errors(response)
  File "/usr/local/lib/python3.11/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 111, in _check_response_for_errors
    raise APIError(f"Server returned: '{response['resMsg']}'")
hyundai_kia_connect_api.exceptions.APIError: Server returned: 'Invalid request body - Invalid parameter.'

**Comment by bkonings** [comment]
I had the same issue and could figure out why, did find a fix by manually updating the following file:

/config/custom_components/kia_uvo/manifest.json

Adjust the requirement from
  "requirements": ["hyundai_kia_connect_api==3.3.7"],

to
  "requirements": ["hyundai_kia_connect_api==3.3.8"],

**Comment by raducotescu** [comment]
See https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/issues/354 for more details.

**Comment by hmorkemo** [comment]
Thank you @bkonings !
In my manifest.json it said 
"requirements": ["hyundai_kia_connect_api==3.3.10"]
I changed it to "requirements": ["hyundai_kia_connect_api==3.3.8"]
and restarted HA.
Now it works!
I don't know why, or what has to be changed in the integration to make this work by default, but I guess someone will find out and resolve it in the source code.

**Comment by cdnninja** [comment]
Please try the latest version and let us know.

**Comment by finnok** [comment]
You are super !, really appreciated

________________________________
