### ISSUE TITLE
Integration stops working after reload everything seems ok, but some time later it stops again.

### ISSUE THREAD

**Issue by HMvdZijden** [Hyundai-Kia-Connect/kia_uvo#677]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/kia_uvo/blob/master/README.md
**Region and Brand of car**
KIA
**Version of the integration**
v2.10.5
**Describe the bug**
Integration stops working after reload everything seems ok, but some time later it stops again.
One must do a reload to get it working again.

**Debug logs if an error occurred**
File "/usr/local/lib/python3.11/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 718, in _get_cached_vehicle_state
_check_response_for_errors(response)
File "/usr/local/lib/python3.11/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 111, in _check_response_for_errors
raise error_code_mapping[response["resCode"]](response["resMsg"])
hyundai_kia_connect_api.exceptions.DeviceIDError: Invalid request body - Invalid deviceId.
2023-07-16 22:00:02.921 DEBUG (MainThread) [custom_components.kia_uvo.coordinator] Finished fetching kia_uvo data in 0.781 seconds (success: False)
2023-07-16 22:05:00.253 WARNING (MainThread) [homeassistant.helpers.service] Unable to find referenced entities switch.ketel_led_groen or it is/they are currently not available
2023-07-16 22:30:02.854 ERROR (MainThread) [custom_components.kia_uvo.coordinator] Unexpected error fetching kia_uvo data: Invalid request body - Invalid deviceId.
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
self.data = await self._async_update_data()

**To Reproduce**
Just wait

**Expected behavior**

**Screenshots**

**Additional context**
Removed integration completely, new download and install, everything exactly the same.

**Comment by mkroeber** [comment]
I have the same problem with Hyundai
