### ISSUE TITLE
Unexpected error fetching kia_uvo data: maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by chlaa** [Hyundai-Kia-Connect/kia_uvo#686]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/kia_uvo/blob/master/README.md
**Region and car**
UK/EU Kia Niro EV

**Version of the integration**
2.10.6

**Describe the bug**
The integration started to fail to initialise at 20:45 BST today (2023-07-28). The Kia Connect app works fine and updates status OK. 

**Debug logs if an error occurred**

This error originated from a custom integration.

Logger: custom_components.kia_uvo.coordinator
Source: custom_components/kia_uvo/coordinator.py:166
Integration: Kia Uvo / Hyundai Bluelink (documentation, issues)
First occurred: 21:16:23 (6 occurrences)
Last logged: 21:29:41

Unexpected error fetching kia_uvo data: maximum recursion depth exceeded while calling a Python object
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/kia_uvo/coordinator.py", line 107, in _async_update_data
    await self.async_check_and_refresh_token()
  File "/config/custom_components/kia_uvo/coordinator.py", line 166, in async_check_and_refresh_token
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 120, in check_and_refresh_token
    self.initialize()
  File "/usr/local/lib/python3.11/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 64, in initialize
    self.token: Token = self.api.login(self.username, self.password)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 205, in login
    stamp = self._get_stamp()
            ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 1086, in _get_stamp
    return self._get_stamp()
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 1086, in _get_stamp
    return self._get_stamp()
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 1086, in _get_stamp
    return self._get_stamp()
           ^^^^^^^^^^^^^^^^^
  [Previous line repeated 967 more times]
  File "/usr/local/lib/python3.11/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 1071, in _get_stamp
    self.stamps = requests.get(self.stamps_url).json()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 454, in send
    conn = self.get_connection(request.url, proxies)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 356, in get_connection
    conn = self.poolmanager.connection_from_url(url)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/poolmanager.py", line 299, in connection_from_url
    return self.connection_from_host(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/poolmanager.py", line 246, in connection_from_host
    return self.connection_from_context(request_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/poolmanager.py", line 261, in connection_from_context
    return self.connection_from_pool_key(pool_key, request_context=request_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/poolmanager.py", line 282, in connection_from_pool_key
    pool = self._new_pool(scheme, host, port, request_context=request_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/poolmanager.py", line 214, in _new_pool
    return pool_cls(host, port, **request_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 949, in __init__
    HTTPConnectionPool.__init__(
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 191, in __init__
    ConnectionPool.__init__(self, host, port)
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 86, in __init__
    self.host = _normalize_host(host, scheme=self.scheme)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1111, in _normalize_host
    host = normalize_host(host, scheme)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/url.py", line 300, in _normalize_host
    b".".join([_idna_encode(label) for label in host.split(".")])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/url.py", line 300, in <listcomp>
    b".".join([_idna_encode(label) for label in host.split(".")])
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/url.py", line 306, in _idna_encode
    if name and any(ord(x) >= 128 for x in name):
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/url.py", line 306, in <genexpr>
    if name and any(ord(x) >= 128 for x in name):
                    ^^^^^^
RecursionError: maximum recursion depth exceeded while calling a Python object

Outlined here: https://github.com/fuatakgun/kia_uvo/blob/master/README.md

**To Reproduce**
Restart Home Assistant and wait for integration to initialise. 

**Expected behavior**
Integration loads fine. 

**Screenshots**

**Additional context**

**Comment by mjmeierhoefer** [comment]
Having the same problem. Does anybody have a solution?

**Comment by fuslwusl** [comment]
Same problem! Any help?

**Comment by timvh-dev** [comment]
Same problem here

**Comment by Happyboy0980** [comment]
Same isseu with the EV6.

**Comment by xelemorf** [comment]
Same issue with Kia Proceed 2023.

**Comment by Nico72120** [comment]
Same issue

**Comment by kalaws** [comment]
Same issue. Ioniq 5 Europe.

**Comment by HansNetcom** [comment]
Same problem e-Nero Europe NL

**Comment by jsuanet** [comment]
And another one with the same problem Kia Niro EV Europe

**Comment by robaw** [comment]
Same issue, was this a change with the Kia/Hyundai API that broke this?

**Comment by dg362** [comment]
The problem started sometime yesterday evening, but the actual time you see the error will be dependent on settings for refresh, etc.
For me, the first error was as below. But the underlying content of the error matches the original post, so no point in re-stating that in full.
I've disabled the integration, for now, to stop this constantly trying to make a connection to Kia and just failing.
I am running v2.10.6, connecting to Kia EU for a Kia Niro EV, and am based in the UK.

```python
2023-07-28 20:17:52.056 ERROR (MainThread) [custom_components.kia_uvo.coordinator] Error fetching kia_uvo data: Error communicating with API: maximum recursion depth exceeded while calling a Python object
2023-07-28 22:26:02.362 ERROR (MainThread) [custom_components.kia_uvo.coordinator] Unexpected error fetching kia_uvo data: maximum recursion depth exceeded while calling a Python object
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/kia_uvo/coordinator.py", line 142, in _async_update_data
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by Wolf-Code** [comment]
Everyone, saying you have the same problem is not helping anyone and in fact making it harder for people to have a meaningful discussion here. Simply put a thumbs up on the issue so we have a nice counter of how many people have this issue.

**Comment by FerryBultje** [comment]
Same issue. Ioniq 4 Europe.

**Comment by hmmbob** [comment]
Probable underlying issue: https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/issues/370

**Comment by ZuinigeRijder** [comment]
Root cause is outdated timestamp generation:
https://github.com/neoPix/bluelinky-stamps/issues/11

In combination with infinite recursion loop in hyundai_kia_connect_api:
https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/issues/370

**Comment by HansNetcom** [comment]
may this add some to fix the problemLogger: homeassistant.components.websocket_api.http.connection
Source: custom_components/kia_uvo/coordinator.py:159 
Integration: Home Assistant WebSocket API (documentation, issues) 
First occurred: 28 juli 2023 om 22:12:50 (4 occurrences) 
Last logged: 13:38:08

[140454434003344] maximum recursion depth exceeded while calling a Python object
[140454364622096] maximum recursion depth exceeded while calling a Python object
[140454373905872] maximum recursion depth exceeded while calling a Python object
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 205, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1965, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2005, in _execute_service
    return await cast(
           ^^^^^^^^^^^
  File "/config/custom_components/kia_uvo/services.py", line 49, in async_handle_force_update
    await coordinator.async_force_update_all()
  File "/config/custom_components/kia_uvo/coordinator.py", line 159, in async_force_update_all
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 109, in force_refresh_all_vehicles_states
    self.force_refresh_vehicle_state(vehicle_id)
  File "/usr/local/lib/python3.11/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 114, in force_refresh_vehicle_state
    self.api.force_refresh_vehicle_state(self.token, vehicle)
  File "/usr/local/lib/python3.11/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 326, in force_refresh_vehicle_state
    state = self._get_forced_vehicle_state(token, vehicle)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 740, in _get_forced_vehicle_state
    url, headers=self._get_authenticated_headers(token)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 196, in _get_authenticated_headers
    "Stamp": self._get_stamp(),
             ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 1086, in _get_stamp
    return self._get_stamp()
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 1086, in _get_stamp
    return self._get_stamp()
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 1086, in _get_stamp
    return self._get_stamp()
           ^^^^^^^^^^^^^^^^^
  [Previous line repeated 965 more times]
  File "/usr/local/lib/python3.11/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 1071, in _get_stamp
    self.stamps = requests.get(self.stamps_url).json()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 454, in send
    conn = self.get_connection(request.url, proxies)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 356, in get_connection
    conn = self.poolmanager.connection_from_url(url)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/poolmanager.py", line 299, in connection_from_url
    return self.connection_from_host(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/poolmanager.py", line 246, in connection_from_host
    return self.connection_from_context(request_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/poolmanager.py", line 261, in connection_from_context
    return self.connection_from_pool_key(pool_key, request_context=request_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/poolmanager.py", line 282, in connection_from_pool_key
    pool = self._new_pool(scheme, host, port, request_context=request_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/poolmanager.py", line 214, in _new_pool
    return pool_cls(host, port, **request_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 949, in __init__
    HTTPConnectionPool.__init__(
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 191, in __init__
    ConnectionPool.__init__(self, host, port)
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 86, in __init__
    self.host = _normalize_host(host, scheme=self.scheme)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1111, in _normalize_host
    host = normalize_host(host, scheme)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/url.py", line 300, in _normalize_host
    b".".join([_idna_encode(label) for label in host.split(".")])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/url.py", line 300, in <listcomp>
    b".".join([_idna_encode(label) for label in host.split(".")])
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/url.py", line 306, in _idna_encode
    if name and any(ord(x) >= 128 for x in name):
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/url.py", line 306, in <genexpr>
    if name and any(ord(x) >= 128 for x in name):
                    ^^^^^^
RecursionError: maximum recursion depth exceeded while calling a Python object

**Comment by cdnninja** [comment]
Could someone drop a pr for increasing the api version in manifest to 3.4.0? This should resolve.  I'm not by a pc but can merge if someone does that.

**Comment by erikgeurts** [comment]
> Could someone drop a pr for increasing the api version in manifest to 3.4.0? This should resolve. I'm not by a pc but can merge if someone does that.

You mean here?
https://github.com/Hyundai-Kia-Connect/kia_uvo/blob/0a1fd64a1ad8d2eb31bea02ecf06498716923221/custom_components/kia_uvo/manifest.json#L10

**Comment by kalaws** [comment]
@cdnninja done!

**Comment by cdnninja** [comment]
Thank you!   Try update from "master" in HACS and let us know!

**Comment by jsuanet** [comment]
Great, did an update of the integration from "master" in HACS, restarted HA and its working again!

**Comment by kalaws** [comment]
Well, I'm getting an error 500 from Hyundai... Perhaps too many requests on my end or something. If it works for you, guess I'll be next :)

**Comment by jsuanet** [comment]
> 

Did you restart HA after you redownloaded the master branch via HACS?

**Comment by kalaws** [comment]
For some reason I cannot get UI config to load with `master`

**Comment by GarryG** [comment]
Tried downloading the master branch twice - the manifest shows the required api version 3.4, so I assume the download itself worked - still stuck at initializing, though, like before ... with the "recursion" error in the debug log ... am I missing something?

**Comment by hmmbob** [comment]
`master` works for me again. 

> Tried downloading the master branch twice - the manifest shows the required api version 3.4, so I assume the download itself worked - still stuck at initializing, though, like before ... with the "recursion" error in the debug log ... am I missing something?

You did try to reboot completely, right? Not just "reload integration"?

**Comment by fuatakgun** [comment]
Thanks all for quick solution and responses

**Comment by cromelex** [comment]
I'm still seeing this issue, even after redownloading the latest version and doing a full reboot.

```
This error originated from a custom integration.

Logger: custom_components.kia_uvo.coordinator
Source: custom_components/kia_uvo/coordinator.py:166
Integration: Kia Uvo / Hyundai Bluelink (documentation, issues)
First occurred: 00:15:22 (70 occurrences)
Last logged: 03:57:45

Unexpected error fetching kia_uvo data: maximum recursion depth exceeded while calling a Python object
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/kia_uvo/coordinator.py", line 107, in _async_update_data
    await self.async_check_and_refresh_token()
  File "/config/custom_components/kia_uvo/coordinator.py", line 166, in async_check_and_refresh_token
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 120, in check_and_refresh_token
    self.initialize()
  File "/usr/local/lib/python3.11/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 64, in initialize
    self.token: Token = self.api.login(self.username, self.password)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 205, in login
    stamp = self._get_stamp()
            ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 1086, in _get_stamp
    return self._get_stamp()
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 1086, in _get_stamp
    return self._get_stamp()
           ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 1086, in _get_stamp
    return self._get_stamp()
           ^^^^^^^^^^^^^^^^^
  [Previous line repeated 967 more times]
  File "/usr/local/lib/python3.11/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 1071, in _get_stamp
    self.stamps = requests.get(self.stamps_url).json()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 454, in send
    conn = self.get_connection(request.url, proxies)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/requests/adapters.py", line 356, in get_connection
    conn = self.poolmanager.connection_from_url(url)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/poolmanager.py", line 299, in connection_from_url
    return self.connection_from_host(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/poolmanager.py", line 246, in connection_from_host
    return self.connection_from_context(request_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/poolmanager.py", line 261, in connection_from_context
    return self.connection_from_pool_key(pool_key, request_context=request_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/poolmanager.py", line 282, in connection_from_pool_key
    pool = self._new_pool(scheme, host, port, request_context=request_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/poolmanager.py", line 214, in _new_pool
    return pool_cls(host, port, **request_context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 949, in __init__
    HTTPConnectionPool.__init__(
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 191, in __init__
    ConnectionPool.__init__(self, host, port)
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 86, in __init__
    self.host = _normalize_host(host, scheme=self.scheme)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/connectionpool.py", line 1111, in _normalize_host
    host = normalize_host(host, scheme)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/url.py", line 300, in _normalize_host
    b".".join([_idna_encode(label) for label in host.split(".")])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/url.py", line 300, in <listcomp>
    b".".join([_idna_encode(label) for label in host.split(".")])
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/url.py", line 306, in _idna_encode
    if name and any(ord(x) >= 128 for x in name):
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/urllib3/util/url.py", line 306, in <genexpr>
    if name and any(ord(x) >= 128 for x in name):
                    ^^^^^^
RecursionError: maximum recursion depth exceeded while calling a Python object

```

**Comment by hmmbob** [comment]
What do you consider "latest version"? Did you select 'master'?

**Comment by jsuanet** [comment]
@cromelex Did you select the "master" version?
![image](https://github.com/Hyundai-Kia-Connect/kia_uvo/assets/75206491/eafb2b53-14b7-4be7-b3e8-d0aac2cc78b1)

**Comment by cromelex** [comment]
Thanks guys, my bad, I was specifically selecting v2.10.6 instead of master. 

It is fixed, working again as soon as I rebooted after putting master.
