### ISSUE TITLE
Hyundai/Kia Connect Failed to set-up

### ISSUE THREAD

**Issue by steveconrad** [Hyundai-Kia-Connect/kia_uvo#687]
I noticed yesterday that the Hyundai connect integrations is no longer returning any information. The integration shows the message 'Failed to set-up' and reloading the integration has no effect. 

I let the integration retry to capture some logs. Not much there aside from:

----------------------

2023-07-29 09:00:06.919 WARNING (MainThread) [custom_components.ecowitt] Unhandled sensor type runtime value 3, file a PR.
2023-07-29 09:00:06.920 WARNING (MainThread) [custom_components.ecowitt] Unhandled sensor type interval value 60, file a PR.
2023-07-29 09:00:50.404 DEBUG (MainThread) [custom_components.kia_uvo.coordinator] Finished fetching kia_uvo data in 60.023 seconds (success: True)
2023-07-29 09:00:50.404 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Hyundai Europe ******.******@gmail.com for kia_uvo
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 390, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/kia_uvo/__init__.py", line 53, in async_setup_entry
    await coordinator.async_config_entry_first_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 251, in async_config_entry_first_refresh
    await self._async_refresh(
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 283, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/kia_uvo/coordinator.py", line 107, in _async_update_data
    await self.async_check_and_refresh_token()
  File "/config/custom_components/kia_uvo/coordinator.py", line 166, in async_check_and_refresh_token
    await self.hass.async_add_executor_job(
asyncio.exceptions.CancelledError

----------------------

Has something in the api altered to that the integration is now failing?

this is for version v2.10.6. The bluelink app is working OK and showing data.

**Comment by kalaws** [comment]
Perhaps same as #686 ?

**Comment by steveconrad** [comment]
Based on the timespan of the other issue, I'd suspect so. But as I didn't notice any mention of recursion in what I was seeing, I thought I'd post what I was getting to assist on debugging.

**Comment by GarryG** [comment]
Same here, stopped getting data around 21:32 GMT+2... Hyundai messing around again?

**Comment by fuatakgun** [comment]
Looks same, test with master and confirm

**Comment by steveconrad** [comment]
New version appeared overnight - I've updated and I'm back connected!
v2.10.7
