### ISSUE TITLE
Kia uvo won't start climate control after automation

### ISSUE THREAD

**Issue by RickM1234** [Hyundai-Kia-Connect/kia_uvo#734]
**Region and Brand of car**
Europe, Kia EV6

**Version of the integration**
2.14.2

**Describe the bug**
After creating an automation my climate won't start in my car. When I try to run the "climate" part of the automation it says: "Unknown Error".
When I try to run the full automation it'll run, and gives no instant errors.

**Debug logs if an error occurred**

Logger: homeassistant.helpers.script.websocket_api_script
Source: helpers/script.py:468
First occurred: 07:24:28 (10 occurrences)
Last logged: 07:31:10

websocket_api script: Error executing script. Unexpected error for call_service at pos 1: Invalid request body - Invalid deviceId.
websocket_api script: If at step 1: Error executing script. Unexpected error for call_service at pos 1: Invalid request body - Invalid deviceId.
websocket_api script: Error executing script. Unexpected error for if at pos 1: Invalid request body - Invalid deviceId.
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 468, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 704, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 666, in _async_run_long_action
    return long_task.result()
           ^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2012, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2049, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/kia_uvo/services.py", line 70, in async_handle_start_climate
    await coordinator.async_start_climate(vehicle_id, climate_request_options)
  File "/config/custom_components/kia_uvo/coordinator.py", line 198, in async_start_climate
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 134, in start_climate
    return self.api.start_climate(self.token, self.get_vehicle(vehicle_id), options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 835, in start_climate
    _check_response_for_errors(response)
  File "/usr/local/lib/python3.11/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 113, in _check_response_for_errors
    raise error_code_mapping[response["resCode"]](response["resMsg"])
hyundai_kia_connect_api.exceptions.DeviceIDError: Invalid request body - Invalid deviceId. 

**Screenshots**
![image](https://github.com/Hyundai-Kia-Connect/kia_uvo/assets/149004232/cc085752-0ee0-4ed0-8883-54fc130e0fa6)

**Comment by fuatakgun** [comment]
Before this automation, try to reload the integration, there is another issue ongoing about this. Until then, reloading is required before these attempts to guarantee successful run.

**Comment by RickM1234** [comment]
Thank's. I tried to automate the reload since I don't want to restart it myself everytime.
Unfortunatly the following doesn't work.

![image](https://github.com/Hyundai-Kia-Connect/kia_uvo/assets/149004232/4d33cac8-b7fd-409d-9567-fb8a3a0e910d)

**Comment by fuatakgun** [comment]
It would work as long as you put the correct variables in place :-)

**Comment by RickM1234** [comment]
Sorry, I'm kind of new into HA. What do you mean with the correct variables? What should be the correct variables?

**Comment by fuatakgun** [comment]
you need to share the YAML code for reload config entry

**Comment by fuatakgun** [comment]
Check #660
