### ISSUE TITLE
Integration with UK GV60

### ISSUE THREAD

**Issue by jmrush97** [Hyundai-Kia-Connect/kia_uvo#746]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/kia_uvo/blob/master/README.md
**Region and Brand of car**
UK is not listed as yet, mobile app is connecting to accounts-eu.genesis.com

**Version of the integration**

**Describe the bug**

**Debug logs if an error occurred**

Outlined here: https://github.com/fuatakgun/kia_uvo/blob/master/README.md
2023-11-12 11:46:09.273 ERROR (MainThread) [custom_components.kia_uvo.config_flow] Unexpected exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 234, in login
    authorization_code = self._get_authorization_code_with_redirect_url(
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 1165, in _get_authorization_code_with_redirect_url
    parsed_url = urlparse(response["redirectUrl"])
KeyError: 'redirectUrl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/kia_uvo/config_flow.py", line 159, in async_step_user
    await validate_input(self.hass, user_input)
  File "/config/custom_components/kia_uvo/config_flow.py", line 63, in validate_input
    token: Token = await hass.async_add_executor_job(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 239, in login
    authorization_code = self._get_authorization_code_with_form(
  File "/usr/local/lib/python3.10/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 1189, in _get_authorization_code_with_form
    login_form_action_url = soup.find("form")["action"].replace("&amp;", "&")
TypeError: 'NoneType' object is not subscriptable

**To Reproduce**

Try to login
**Expected behavior**
login works.
**Screenshots**

**Additional context**

**Comment by cdnninja** [comment]
Genesis in the eu isn't supported at this point.

**Comment by fuatakgun** [comment]
@cdnninja do we have any dumps from users?

**Comment by cdnninja** [comment]
#686 covers some of that.  

The work done so far was with me sniffing traffic without a car.   It was similar flow but seemed slightly unique.

**Comment by fuatakgun** [comment]
hmmm, we need some support from the actual users then, right?

**Comment by cdnninja** [comment]
And time to tinker with it.  :)  it gets past stamps and what not.  Just not the whole way.

**Comment by jmrush97** [comment]
What do I need to get for you ?

John

**Comment by mute2014** [comment]
Ill have a car and could pcap on my firewall and dump when you tell me what you exactly need (egv70).
Cheers

**Comment by cdnninja** [comment]
I have a Charles dump.   Someone else needs to code this.  I don't have the time to dedicate to this.   I no longer own a Kia so I'm spending less time on this integration.

**Comment by cdnninja** [comment]
Lets move this to #682
