### ISSUE TITLE
China Kia account cannot log in due to unknown error

### ISSUE THREAD

**Issue by woshixuantao** [Hyundai-Kia-Connect/kia_uvo#757]
Here is the error log

此错误来自自定义集成。

Logger: custom_components.kia_uvo.config_flow
Source: custom_components/kia_uvo/config_flow.py:159
Integration: Hyundai / Kia Connect (documentation, issues)
First occurred: 01:17:48 (1 occurrences)
Last logged: 01:17:48

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/kia_uvo/config_flow.py", line 159, in async_step_user
    await validate_input(self.hass, user_input)
  File "/config/custom_components/kia_uvo/config_flow.py", line 63, in validate_input
    token: Token = await hass.async_add_executor_job(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/hyundai_kia_connect_api/KiaUvoApiCN.py", line 145, in login
    device_id = self._get_device_id()
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/hyundai_kia_connect_api/KiaUvoApiCN.py", line 1018, in _get_device_id
    _check_response_for_errors(response)
  File "/usr/local/lib/python3.11/site-packages/hyundai_kia_connect_api/KiaUvoApiCN.py", line 92, in _check_response_for_errors
    raise APIError(f"Server returned: '{response['resMsg']}'")
hyundai_kia_connect_api.exceptions.APIError: Server returned: 'Invalid request body - Invalid parameter.'
![image](https://github.com/Hyundai-Kia-Connect/kia_uvo/assets/5766485/1ec44fea-3033-4c65-981e-da0b00f0e583)

![屏幕截图 2023-11-21 012334](https://github.com/Hyundai-Kia-Connect/kia_uvo/assets/5766485/05df850b-ab92-470f-a6c8-5cf6227c1f7b)

**Comment by cdnninja** [comment]
Will need someone in China to debug this.  @toraidl could you take a look?

**Comment by woshixuantao** [comment]
I hope if you have time, you can help troubleshoot the problem. Thank you very much!

**Comment by 15075550180** [comment]
Finally found someone who encountered the same problem. I hope the expert can help to solve it.Thank you very much!

**Comment by LitchiCherry** [comment]
The same problem.
EV5 with Kia connect China version.

**Comment by LitchiCherry** [comment]
This error message is from kia server? Maybe they have updated the api or banned the integration?

**Comment by cdnninja** [comment]
More likely api changed.  Someone needs to sniff the traffic and create a pull request with the fix.

**Comment by LitchiCherry** [comment]
> More likely api changed. Someone needs to sniff the traffic and create a pull request with the fix.

Tried sniffing the request and app returned error. Mitm has been restricted when app visiting “prd.cn-ccapi.kia.com”. Maybe app coe should be modified before sniffing.

**Comment by woshixuantao** [comment]
What do we need to do? I'm here to help.

**Comment by cdnninja** [comment]
Sniff the traffic from the native app or website.  Compare to our code in the api repo and make any corrections.

**Comment by LitchiCherry** [comment]
> Sniff the traffic from the native app or website. Compare to our code in the api repo and make any corrections.
Tried but failed. Once MitM, kia connect prevented me from logging in and returned error.

**Comment by cdnninja** [comment]
> > Sniff the traffic from the native app or website. Compare to our code in the api repo and make any corrections.
> 
> Tried but failed. Once MitM on iOS, kia connect prevented me from logging in and returned error

Knox player to run android with Charles proxy is my usual approach but each apps different.  

If a website exists in China for Kia Hyundai can also just use browsers developer mode.

**Comment by woshixuantao** [comment]
I looked around and it looks like it was intercepted. 😟
![Uploading Screenshot_2024-01-31-17-07-01-58_7fac49e5329bfa70bf0c1257a1a51d55.jpg…]()

**Comment by LitchiCherry** [comment]
图挂了

**Comment by woshixuantao** [comment]
![Screenshot_2024-01-31-17-07-01-58_7fac49e5329bfa70bf0c1257a1a51d55](https://github.com/Hyundai-Kia-Connect/kia_uvo/assets/5766485/658caa03-c07a-44fa-b4d1-b31b4c18ebfa)

**Comment by LitchiCherry** [comment]
这个只是网络信息，数据包内容没有看到。

**Comment by woshixuantao** [comment]
> 这个只是网络信息，数据包内容没有看到。

我不知道他是不是拦截代理方式打开kia Connect 抓包里面就是没有数据 还是我的抓包方式有问题

**Comment by LitchiCherry** [comment]
> > 这个只是网络信息，数据包内容没有看到。
> 
> 我不知道他是不是拦截代理方式打开kia Connect 抓包里面就是没有数据 还是我的抓包方式有问题

是的，我在iOS上面一样的，应该是对SSL证书进行了校验

**Comment by LitchiCherry** [comment]
no way to support China EV?

**Comment by cdnninja** [comment]
Yes can be done but someone in China needs to take this on.
