### ISSUE TITLE
Fails on boot

### ISSUE THREAD

**Issue by kalaws** [Hyundai-Kia-Connect/kia_uvo#782]
**Region and Brand of car**
EUR, Hyunday Ioniq 5
**Version of the integration**
2.16.3

**Describe the bug**
The integration fails at boot and it does not help to reload or redownload.
**Debug logs if an error occurred**
```
Logger: homeassistant.config_entries
Source: config_entries.py:402
First occurred: 19:39:23 (1 occurrences)
Last logged: 19:39:23

Error setting up entry Hyundai Europe simon.hallberg@me.com for kia_uvo
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 402, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/kia_uvo/__init__.py", line 53, in async_setup_entry
    await coordinator.async_config_entry_first_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in async_config_entry_first_refresh
    await self._async_refresh(
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 300, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/kia_uvo/coordinator.py", line 107, in _async_update_data
    await self.async_check_and_refresh_token()
  File "/config/custom_components/kia_uvo/coordinator.py", line 166, in async_check_and_refresh_token
    await self.hass.async_add_executor_job(
asyncio.exceptions.CancelledError: Global task timeout
```

**To Reproduce**
No idea.

**Expected behavior**
Load.

**Comment by ridderr** [comment]
I'm getting some additionalerror informaton:
`Unexpected error fetching kia_uvo data: 'redirectUrl'
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 237, in login
    authorization_code = self._get_authorization_code_with_redirect_url(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 1184, in _get_authorization_code_with_redirect_url
    parsed_url = urlparse(response["redirectUrl"])
                          ~~~~~~~~^^^^^^^^^^^^^^^
KeyError: 'redirectUrl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 300, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/kia_uvo/coordinator.py", line 107, in _async_update_data
    await self.async_check_and_refresh_token()
  File "/config/custom_components/kia_uvo/coordinator.py", line 166, in async_check_and_refresh_token
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 124, in check_and_refresh_token
    self.initialize()
  File "/usr/local/lib/python3.11/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 68, in initialize
    self.token: Token = self.api.login(self.username, self.password)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 242, in login
    authorization_code = self._get_authorization_code_with_form(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 1282, in _get_authorization_code_with_form
    parsed_url = urlparse(response["redirectUrl"])
                          ~~~~~~~~^^^^^^^^^^^^^^^
KeyError: 'redirectUrl'`

**Comment by cdnninja** [comment]
Does the native app work right now?

**Comment by ridderr** [comment]
Yes all working fine.

**Comment by VictorTorrens** [comment]
Same here, also in Europe

**Comment by kalaws** [comment]
> Does the native app work right now?

Yep

**Comment by Mkay505** [comment]
Same here, EU Version. Both car accounts.

**Comment by RuneNyhuus** [comment]
Same error here.. EU

**Comment by Homergy** [comment]
Same error for me as well.
No longer able to get any connection though home assistant. The Android app does still work 
, however I did notice the Android app is updated might be related?

**Comment by fuatakgun** [comment]
Debug logs please, I am located in EU and it is working fine

**Comment by ridderr** [comment]
I hope this helps.

[home-assistant_kia_uvo_2023-12-23T19-38-58.219Z.log](https://github.com/Hyundai-Kia-Connect/kia_uvo/files/13760262/home-assistant_kia_uvo_2023-12-23T19-38-58.219Z.log)

**Comment by Homergy** [comment]
2023-12-23 21:56:52.326 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Kia Europe xxxxx@hotmail.com for kia_uvo
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 402, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/kia_uvo/__init__.py", line 53, in async_setup_entry
    await coordinator.async_config_entry_first_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in async_config_entry_first_refresh
    await self._async_refresh(
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 300, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/kia_uvo/coordinator.py", line 107, in _async_update_data
    await self.async_check_and_refresh_token()
  File "/config/custom_components/kia_uvo/coordinator.py", line 166, in async_check_and_refresh_token
    await self.hass.async_add_executor_job(
asyncio.exceptions.CancelledError: Global task timeout
2023-12-23 21:56:52.333 WARNING (MainThread) [homeassistant.bootstrap] Setup timed out for stage 2 - moving forward

**Comment by cdnninja** [comment]
Bluelinky is also seen a report of login issues.  API may have changed again. 

https://github.com/Hacksore/bluelinky/issues/270

**Comment by fuatakgun** [comment]
Thanks, apparently kia/Hyundai had changed something again so we should try to reverse engineer the new stuff to make it work.

Please stand by but it will take time

**Comment by kalaws** [comment]
Up and running again. Strange.

**Comment by Homergy** [comment]
Same here, reloaded the integration it's working again.

I have an automation which tried that over 10times, tried to reboot nothing worked for the past few hours, but now it's solved again...
Possibly it was Kia server side issue?
