### ISSUE TITLE
Failed Setup Error

### ISSUE THREAD

**Issue by franquosino** [Hyundai-Kia-Connect/kia_uvo#786]
Just purchased Kona Electric in Vancouver, Canada.

**Version of the integration** is v2.18.0

**Describe the bug**
Despite several attempts at reloading, the setup keeps failing.

This error originated from a custom integration.

Logger: custom_components.kia_uvo.coordinator
Source: helpers/update_coordinator.py:300
Integration: Hyundai / Kia Connect (documentation, issues)
First occurred: December 27, 2023 at 10:00:30 PM (400 occurrences)
Last logged: 6:59:54 AM

Unexpected error fetching kia_uvo data: invalid literal for int() with base 16: 'OFF'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 300, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/kia_uvo/coordinator.py", line 142, in _async_update_data
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 79, in update_all_vehicles_with_cached_state
    self.update_vehicle_with_cached_state(vehicle_id)
  File "/usr/local/lib/python3.11/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 84, in update_vehicle_with_cached_state
    self.api.update_vehicle_with_cached_state(self.token, vehicle)
  File "/usr/local/lib/python3.11/site-packages/hyundai_kia_connect_api/KiaUvoApiCA.py", line 177, in update_vehicle_with_cached_state
    self._update_vehicle_properties_base(vehicle, state)
  File "/usr/local/lib/python3.11/site-packages/hyundai_kia_connect_api/KiaUvoApiCA.py", line 247, in _update_vehicle_properties_base
    tempIndex = get_hex_temp_into_index(
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/hyundai_kia_connect_api/utils.py", line 36, in get_hex_temp_into_index
    value = int(value, 16)
            ^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 16: 'OFF'

Any thoughts?
Thanks.

**Comment by cdnninja** [comment]
What year?  Looks like this changed.

**Comment by franquosino** [comment]
It's a 2024

**Comment by cdnninja** [comment]
Could you go to HACS and click redownload and select the version of "master" and let me know if that solves it or if it has a new error? 

https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/pull/468

**Comment by franquosino** [comment]
Just reloaded the integration with the master version. However, as I was debating whether this issue might be related to the fact that my HA email is different than the Bluelink's, I had the dealership change their email on file. Now, I have to wait until the Bluelink app activate my account with this new email. I will let know as soon as I can log on Bluelink and setup your integration with the master version. 

I really appreciate your help here.

**Comment by cdnninja** [comment]
It wouldn't be the login.  

What's happening is the reported temp is reporting as off.  It used to just report the lowest temp when off.  

We aren't handling the word off as we expect a number.  

Kia Hyundai tinker with this api from time to time so we have to keep up with them on the new cars.

**Comment by franquosino** [comment]
Just reinstalled the integration, configured, and reloaded it. No go. Still the exact same error: invalid literal for int() with base 16: 'OFF'

I still can't log in the Bluelink app, but your integration doesn't get a rejected login.

**Comment by cdnninja** [comment]
If native app doesn't work neither will our app.   To confirm you did the reinstall from master step?

**Comment by franquosino** [comment]
Yes, I did.

**Comment by cdnninja** [comment]
To confirm error is exact same? Like numbers etc match?   If so that means it didn't update.  Line numbers should change at a minimum.  

Make sure to restart HA after installing from master.

**Comment by franquosino** [comment]
Sorry, the error I was referring to is the one that appears on the integration page, not the log. 
![image](https://github.com/Hyundai-Kia-Connect/kia_uvo/assets/31945267/5acaa60e-2a4a-4a9d-b57c-a49cc790b7d0)

Usual HA log doesn't seem to show anything. When I run debug logging on the integration, I get:

2023-12-28 17:07:21.850 DEBUG (MainThread) [custom_components.kia_uvo.coordinator] Finished fetching kia_uvo data in 0.899 seconds (success: False)
2023-12-28 17:07:37.957 ERROR (MainThread) [frontend.js.latest.202312082] Uncaught error from Chrome 120.0.0.0 on Windows 10
TypeError: Cannot read properties of null (reading 'removeEventListener')
renderHeading (src/components/ha-dialog.ts:51:24)
apply (src/scoped-custom-element-registry.js:262:44)
mainWindow.history.pushState (src/dialogs/make-dialog-manager.ts:129:7)
2023-12-28 17:07:46.405 DEBUG (MainThread) [custom_components.kia_uvo.coordinator] Finished fetching kia_uvo data in 0.881 seconds (success: False)
2023-12-28 17:07:52.518 DEBUG (MainThread) [custom_components.kia_uvo.coordinator] Finished fetching kia_uvo data in 0.873 seconds (success: False)
2023-12-28 17:07:56.349 DEBUG (MainThread) [custom_components.kia_uvo.coordinator] Finished fetching kia_uvo data in 0.891 seconds (success: False)
2023-12-28 17:08:02.531 DEBUG (MainThread) [custom_components.kia_uvo.coordinator] Finished fetching kia_uvo data in 0.858 seconds (success: False)
2023-12-28 17:08:13.751 DEBUG (MainThread) [custom_components.kia_uvo.coordinator] Finished fetching kia_uvo data in 0.882 seconds (success: False)

**Comment by cdnninja** [comment]
The error about the value in full form would be helpful with stack trace.

**Comment by franquosino** [comment]
Pardon my ignorance. Where would I find such information?

**Comment by cdnninja** [comment]
Same spot as the above logs but you may need two tabs open. One to setup the integration another to watch the live logs.  Your first post contains the example of what I am looking for.  

As a note additional debug logs can also be enabled and may be handy.  Enabling them is outlined on the readme of this github repo.

**Comment by franquosino** [comment]
Ok. I can do that. 

However, I still do not have access to the Bluelink app, after changing email with the dealership. I don't feel I'm working on a solid basis without access to my account. It can take up to 24 hrs to activate the app with the  new email. 

So, I'll wait until that access issue is sorted out and get back to you with more log content.

Thanks again.

**Comment by franquosino** [comment]
Just got off the phone with Hyundai regarding the activation of my account, as I still cannot connect through the app. However, following your recommended procedure, I generated further debug log, which is pasted below. It appears that the integration does make a connection and collects information about the car. Hopefully, it's meaningful to you in identifying why the setup fails nonetheless.  Let me know if I can do anything else.


023-12-29 09:24:09.611 DEBUG (SyncWorker_5) [hyundai_kia_connect_api.KiaUvoApiCA] hyundai_kia_connect_api - Get Vehicles Response {"responseHeader":{"responseCode":0,"responseDesc":"Success"},"result":{"vehicles":[{"vehicleId":"GcEvxvL7rvFiDnwR26lh/A==","nickName":"KONA EV","modelCode":"KE2SEFEMEP20","modelName":"KONA EV","modelYear":"2024","fuelKindCode":"E","trim":"Ultimate -","engine":"","exteriorColor":"R2P","dtcCount":0,"subscriptionStatus":"A","subscriptionEndDate":"20261219","mileageForNextService":11629.4,"daysForNextService":"20241219","overviewMessage":"","defaultVehicle":true,"enrollmentStatus":"7","genType":"G3","valetParkingModeOn":1,"vin":"KM8HE3A67RU004640"}]}}
2023-12-29 09:24:10.160 DEBUG (SyncWorker_0) [hyundai_kia_connect_api.KiaUvoApiCA] hyundai_kia_connect_api - get_cached_vehicle_status response {'responseHeader': {'responseCode': 0, 'responseDesc': 'Success'}, 'result': {'status': {'lastStatusDate': '20231229004702', 'airCtrlOn': False, 'engine': True, 'doorLock': False, 'doorOpen': {'frontLeft': 0, 'frontRight': 0, 'backLeft': 0, 'backRight': 0}, 'trunkOpen': False, 'airTempUnit': 'C', 'airTemp': {'value': 'OFF', 'unit': 0}, 'defrost': False, 'lowFuelLight': False, 'acc': True, 'evStatus': {'batteryCharge': False, 'batteryStatus': 82, 'batteryPlugin': 0, 'remainTime2': {'etc1': {'value': 18, 'unit': 1}, 'etc2': {'value': 150, 'unit': 1}, 'etc3': {'value': 60, 'unit': 1}, 'atc': {'value': 0, 'unit': 1}}, 'drvDistance': [{'rangeByFuel': {'evModeRange': {'value': 361.0, 'unit': 1}, 'totalAvailableRange': {'value': 361.0, 'unit': 1}}, 'type': 2}], 'reservChargeInfos': {'reservChargeInfo': {'reservChargeInfoDetail': {'reservInfo': {'day': [5, 1, 6, 0, 4, 2, 3], 'time': {'time': '3170', 'timeSection': 0}}, 'reservChargeSet': False, 'reservFatcSet': {'defrost': False, 'airTemp': {'value': 'OFF', 'unit': 0, 'hvacTempType': 0}, 'airCtrl': 2, 'heating1': 0}}}, 'reserveChargeInfo2': {'reservChargeInfoDetail': {'reservInfo': {'day': [5, 1, 6, 0, 4, 2, 3], 'time': {'time': '3170', 'timeSection': 0}}, 'reservChargeSet': False, 'reservFatcSet': {'defrost': False, 'airTemp': {'value': 'OFF', 'unit': 0, 'hvacTempType': 0}, 'airCtrl': 2}}}, 'offpeakPowerInfo': {'offPeakPowerFlag': 2, 'offPeakPowerTime1': {'starttime': {'time': '0000', 'timeSection': 0}, 'endtime': {'time': '0630', 'timeSection': 0}}, 'offPeakPowerTime2': {'starttime': {'time': '0000', 'timeSection': 0}, 'endtime': {'time': '0630', 'timeSection': 0}}}, 'reservFlag': 1, 'ect': {'start': {'day': 9, 'time': {'time': '3163', 'timeSection': 0}}, 'end': {'day': 7, 'time': {'time': '3163', 'timeSection': 0}}}, 'targetSOClist': [{'plugType': 0, 'targetSOClevel': 90}, {'plugType': 1, 'targetSOClevel': 90}]}, 'batteryPreconditiong': False, 'wirelessCharging': False, 'batterySoh': 100}, 'hoodOpen': False, 'transCond': True, 'steerWheelHeat': 0, 'tirePressureLamp': {'tirePressureLampAll': 1, 'tirePressureLampFL': 0, 'tirePressureLampFR': 0, 'tirePressureLampRL': 0, 'tirePressureLampRR': 0}, 'battery': {'batSoc': 84, 'batState': 0, 'sjbDeliveryMode': 1, 'batSignalReferenceValue': {'batWarning': 65}, 'powerAutoCutMode': 2}, 'remoteIgnition': True, 'seatHeaterVentInfo': {'drvSeatHeatState': 2, 'astSeatHeatState': 2, 'rlSeatHeatState': 2, 'rrSeatHeatState': 2}, 'sunroofOpen': False, 'lampWireStatus': {'headLamp': {'headLampStatus': False, 'leftLowLamp': False, 'rightLowLamp': False, 'leftHighLamp': False, 'rightHighLamp': False, 'leftBifuncLamp': False, 'rightBifuncLamp': False}, 'stopLamp': {'stopLampStatus': False, 'leftLamp': False, 'rightLamp': False}, 'turnSignalLamp': {'turnSignalLampStatus': False, 'leftFrontLamp': False, 'rightFrontLamp': False, 'leftRearLamp': False, 'rightRearLamp': False}}, 'smartKeyBatteryWarning': False, 'washerFluidStatus': False, 'breakOilStatus': False, 'engineRuntime': {}}}}
2023-12-29 09:24:10.160 DEBUG (SyncWorker_0) [hyundai_kia_connect_api.KiaUvoApiCA] hyundai_kia_connect_api - Old Vehicle Last Updated: None
2023-12-29 09:24:10.160 DEBUG (SyncWorker_0) [hyundai_kia_connect_api.KiaUvoApiCA] hyundai_kia_connect_api - last_updated_at - before 20231229004702
2023-12-29 09:24:10.161 DEBUG (SyncWorker_0) [hyundai_kia_connect_api.KiaUvoApiCA] hyundai_kia_connect_api - last_updated_at - after 2023-12-29 00:47:02+00:00
2023-12-29 09:24:10.161 DEBUG (SyncWorker_0) [hyundai_kia_connect_api.KiaUvoApiCA] hyundai_kia_connect_api - Current Vehicle Last Updated: 2023-12-29 00:47:02+00:00
2023-12-29 09:24:10.736 DEBUG (SyncWorker_7) [hyundai_kia_connect_api.KiaUvoApiCA] hyundai_kia_connect_api - get_cached_vehicle_status response {'responseHeader': {'responseCode': 0, 'responseDesc': 'Success'}, 'result': {'status': {'lastStatusDate': '20231229004702', 'airCtrlOn': False, 'engine': True, 'doorLock': False, 'doorOpen': {'frontLeft': 0, 'frontRight': 0, 'backLeft': 0, 'backRight': 0}, 'trunkOpen': False, 'airTempUnit': 'C', 'airTemp': {'value': 'OFF', 'unit': 0}, 'defrost': False, 'lowFuelLight': False, 'acc': True, 'evStatus': {'batteryCharge': False, 'batteryStatus': 82, 'batteryPlugin': 0, 'remainTime2': {'etc1': {'value': 18, 'unit': 1}, 'etc2': {'value': 150, 'unit': 1}, 'etc3': {'value': 60, 'unit': 1}, 'atc': {'value': 0, 'unit': 1}}, 'drvDistance': [{'rangeByFuel': {'evModeRange': {'value': 361.0, 'unit': 1}, 'totalAvailableRange': {'value': 361.0, 'unit': 1}}, 'type': 2}], 'reservChargeInfos': {'reservChargeInfo': {'reservChargeInfoDetail': {'reservInfo': {'day': [5, 1, 6, 0, 4, 2, 3], 'time': {'time': '3170', 'timeSection': 0}}, 'reservChargeSet': False, 'reservFatcSet': {'defrost': False, 'airTemp': {'value': 'OFF', 'unit': 0, 'hvacTempType': 0}, 'airCtrl': 2, 'heating1': 0}}}, 'reserveChargeInfo2': {'reservChargeInfoDetail': {'reservInfo': {'day': [5, 1, 6, 0, 4, 2, 3], 'time': {'time': '3170', 'timeSection': 0}}, 'reservChargeSet': False, 'reservFatcSet': {'defrost': False, 'airTemp': {'value': 'OFF', 'unit': 0, 'hvacTempType': 0}, 'airCtrl': 2}}}, 'offpeakPowerInfo': {'offPeakPowerFlag': 2, 'offPeakPowerTime1': {'starttime': {'time': '0000', 'timeSection': 0}, 'endtime': {'time': '0630', 'timeSection': 0}}, 'offPeakPowerTime2': {'starttime': {'time': '0000', 'timeSection': 0}, 'endtime': {'time': '0630', 'timeSection': 0}}}, 'reservFlag': 1, 'ect': {'start': {'day': 9, 'time': {'time': '3163', 'timeSection': 0}}, 'end': {'day': 7, 'time': {'time': '3163', 'timeSection': 0}}}, 'targetSOClist': [{'plugType': 0, 'targetSOClevel': 90}, {'plugType': 1, 'targetSOClevel': 90}]}, 'batteryPreconditiong': False, 'wirelessCharging': False, 'batterySoh': 100}, 'hoodOpen': False, 'transCond': True, 'steerWheelHeat': 0, 'tirePressureLamp': {'tirePressureLampAll': 1, 'tirePressureLampFL': 0, 'tirePressureLampFR': 0, 'tirePressureLampRL': 0, 'tirePressureLampRR': 0}, 'battery': {'batSoc': 84, 'batState': 0, 'sjbDeliveryMode': 1, 'batSignalReferenceValue': {'batWarning': 65}, 'powerAutoCutMode': 2}, 'remoteIgnition': True, 'seatHeaterVentInfo': {'drvSeatHeatState': 2, 'astSeatHeatState': 2, 'rlSeatHeatState': 2, 'rrSeatHeatState': 2}, 'sunroofOpen': False, 'lampWireStatus': {'headLamp': {'headLampStatus': False, 'leftLowLamp': False, 'rightLowLamp': False, 'leftHighLamp': False, 'rightHighLamp': False, 'leftBifuncLamp': False, 'rightBifuncLamp': False}, 'stopLamp': {'stopLampStatus': False, 'leftLamp': False, 'rightLamp': False}, 'turnSignalLamp': {'turnSignalLampStatus': False, 'leftFrontLamp': False, 'rightFrontLamp': False, 'leftRearLamp': False, 'rightRearLamp': False}}, 'smartKeyBatteryWarning': False, 'washerFluidStatus': False, 'breakOilStatus': False, 'engineRuntime': {}}}}
2023-12-29 09:24:10.736 DEBUG (SyncWorker_7) [hyundai_kia_connect_api.KiaUvoApiCA] hyundai_kia_connect_api - Old Vehicle Last Updated: 2023-12-29 00:47:02+00:00
2023-12-29 09:24:10.736 DEBUG (SyncWorker_7) [hyundai_kia_connect_api.KiaUvoApiCA] hyundai_kia_connect_api - last_updated_at - before 20231229004702
2023-12-29 09:24:10.736 DEBUG (SyncWorker_7) [hyundai_kia_connect_api.KiaUvoApiCA] hyundai_kia_connect_api - last_updated_at - after 2023-12-29 00:47:02+00:00
2023-12-29 09:24:10.736 DEBUG (SyncWorker_7) [hyundai_kia_connect_api.KiaUvoApiCA] hyundai_kia_connect_api - Current Vehicle Last Updated: 2023-12-29 00:47:02+00:00
2023-12-29 09:24:11.418 DEBUG (MainThread) [custom_components.kia_uvo.coordinator] Finished fetching kia_uvo data in 2.928 seconds (success: False)

**Comment by franquosino** [comment]
I see no error in the usual HA logs since I installed the master version. The only error I get (error communication with API) is on the Integration page as indicated in the picture I posted above.

**Comment by franquosino** [comment]
I deleted the master version, and re-install v2.18.0, with proper HA rebooting. I'm attaching the log, which looks pretty similar to the master version, i.e. getting the car info.  Otherwise, same failed setup error on the integration page, although the HA Core log doesn't show the "ValueError: invalid literal for int() with base 16: 'OFF'" anymore. 

2023-12-29 18:05:22.574 DEBUG (SyncWorker_9) [hyundai_kia_connect_api.KiaUvoApiCA] hyundai_kia_connect_api - Get Vehicles Response {"responseHeader":{"responseCode":0,"responseDesc":"Success"},"result":{"vehicles":[{"vehicleId":"GcEvxvL7rvFiDnwR26lh/A==","nickName":"KONA EV","modelCode":"KE2SEFEMEP20","modelName":"KONA EV","modelYear":"2024","fuelKindCode":"E","trim":"Ultimate -","engine":"","exteriorColor":"R2P","dtcCount":0,"subscriptionStatus":"A","subscriptionEndDate":"20261219","mileageForNextService":11600.2,"daysForNextService":"20241219","overviewMessage":"","defaultVehicle":true,"enrollmentStatus":"7","genType":"G3","valetParkingModeOn":1,"vin":"KM8HE3A67RU004640"}]}}
2023-12-29 18:05:22.708 DEBUG (SyncWorker_3) [hyundai_kia_connect_api.KiaUvoApiCA] hyundai_kia_connect_api - get_cached_vehicle_status response {'responseHeader': {'responseCode': 0, 'responseDesc': 'Success'}, 'result': {'status': {'lastStatusDate': '20231229223158', 'airCtrlOn': False, 'engine': False, 'doorLock': False, 'doorOpen': {'frontLeft': 0, 'frontRight': 0, 'backLeft': 0, 'backRight': 0}, 'trunkOpen': False, 'airTempUnit': 'C', 'airTemp': {'value': 'OFF', 'unit': 0}, 'defrost': False, 'lowFuelLight': False, 'acc': False, 'evStatus': {'batteryCharge': False, 'batteryStatus': 75, 'batteryPlugin': 0, 'remainTime2': {'etc1': {'value': 33, 'unit': 1}, 'etc2': {'value': 275, 'unit': 1}, 'etc3': {'value': 85, 'unit': 1}, 'atc': {'value': 0, 'unit': 1}}, 'drvDistance': [{'rangeByFuel': {'evModeRange': {'value': 329.0, 'unit': 1}, 'totalAvailableRange': {'value': 329.0, 'unit': 1}}, 'type': 2}], 'reservChargeInfos': {'reservChargeInfo': {'reservChargeInfoDetail': {'reservInfo': {'day': [5, 1, 6, 0, 4, 2, 3], 'time': {'time': '3170', 'timeSection': 0}}, 'reservChargeSet': False, 'reservFatcSet': {'defrost': False, 'airTemp': {'value': 'OFF', 'unit': 0, 'hvacTempType': 0}, 'airCtrl': 2, 'heating1': 0}}}, 'reserveChargeInfo2': {'reservChargeInfoDetail': {'reservInfo': {'day': [5, 1, 6, 0, 4, 2, 3], 'time': {'time': '3170', 'timeSection': 0}}, 'reservChargeSet': False, 'reservFatcSet': {'defrost': False, 'airTemp': {'value': 'OFF', 'unit': 0, 'hvacTempType': 0}, 'airCtrl': 2}}}, 'offpeakPowerInfo': {'offPeakPowerFlag': 2, 'offPeakPowerTime1': {'starttime': {'time': '0000', 'timeSection': 0}, 'endtime': {'time': '0630', 'timeSection': 0}}, 'offPeakPowerTime2': {'starttime': {'time': '0000', 'timeSection': 0}, 'endtime': {'time': '0630', 'timeSection': 0}}}, 'reservFlag': 1, 'ect': {'start': {'day': 9, 'time': {'time': '3163', 'timeSection': 0}}, 'end': {'day': 7, 'time': {'time': '3163', 'timeSection': 0}}}, 'targetSOClist': [{'plugType': 0, 'targetSOClevel': 90}, {'plugType': 1, 'targetSOClevel': 90}]}, 'batteryPreconditiong': False, 'wirelessCharging': False, 'batterySoh': 100}, 'hoodOpen': False, 'transCond': True, 'steerWheelHeat': 0, 'tirePressureLamp': {'tirePressureLampAll': 1, 'tirePressureLampFL': 0, 'tirePressureLampFR': 0, 'tirePressureLampRL': 0, 'tirePressureLampRR': 0}, 'battery': {'batSoc': 86, 'batState': 0, 'sjbDeliveryMode': 1, 'batSignalReferenceValue': {'batWarning': 65}, 'powerAutoCutMode': 2}, 'remoteIgnition': True, 'seatHeaterVentInfo': {'drvSeatHeatState': 2, 'astSeatHeatState': 2, 'rlSeatHeatState': 2, 'rrSeatHeatState': 2}, 'sunroofOpen': False, 'lampWireStatus': {'headLamp': {'headLampStatus': False, 'leftLowLamp': False, 'rightLowLamp': False, 'leftHighLamp': False, 'rightHighLamp': False, 'leftBifuncLamp': False, 'rightBifuncLamp': False}, 'stopLamp': {'stopLampStatus': False, 'leftLamp': False, 'rightLamp': False}, 'turnSignalLamp': {'turnSignalLampStatus': False, 'leftFrontLamp': False, 'rightFrontLamp': False, 'leftRearLamp': False, 'rightRearLamp': False}}, 'smartKeyBatteryWarning': False, 'washerFluidStatus': False, 'breakOilStatus': False, 'engineRuntime': {}}}}
2023-12-29 18:05:22.708 DEBUG (SyncWorker_3) [hyundai_kia_connect_api.KiaUvoApiCA] hyundai_kia_connect_api - Old Vehicle Last Updated: None
2023-12-29 18:05:22.708 DEBUG (SyncWorker_3) [hyundai_kia_connect_api.KiaUvoApiCA] hyundai_kia_connect_api - last_updated_at - before 20231229223158
2023-12-29 18:05:22.709 DEBUG (SyncWorker_3) [hyundai_kia_connect_api.KiaUvoApiCA] hyundai_kia_connect_api - last_updated_at - after 2023-12-29 22:31:58+00:00
2023-12-29 18:05:22.709 DEBUG (SyncWorker_3) [hyundai_kia_connect_api.KiaUvoApiCA] hyundai_kia_connect_api - Current Vehicle Last Updated: 2023-12-29 22:31:58+00:00
2023-12-29 18:05:22.844 DEBUG (SyncWorker_1) [hyundai_kia_connect_api.KiaUvoApiCA] hyundai_kia_connect_api - get_cached_vehicle_status response {'responseHeader': {'responseCode': 0, 'responseDesc': 'Success'}, 'result': {'status': {'lastStatusDate': '20231229223158', 'airCtrlOn': False, 'engine': False, 'doorLock': False, 'doorOpen': {'frontLeft': 0, 'frontRight': 0, 'backLeft': 0, 'backRight': 0}, 'trunkOpen': False, 'airTempUnit': 'C', 'airTemp': {'value': 'OFF', 'unit': 0}, 'defrost': False, 'lowFuelLight': False, 'acc': False, 'evStatus': {'batteryCharge': False, 'batteryStatus': 75, 'batteryPlugin': 0, 'remainTime2': {'etc1': {'value': 33, 'unit': 1}, 'etc2': {'value': 275, 'unit': 1}, 'etc3': {'value': 85, 'unit': 1}, 'atc': {'value': 0, 'unit': 1}}, 'drvDistance': [{'rangeByFuel': {'evModeRange': {'value': 329.0, 'unit': 1}, 'totalAvailableRange': {'value': 329.0, 'unit': 1}}, 'type': 2}], 'reservChargeInfos': {'reservChargeInfo': {'reservChargeInfoDetail': {'reservInfo': {'day': [5, 1, 6, 0, 4, 2, 3], 'time': {'time': '3170', 'timeSection': 0}}, 'reservChargeSet': False, 'reservFatcSet': {'defrost': False, 'airTemp': {'value': 'OFF', 'unit': 0, 'hvacTempType': 0}, 'airCtrl': 2, 'heating1': 0}}}, 'reserveChargeInfo2': {'reservChargeInfoDetail': {'reservInfo': {'day': [5, 1, 6, 0, 4, 2, 3], 'time': {'time': '3170', 'timeSection': 0}}, 'reservChargeSet': False, 'reservFatcSet': {'defrost': False, 'airTemp': {'value': 'OFF', 'unit': 0, 'hvacTempType': 0}, 'airCtrl': 2}}}, 'offpeakPowerInfo': {'offPeakPowerFlag': 2, 'offPeakPowerTime1': {'starttime': {'time': '0000', 'timeSection': 0}, 'endtime': {'time': '0630', 'timeSection': 0}}, 'offPeakPowerTime2': {'starttime': {'time': '0000', 'timeSection': 0}, 'endtime': {'time': '0630', 'timeSection': 0}}}, 'reservFlag': 1, 'ect': {'start': {'day': 9, 'time': {'time': '3163', 'timeSection': 0}}, 'end': {'day': 7, 'time': {'time': '3163', 'timeSection': 0}}}, 'targetSOClist': [{'plugType': 0, 'targetSOClevel': 90}, {'plugType': 1, 'targetSOClevel': 90}]}, 'batteryPreconditiong': False, 'wirelessCharging': False, 'batterySoh': 100}, 'hoodOpen': False, 'transCond': True, 'steerWheelHeat': 0, 'tirePressureLamp': {'tirePressureLampAll': 1, 'tirePressureLampFL': 0, 'tirePressureLampFR': 0, 'tirePressureLampRL': 0, 'tirePressureLampRR': 0}, 'battery': {'batSoc': 86, 'batState': 0, 'sjbDeliveryMode': 1, 'batSignalReferenceValue': {'batWarning': 65}, 'powerAutoCutMode': 2}, 'remoteIgnition': True, 'seatHeaterVentInfo': {'drvSeatHeatState': 2, 'astSeatHeatState': 2, 'rlSeatHeatState': 2, 'rrSeatHeatState': 2}, 'sunroofOpen': False, 'lampWireStatus': {'headLamp': {'headLampStatus': False, 'leftLowLamp': False, 'rightLowLamp': False, 'leftHighLamp': False, 'rightHighLamp': False, 'leftBifuncLamp': False, 'rightBifuncLamp': False}, 'stopLamp': {'stopLampStatus': False, 'leftLamp': False, 'rightLamp': False}, 'turnSignalLamp': {'turnSignalLampStatus': False, 'leftFrontLamp': False, 'rightFrontLamp': False, 'leftRearLamp': False, 'rightRearLamp': False}}, 'smartKeyBatteryWarning': False, 'washerFluidStatus': False, 'breakOilStatus': False, 'engineRuntime': {}}}}
2023-12-29 18:05:22.844 DEBUG (SyncWorker_1) [hyundai_kia_connect_api.KiaUvoApiCA] hyundai_kia_connect_api - Old Vehicle Last Updated: 2023-12-29 22:31:58+00:00
2023-12-29 18:05:22.844 DEBUG (SyncWorker_1) [hyundai_kia_connect_api.KiaUvoApiCA] hyundai_kia_connect_api - last_updated_at - before 20231229223158
2023-12-29 18:05:22.845 DEBUG (SyncWorker_1) [hyundai_kia_connect_api.KiaUvoApiCA] hyundai_kia_connect_api - last_updated_at - after 2023-12-29 22:31:58+00:00
2023-12-29 18:05:22.845 DEBUG (SyncWorker_1) [hyundai_kia_connect_api.KiaUvoApiCA] hyundai_kia_connect_api - Current Vehicle Last Updated: 2023-12-29 22:31:58+00:00
2023-12-29 18:05:22.847 DEBUG (MainThread) [custom_components.kia_uvo.coordinator] Finished fetching kia_uvo data in 0.870 seconds (success: False)

**Comment by franquosino** [comment]
Resolved! I don't know if it's because of the last update or the fact that I was finally able to connect with BlueLink, but the integration started to work. In either case, thank you for your time and support on this issue. 

This issue can be be marked completed.
