### ISSUE TITLE
KeyError: 'redirectUrl'

### ISSUE THREAD

**Issue by stefanuytterhoeven** [Hyundai-Kia-Connect/kia_uvo#818]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/kia_uvo/blob/master/README.md
**Region and Brand of car**
Europe kia Sportage 
**Version of the integration**
Latest

**Describe the bug**
Suddenly stopped working

**Debug logs if an error occurred**
2024-02-03 20:02:57.171 ERROR (MainThread) [custom_components.kia_uvo.coordinator] Unexpected error fetching kia_uvo data: 'redirectUrl'
Traceback (most recent call last):
File "/usr/local/lib/python3.11/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 240, in login
authorization_code = self._get_authorization_code_with_redirect_url(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 1430, in _get_authorization_code_with_redirect_url
parsed_url = urlparse(response["redirectUrl"])
~~~~~~~~^^^^^^^^^^^^^^^
KeyError: 'redirectUrl'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File

**Comment by fuatakgun** [comment]
Please enable debug logs so we can see where it exactly fails

**Comment by stefanuytterhoeven** [comment]
Had installed it.
When reinstalling,
I can't even login
Deze fout is ontstaan door een aangepaste integratie.

Logger: custom_components.kia_uvo.config_flow
Source: custom_components/kia_uvo/config_flow.py:159
Integration: Hyundai / Kia Connect (documentation, issues)
First occurred: 20:56:01 (1 occurrences)
Last logged: 20:56:01

Unexpected exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 240, in login
    authorization_code = self._get_authorization_code_with_redirect_url(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 1430, in _get_authorization_code_with_redirect_url
    parsed_url = urlparse(response["redirectUrl"])
                          ~~~~~~~~^^^^^^^^^^^^^^^
KeyError: 'redirectUrl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/kia_uvo/config_flow.py", line 159, in async_step_user
    await validate_input(self.hass, user_input)
  File "/config/custom_components/kia_uvo/config_flow.py", line 63, in validate_input
    token: Token = await hass.async_add_executor_job(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 245, in login
    authorization_code = self._get_authorization_code_with_form(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 1528, in _get_authorization_code_with_form
    parsed_url = urlparse(response["redirectUrl"])
                          ~~~~~~~~^^^^^^^^^^^^^^^
KeyError: 'redirectUrl'

**Comment by stefanuytterhoeven** [comment]
Nothing yet?

**Comment by cdnninja** [comment]
Any luck on debug logs?

**Comment by stefanuytterhoeven** [comment]
just found out. Log out of the app. Log in. and then retry the integration.
Hopefully I don't have to do this every time HA restarts...
