### ISSUE TITLE
USA hyundai "Failed setup, will retry" message

### ISSUE THREAD

**Issue by Esprit1st** [Hyundai-Kia-Connect/kia_uvo#837]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/kia_uvo/blob/master/README.md ... CHECK
**Region and Brand of car**
US - Hyundai Ioniq 5 2022
**Version of the integration**
2.21.0

**Describe the bug**
Getting title error message and integration doesn't start. It used to work before. No changes made. (I realize how that sounds)
I just tried a complete delete and re-install of the integration and it shows the same error.

**Debug logs if an error occurred**
```
Logger: aiohttp.server
Source: /usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py:421
First occurred: 15:37:37 (36 occurrences)
Last logged: 16:10:59

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 350, in data_received
    messages, upgraded, tail = self._request_parser.feed_data(data)
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "aiohttp/_http_parser.pyx", line 557, in aiohttp._http_parser.HttpParser.feed_data
aiohttp.http_exceptions.BadStatusLine: 400, message:
  Invalid method encountered:

    b'\x16\x03\x03'
      ^
```

**Comment by BZPJoe** [comment]
I'm curious if your bluelink app works. We are getting notification in our bluelink app that we have used our daily max requests. This is fairly new issue for us as well.

**Comment by Esprit1st** [comment]
Yes, my bluelink works fine. It worked fine for months and suddenly it stopped working.

**Comment by BZPJoe** [comment]
Yes that's what I mean, did you Hyundai app actually stop working today? I think the latest update may be calling a lot more or Hyundai may have put limits on it. I'm just curious as we are experiencing the same thing.

**Comment by cy-bertrand** [comment]
Hi, I had the same issue since the last update yesterday.
I've opened the Kia App and forced the refresh in the app,
Then I've forced a reload of the Integration and now it is working (was not before forcing the refresh in the Kia app)

**Comment by Esprit1st** [comment]
Very strange. @BZPJoe No, the HyundaiApp never stopped working. But for some reason this morning the integration works just fine.

**Comment by stintov** [comment]
I have this issue too

**Comment by Andrewa80** [comment]
I also have the same problem, is there any news?

**Comment by domarseneault** [comment]
Same issue. 

2 cars, both working in the bluelink app. 
I had force updated both and still have the issue. 

Stsrted tonight

**Comment by renatkh** [comment]
I have the "failed setup" issue, but my debug logs show no problems as described in #848. So there may be people with different issues here.

**Comment by TheHuskyCrobats** [comment]
Does anyone knows what this means?

> 2024-04-04 05:57:09.833 DEBUG (SyncWorker_15) [hyundai_kia_connect_api.KiaUvoApiEU] hyundai_kia_connect_api - Get Vehicles Response: {'retCode': 'F', 'resCode': '4017', 'resMsg': 'Invalid request value - Invalid Application Id. - 3596.0859999656677', 'msgId': 'aeb5be48-8ec0-4b8f-ae3b-7ffbee0b2e49'}
2024-04-04 05:57:09.834 ERROR (MainThread) [custom_components.kia_uvo.coordinator] Unexpected error fetching kia_uvo data: Server returned:  '4017' 'Invalid request value - Invalid Application Id. - 3596.0859999656677'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 290, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/kia_uvo/coordinator.py", line 107, in _async_update_data
    await self.async_check_and_refresh_token()
  File "/config/custom_components/kia_uvo/coordinator.py", line 166, in async_check_and_refresh_token
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 125, in check_and_refresh_token
    self.initialize()
  File "/usr/local/lib/python3.11/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 71, in initialize
    vehicles = self.api.get_vehicles(self.token)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 271, in get_vehicles
    _check_response_for_errors(response)
  File "/usr/local/lib/python3.11/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 127, in _check_response_for_errors
    raise APIError(
hyundai_kia_connect_api.exceptions.APIError: Server returned:  '4017' 'Invalid request value - Invalid Application Id. - 3596.0859999656677'
2024-04-04 05:57:09.842 DEBUG (MainThread) [custom_components.kia_uvo.coordinator] Finished fetching kia_uvo data in 2.628 seconds (success: False)

**Comment by TheHuskyCrobats** [comment]
Just a question
Is this integration still maintained or is it abandoned?

I can see that the post before my previous question, it is 3 weeks older ....

**Comment by domarseneault** [comment]
There was a bluelink integration update in hacs in the last week. It's not abanadoned

**Comment by TheHuskyCrobats** [comment]
Yeah ... It seems that I can log in but there is no device or entities... I have no ideea what I can do.
I have restarted the HA, reinstalled the integration, nothing is working.

**Comment by domarseneault** [comment]
Try changing your password in the app and then in home assistant

**Comment by TheHuskyCrobats** [comment]
Already did it, same issue.
I have tried with my wife's account, same error.
I dont understand what is with that PIN that it is asking now at login, but it does not looks mandatory.

**Comment by cdnninja** [comment]
I don't own one of these cars anymore so don't spend much time on this.  Even if I had a car this one is a USA so someone in the states needs to step up to fix it.  Each region is unique.

**Comment by cdnninja** [comment]
> Does anyone knows what this means?
> 
> There has nothing to do with geolocation issue.
> 
> 
> 
> > 2024-04-04 05:57:09.833 DEBUG (SyncWorker_15) [hyundai_kia_connect_api.KiaUvoApiEU] hyundai_kia_connect_api - Get Vehicles Response: {'retCode': 'F', 'resCode': '4017', 'resMsg': 'Invalid request value - Invalid Application Id. - 3596.0859999656677', 'msgId': 'aeb5be48-8ec0-4b8f-ae3b-7ffbee0b2e49'}
> 
> 2024-04-04 05:57:09.834 ERROR (MainThread) [custom_components.kia_uvo.coordinator] Unexpected error fetching kia_uvo data: Server returned:  '4017' 'Invalid request value - Invalid Application Id. - 3596.0859999656677'
> 
> Traceback (most recent call last):
> 
>   File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 290, in _async_refresh
> 
>     self.data = await self._async_update_data()
> 
>                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/config/custom_components/kia_uvo/coordinator.py", line 107, in _async_update_data
> 
>     await self.async_check_and_refresh_token()
> 
>   File "/config/custom_components/kia_uvo/coordinator.py", line 166, in async_check_and_refresh_token
> 
>     await self.hass.async_add_executor_job(
> 
>   File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
> 
>     result = self.fn(*self.args, **self.kwargs)
> 
>              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/local/lib/python3.11/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 125, in check_and_refresh_token
> 
>     self.initialize()
> 
>   File "/usr/local/lib/python3.11/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 71, in initialize
> 
>     vehicles = self.api.get_vehicles(self.token)
> 
>                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> 
>   File "/usr/local/lib/python3.11/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 271, in get_vehicles
> 
>     _check_response_for_errors(response)
> 
>   File "/usr/local/lib/python3.11/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 127, in _check_response_for_errors
> 
>     raise APIError(
> 
> hyundai_kia_connect_api.exceptions.APIError: Server returned:  '4017' 'Invalid request value - Invalid Application Id. - 3596.0859999656677'
> 
> 2024-04-04 05:57:09.842 DEBUG (MainThread) [custom_components.kia_uvo.coordinator] Finished fetching kia_uvo data in 2.628 seconds (success: False)

This is a totally different issue than this thread.  Different region as well.  

Open a new issue please and confirm your version number.   This somewhat implies an old app id.  If that was widespread we would have heard about it.
