### ISSUE TITLE
Change AC-charge-current

### ISSUE THREAD

**Issue by dagobert** [Hyundai-Kia-Connect/kia_uvo#864]
It is possible to change am the AC charge current to 100%, 90% and 60% when sitting in the car using the settings in EV screen on an Ioniq 5 and others with the same platform.

This option would've great to expose to HA to be able to regulate the charge current when loading at home with solar. 

Is it in the API? How to find out?

**Comment by dagobert** [comment]
I am not sure I understand you correctly but there is a way to do what I wrote from the car screen. Just follow the screenshots and you will find it. Sorry the ui is in German.

From ev screen use the burger icon.
![IMG_20240419_162852](https://github.com/Hyundai-Kia-Connect/kia_uvo/assets/140021/d07e78d8-993d-426f-b5d1-1ee075219416)

There you use ev-settings.
![IMG_20240419_162801](https://github.com/Hyundai-Kia-Connect/kia_uvo/assets/140021/9404bf65-92a8-49e9-8999-ca5369f057b5)

Than ac-current
![IMG_20240419_162715](https://github.com/Hyundai-Kia-Connect/kia_uvo/assets/140021/5e48ddde-ac0a-4a93-ac91-fdfd583c0984)

Here you can change the percentage of the max available current of the charging process. This actually means that it uses x percent of what the charger offers at this right moment and not of what it could offer at maximum. Hence, if you setup your simple plugin charger to 8 amps at 230v than it would use this as 100 percent and the lower accordingly. This paragraph has nothing to do with my request but is for you to understand the mechanism of these settings options.
![IMG_20240419_162632](https://github.com/Hyundai-Kia-Connect/kia_uvo/assets/140021/26d557ea-e09e-45dc-88d6-6d4a57f7f90d)

**Comment by Speederer** [comment]
Okay, you are right, I skipped over that setting. Sorry for that.
It looks promising for controlling the charging, but too bad it's not supported remotely.

**Comment by cdnninja** [comment]
I assume that is different than the ac /dc charge setting we offer in this today?

**Comment by dagobert** [comment]
Yes, the difference is, that the charge option sets the maximum charge point to whî the car should be filled, eg. 80% full.

The option I talk about sets the current. It basically the speed the car is charging (in this case related to the amps the charger offers).

**Comment by cdnninja** [comment]
Someone will need to sniff this traffic and add it.

**Comment by cdnninja** [comment]
try updating to master branch.  That was an error in the code.

**Comment by ReconOperator** [comment]
@cdnninja 

Updated to Master and restarted HA. Now i get some different errors. Calling for example Start Climate works fine. 

2024-06-28 10:22:13.278 ERROR (SyncWorker_45) [hyundai_kia_connect_api.KiaUvoApiEU] Failed to parse driving info. Possible reasons:
                                    - incompatible vehicle (ICE)
                                    - new API format
                                    - API outage
                            
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 356, in update_vehicle_with_cached_state
    state = self._get_driving_info(token, vehicle)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 1205, in _get_driving_info
    _check_response_for_errors(response30d)
  File "/usr/local/lib/python3.12/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 128, in _check_response_for_errors
    raise error_code_mapping[response["resCode"]](response["resMsg"])
hyundai_kia_connect_api.exceptions.DeviceIDError: Invalid request body - Invalid deviceId. 

2024-06-28 10:22:37.922 ERROR (MainThread) [homeassistant.helpers.script.websocket_api_script] websocket_api script: Error executing script. Unexpected error for call_service at pos 1: Invalid request body - Invalid deviceId. 
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 526, in _async_step
    await getattr(self, handler)()
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 763, in _async_call_service_step
    response_data = await self._async_run_long_action(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/script.py", line 726, in _async_run_long_action
    return await long_task
           ^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2741, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2784, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/kia_uvo/services.py", line 148, in async_handle_set_charging_current
    await coordinator.set_charging_current(vehicle_id, int(current_level))
  File "/config/custom_components/kia_uvo/coordinator.py", line 267, in set_charging_current
    action_id = await self.hass.async_add_executor_job(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 169, in set_charging_current
    return self.api.set_charging_current(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 1302, in set_charging_current
    _check_response_for_errors(response)
  File "/usr/local/lib/python3.12/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 128, in _check_response_for_errors
    raise error_code_mapping[response["resCode"]](response["resMsg"])
hyundai_kia_connect_api.exceptions.DeviceIDError: Invalid request body - Invalid deviceId.

**Comment by cdnninja** [comment]
This may be two errors.  Is it still occurring for you?

**Comment by ReconOperator** [comment]
@cdnninja Hi, yes I still get the same error

**Comment by SeatFX** [comment]
Also getting the same Error on a 2021 Kia E-Niro in the EU. Invalid Device ID whenever trying to set the charging current. Any updates on this?

**Comment by mastameista** [comment]
I also get 2 Errors in HA Log file. But changing AC-charge-current on my EV9 works! 
BUT: After calling the service the integration crashes entirely. I need to reload the integration in order to make entities available again. 

Error 1:
```
Logger: custom_components.kia_uvo.coordinator
Source: helpers/update_coordinator.py:386
integration: Hyundai / Kia Connect ([documentation](https://github.com/Hyundai-Kia-Connect/kia_uvo), [issues](https://github.com/Hyundai-Kia-Connect/kia_uvo/issues))
First occurred: 4:22:57 PM (2 occurrences)
Last logged: 4:25:11 PM

Error fetching kia_uvo data: Error communicating with API: Traceback (most recent call last): File "/config/custom_components/kia_uvo/coordinator.py", line 126, in _async_update_data await self.hass.async_add_executor_job( File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run result = self.fn(*self.args, **self.kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 113, in check_and_force_update_vehicles self.update_vehicle_with_cached_state(vehicle_id) File "/usr/local/lib/python3.12/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 90, in update_vehicle_with_cached_state self.api.update_vehicle_with_cached_state(self.token, vehicle) File "/usr/local/lib/python3.12/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 341, in update_vehicle_with_cached_state _check_response_for_errors(response) File "/usr/local/lib/python3.12/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 128, in _check_response_for_errors raise error_code_mapping[response["resCode"]](response["resMsg"]) hyundai_kia_connect_api.exceptions.DeviceIDError: Invalid request body - Invalid deviceId. During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/config/custom_components/kia_uvo/coordinator.py", line 135, in _async_update_data await self.hass.async_add_executor_job( File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run result = self.fn(*self.args, **self.kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 85, in update_all_vehicles_with_cached_state self.update_vehicle_with_cached_state(vehicle_id) File "/usr/local/lib/python3.12/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 90, in update_vehicle_with_cached_state self.api.update_vehicle_with_cached_state(self.token, vehicle) File "/usr/local/lib/python3.12/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 341, in update_vehicle_with_cached_state _check_response_for_errors(response) File "/usr/local/lib/python3.12/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 128, in _check_response_for_errors raise error_code_mapping[response["resCode"]](response["resMsg"]) hyundai_kia_connect_api.exceptions.DeviceIDError: Invalid request body - Invalid deviceId.
```

Error 2:
```
Logger: homeassistant
Source: custom_components/kia_uvo/coordinator.py:175
integration: Hyundai / Kia Connect ([documentation](https://github.com/Hyundai-Kia-Connect/kia_uvo), [issues](https://github.com/Hyundai-Kia-Connect/kia_uvo/issues))
First occurred: 4:22:57 PM (2 occurrences)
Last logged: 4:25:11 PM

Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/config/custom_components/kia_uvo/coordinator.py", line 175, in async_await_action_and_refresh
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 206, in check_action_status
    return self.api.check_action_status(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 1687, in check_action_status
    state = self.check_action_status(
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 1709, in check_action_status
    _check_response_for_errors(response)
  File "/usr/local/lib/python3.12/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 128, in _check_response_for_errors
    raise error_code_mapping[response["resCode"]](response["resMsg"])
hyundai_kia_connect_api.exceptions.DeviceIDError: Invalid request body - Invalid deviceId.
```

**Comment by eekhoorn** [comment]
Also getting the same Error on a 2023 Kia E-Niro in the EU. Invalid Device ID whenever trying to set the charging current. Any updates on this?

**Comment by zulufoxtrot** [comment]
2020 e-niro here.

I did some trial and error with the library, and couldn't get it to work.

I also noticed that while it is possible to set max current from the infotainment, there is no option in Kia Connect for my car.

This feature appears to be reserved to "CCS2" vehicles: most likely EV6 or newer.

I think the "invalid device ID" is the API telling us this feature is not supported for older cars.
