### ISSUE TITLE
KIA EV9 start charging not working

### ISSUE THREAD

**Issue by mastameista** [Hyundai-Kia-Connect/kia_uvo#878]
**Region and Brand of car**
EU (Switzerland), KIA EV9

**Version of the integration**
2.24.2

**Describe the bug**
Start Charging does not work. Stop charging works. 
I've read the readme and I am aware of the info, that "start stop charge" for EU(<2023) is not supported. But as "stop charge" works and because of this post: https://github.com/Hyundai-Kia-Connect/kia_uvo/issues/872#issuecomment-2091245486
I allow myself to open an issue to ask if it should work in the meantime and if yes, if you could make it work for EV9. 

**Debug logs if an error occurred**
No error in log file of HA. After calling the service in HA DevTools, it just says "done" (green, success). 

**To Reproduce**
Call the start charge service in HA DevTools:
![image](https://github.com/Hyundai-Kia-Connect/kia_uvo/assets/59114249/a3c009d7-db40-4796-acb0-1c8795145369)

Other EV9 users from Germany and Austria have the same issue. 

**Expected behavior**
EV9 starts charging

**Comment by cdnninja** [comment]
I just bumped the API in the manifest file. Could you try update to the "master" branch and let me know if it fixes it?

**Comment by mastameista** [comment]
@cdnninja thx a lot! very appreciated! With your change, the integration could not load. Thanks to @pypi, who changed
 ` "requirements": ["hyundai_kia_connect_api==3.20.2"]`
the integration works again. 

I will test asap, if start charge works. Unfortunately, I am on a business trip this week. So it will take some time.

**Comment by mastameista** [comment]
@cdnninja I tested today but got already stuck with start charging remote command in KIA Connect App. Did only work once in all my tests, so I did not move over to HA yet. 
Will keep you posted once I know more

**Comment by larser** [comment]
I have the same issue, also with Kia EV9 EU (Sweden).
Version 2.26.1 

Below shows up in the log, both with working and non working commands, so maybe not related?

Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/config/custom_components/kia_uvo/coordinator.py", line 174, in async_await_action_and_refresh
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 206, in check_action_status
    return self.api.check_action_status(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 1687, in check_action_status
    state = self.check_action_status(
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 1727, in check_action_status
    raise APIError(f"No action found with ID {action_id}")
hyundai_kia_connect_api.exceptions.APIError: No action found with ID

**Comment by mastameista** [comment]
Think so. As long as it does not work with the mobile app, I strongly assume it's not an issue of this integration.

**Comment by larser** [comment]
Now I'm confused, you can't start charging from Kia connect app? I can (Android device)

**Comment by mastameista** [comment]
correct, also on android. I use juice booster v2 and EM2GO Mobile Charger. Doesn't work with both. The issue has been discussed in EV9 Forum. 

https://www.ev9-forum.de/forum/thread/250-abfahrtszeit-ladestand-einstellen/?postID=3832#post3832 
and here
https://www.ev9-forum.de/forum/thread/137-home-assistant/?postID=3170#post3170

I will get an ABB Terra AC Wallbox in September. Then I know, if it's related to specific wallboxes / mobile chargers.

**Comment by mastameista** [comment]
Update #1: I now have my ABB Terra AC Wallbox and start / stop charging from Kia Connect App works. I've also tested start charging from Home Assistant and it didn't work. My EV9 and the wallbox got in a very strange state after calling the serivce. The wallbox showed the loading / initializing screen and on the car side the charging plug was in locked state. I could not unlock the cable anymore and had to try several different things like power on/off the car and then running to the charging plug to pull out the cable. 
I will further test this and update here. 

Error in HA:

This error originated from a custom integration.

```
Logger: homeassistant
Source: custom_components/kia_uvo/coordinator.py:175
integration: Hyundai / Kia Connect (documentation, issues)
First occurred: September 20, 2024 at 6:30:37 PM (5 occurrences)
Last logged: September 20, 2024 at 7:31:05 PM

Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/config/custom_components/kia_uvo/coordinator.py", line 175, in async_await_action_and_refresh
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 206, in check_action_status
    return self.api.check_action_status(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 1687, in check_action_status
    state = self.check_action_status(
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 1727, in check_action_status
    raise APIError(f"No action found with ID {action_id}")
hyundai_kia_connect_api.exceptions.APIError: No action found with ID aa1cf5e0-776d-11ef-9a43-37f940a8e012
```

**Comment by timvh-dev** [comment]
Yes, i am still having this issue with locking/unlocking my doors for a sorento (2024 Netherlands) same error APIError: no action found with id abc

**Comment by cdnninja** [comment]
This is for charging.  

That no action error is it checking after the action was issued. Did you confirm that lock command actually functioned correctly just gave an error?

**Comment by timvh-dev** [comment]
yeah actually, it's the same as this thread, Controls don’t work #972
so the door can unlock and lock going to the development tools (just checked), but do not work with the sliding control button when you would go into the integration and do something with the control options.

But yeah either way, this is not about charging, so never mind.

**Comment by cdnninja** [comment]
@timvh-dev  That one is EU.   Not sure if we have one for EU.   Could you search, if not open one? I have a theory on how to fix that but would need someone to test it.

**Comment by mastameista** [comment]
I still experience this issue

**Comment by cdnninja** [comment]
A bunch of changes have been done in the library.  Could you retest with latest?

**Comment by mastameista** [comment]
@cdnninja just tested and was able to stop / start twice. -> seems to work now. 
(thx a lot, it's great how much you are fixing!)

In Logfile, I get this warning, also when changing ac charging current:

This error originated from a custom integration.

Logger: py.warnings
Source: custom_components/kia_uvo/coordinator.py:176
integration: Hyundai / Kia Connect (documentation, issues)
First occurred: 1:37:55 AM (2 occurrences)
Last logged: 1:39:14 AM

/config/custom_components/kia_uvo/coordinator.py:176: RuntimeWarning: coroutine 'sleep' was never awaited asyncio.sleep(30)

**Comment by cdnninja** [comment]
That should be fixed in next release.  Thanks for reporting it.
