### ISSUE TITLE
Hyundai USA:  Config Not Ready: Error communicating with API: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by henrybauer** [Hyundai-Kia-Connect/kia_uvo#880]
**Region and Brand of car**
Hyundai USA Ioniq 6

**Version of the integration**
2.24.2

**Describe the bug**
Integration won't start, saying: "Config Not Ready: Error communicating with API: Expecting value: line 1 column 1 (char 0)"

![hyundai](https://github.com/Hyundai-Kia-Connect/kia_uvo/assets/5103358/6e65033f-e847-4fce-9c93-6ac4c78f9840)

**Debug logs if an error occurred**

> Logger: hyundai_kia_connect_api.HyundaiBlueLinkAPIUSA
> Source: /usr/local/lib/python3.12/site-packages/hyundai_kia_connect_api/HyundaiBlueLinkAPIUSA.py:224
> First occurred: 6:04:11 PM (1 occurrences)
> Last logged: 6:04:11 PM
> 
> hyundai_kia_connect_api - Unable to get vehicle location: {'errorSubCode': 'GEN', 'systemName': 'HATA', 'functionName': 'findMyCar', 'errorSubMessage': 'HATA findMyCar service failed while performing the operation FindMyCar', 'errorMessage': "We're sorry, but we could not complete your request. Please try again later.", 'errorCode': 502, 'serviceName': 'FindMyCar'}

**Comment by shacklockj** [comment]
I have been having this same issue with the integration since late April. It will sometime reload fine and will work for a couple of hours before reporting that the setup fails.
It will be good to get to the bottom of what is causing this as my configuration has not changed since I added the integration over 8 months ago.

**Comment by jsuanet** [comment]
Also after upgrade to version v2024.2.4 this error still exists.

**Comment by florianoverkamp** [comment]
Looks similar to what's happening here. Ioniq 5 in Europe. Running integration v2.24.4 on core 2024.5.4.

I can actually restart the integration but as soon as it tries to update, it will fail again. I'm guessing Hyundai is returning something we're not expecting.
 
Debug log: 
2024-05-22 16:49:38.967 DEBUG (SyncWorker_8) [hyundai_kia_connect_api.KiaUvoApiEU] KiaUvoApiEU: after  daily_stats: [DailyDrivingStats(date=datetime.datetime(2024, 5, 22, 0, 0), total_consumed=42428, engine_consumption=39918, climate_consumption=710, onboard_electronics_consumption=1800, battery_care_consumption=0, regenerated_energy=11547, distance=290), DailyDrivingStats(date=datetime.datetime(2024, 5, 18, 0, 0), total_consumed=1003, engine_consumption=719, climate_consumption=114, onboard_electronics_consumption=170, battery_care_consumption=0, regenerated_energy=754, distance=8), DailyDrivingStats(date=datetime.datetime(2024, 5, 17, 0, 0), total_consumed=4036, engine_consumption=3395, climate_consumption=241, onboard_electronics_consumption=400, battery_care_consumption=0, regenerated_energy=2090, distance=29), DailyDrivingStats(date=datetime.datetime(2024, 5, 16, 0, 0), total_consumed=1923, engine_consumption=1239, climate_consumption=334, onboard_electronics_consumption=350, battery_care_consumption=0, regenerated_energy=1278, distance=13), DailyDrivingStats(date=datetime.datetime(2024, 5, 12, 0, 0), total_consumed=18376, engine_consumption=17659, climate_consumption=157, onboard_electronics_consumption=560, battery_care_consumption=0, regenerated_energy=2873, distance=110), DailyDrivingStats(date=datetime.datetime(2024, 5, 11, 0, 0), total_consumed=39279, engine_consumption=37824, climate_consumption=355, onboard_electronics_consumption=1100, battery_care_consumption=0, regenerated_energy=4759, distance=258), DailyDrivingStats(date=datetime.datetime(2024, 5, 8, 0, 0), total_consumed=1882, engine_consumption=1333, climate_consumption=219, onboard_electronics_consumption=330, battery_care_consumption=0, regenerated_energy=1095, distance=13), DailyDrivingStats(date=datetime.datetime(2024, 5, 7, 0, 0), total_consumed=1132, engine_consumption=879, climate_consumption=63, onboard_electronics_consumption=190, battery_care_consumption=0, regenerated_energy=932, distance=9), DailyDrivingStats(date=datetime.datetime(2024, 5, 6, 0, 0), total_consumed=2112, engine_consumption=1211, climate_consumption=361, onboard_electronics_consumption=540, battery_care_consumption=0, regenerated_energy=799, distance=11), DailyDrivingStats(date=datetime.datetime(2024, 5, 4, 0, 0), total_consumed=4532, engine_consumption=4081, climate_consumption=151, onboard_electronics_consumption=300, battery_care_consumption=0, regenerated_energy=1851, distance=31), DailyDrivingStats(date=datetime.datetime(2024, 5, 3, 0, 0), total_consumed=863, engine_consumption=462, climate_consumption=221, onboard_electronics_consumption=180, battery_care_consumption=0, regenerated_energy=516, distance=4), DailyDrivingStats(date=datetime.datetime(2024, 5, 2, 0, 0), total_consumed=3403, engine_consumption=2700, climate_consumption=203, onboard_electronics_consumption=500, battery_care_consumption=0, regenerated_energy=2765, distance=28), DailyDrivingStats(date=datetime.datetime(2024, 5, 1, 0, 0), total_consumed=3819, engine_consumption=3358, climate_consumption=131, onboard_electronics_consumption=330, battery_care_consumption=0, regenerated_energy=2160, distance=30), DailyDrivingStats(date=datetime.datetime(2024, 4, 30, 0, 0), total_consumed=3589, engine_consumption=3128, climate_consumption=1, onboard_electronics_consumption=460, battery_care_consumption=0, regenerated_energy=2274, distance=24), DailyDrivingStats(date=datetime.datetime(2024, 4, 29, 0, 0), total_consumed=8186, engine_consumption=7216, climate_consumption=0, onboard_electronics_consumption=970, battery_care_consumption=0, regenerated_energy=5357, distance=47), DailyDrivingStats(date=datetime.datetime(2024, 4, 27, 0, 0), total_consumed=30, engine_consumption=0, climate_consumption=0, onboard_electronics_consumption=30, battery_care_consumption=0, regenerated_energy=0, distance=0)]
2024-05-22 16:49:41.459 ERROR (MainThread) [custom_components.kia_uvo.coordinator] Error fetching kia_uvo data: Error communicating with API: Expecting value: line 1 column 1 (char 0)
2024-05-22 16:49:41.459 DEBUG (MainThread) [custom_components.kia_uvo.coordinator] Finished fetching kia_uvo data in 3.648 seconds (success: False)

**Comment by adman234** [comment]
I am also having the same issue with a 2019 ioniq EV. I hope it can be fixed! Thanks

**Comment by andregreven** [comment]
Same here, Europe, Hyunday KONA. Works every now and then. Geocoded location off for a few kilometers

**Comment by ianwood** [comment]
Same. After reboot. Integration failed. Dropped integration and re-added it and works again. 

USA. Kia EV6.

**Comment by thkrmr** [comment]
Same error, essentially seeing in debug logs 

`hyundai_kia_connect_api - Sign In Response: {'errId': 'a7925234-3e3b-4d25-a1e1-87e1e22959dc', 'errCode': '4003', 'errMsg': 'Invalid values'}
2024-06-07 23:32:46.426 DEBUG (SyncWorker_15) [hyundai_kia_connect_api.KiaUvoApiEU] hyundai_kia_connect_api - get_authorization_code_with_redirect_url failed`

**Comment by slusaro2** [comment]
Same error Kona Europe

**Comment by raczgy** [comment]
Same error, Kia EV6 & Ceed It is strange that the integration sometimes works and sometimes not:(

**Comment by jamesbmarshall** [comment]
I am experiencing this issue. If I manually reload the integration it will work for a short period before failing again.

**Comment by robyholmes** [comment]
Has anyone found the best way of avoiding this issue? I have automatic updates turned off and I just trigger a manual force update when plugging the car in, and at the start and end of charging. However it can still fail randomly requiring me to manually restart the integration multiple times to try and get it back working.

It seems to fall over at least once every 3 force updates.

**Comment by rmunroe** [comment]
Same here. USA, 2020 Kia Telluride

**Comment by arimers** [comment]
For me, this error was shown in the integration status after enabling the "Enable Geolocation Entity using OpenStreetMap" option. The logs indicated: `hyundai_kia_connect_api - get vehicle location rate limit exceeded.`
It's possible there are multiple causes of this error, but after I disabled that option the integration works again.

**Comment by matthewcky2k** [comment]
For me disabling geocode location fixes this problem.

**Comment by robyholmes** [comment]
Yes thank you @arimers for spotting this. Can't believe I missed that in the logs.

Disabled Geocode, restarted the integration and other than failing once, so far it's worked perfectly. Not sure if a HA restart also helped it after I disabled the maps option or not.

**Comment by cdnninja** [comment]
I added some debug logs.  Could someone update to the "master" version via service call. Enable debug logs and then when this occurs look for  the two debug log statements I added: 

https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/commit/867b24540916d237ac6b8b1de230fa75df35311c


I want to know if 

1. the first one is a valid URL. Copying a pasting it into a browser should work.  In theory it has lat long in it.  
2. The second debug statement if it contains display_name and address.

**Comment by jsuanet** [comment]
Hi I updated to the master version, but I don't see the extra debugging information. The changes you made were in the api integration, but in the Kia_uvo integration there are no changes made. I would also expect an update in the manifest file of this integration?

This is the logging I get.

This error originated from a custom integration.

Logger: custom_components.kia_uvo.coordinator
Source: helpers/update_coordinator.py:344
integration: Kia Uvo / Hyundai Bluelink (documentation, issues)
First occurred: 13:16:06 (1 occurrences)
Last logged: 13:16:06

Error fetching kia_uvo data: Error communicating with API: Traceback (most recent call last): File "/usr/local/lib/python3.12/site-packages/requests/models.py", line 974, in json return complexjson.loads(self.text, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/simplejson/__init__.py", line 514, in loads return _default_decoder.decode(s) ^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/simplejson/decoder.py", line 386, in decode obj, end = self.raw_decode(s) ^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/simplejson/decoder.py", line 416, in raw_decode return self.scan_once(s, idx=_w(s, idx).end()) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0) During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/config/custom_components/kia_uvo/coordinator.py", line 126, in _async_update_data await self.hass.async_add_executor_job( File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run result = self.fn(*self.args, **self.kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 113, in check_and_force_update_vehicles self.update_vehicle_with_cached_state(vehicle_id) File "/usr/local/lib/python3.12/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 92, in update_vehicle_with_cached_state self.api.update_geocoded_location( File "/usr/local/lib/python3.12/site-packages/hyundai_kia_connect_api/ApiImpl.py", line 115, in update_geocoded_location response = response.json() ^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/requests/models.py", line 978, in json raise RequestsJSONDecodeError(e.msg, e.doc, e.pos) requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0) During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/config/custom_components/kia_uvo/coordinator.py", line 132, in _async_update_data await self.hass.async_add_executor_job( File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run result = self.fn(*self.args, **self.kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 85, in update_all_vehicles_with_cached_state self.update_vehicle_with_cached_state(vehicle_id) File "/usr/local/lib/python3.12/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 92, in update_vehicle_with_cached_state self.api.update_geocoded_location( File "/usr/local/lib/python3.12/site-packages/hyundai_kia_connect_api/ApiImpl.py", line 115, in update_geocoded_location response = response.json() ^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/requests/models.py", line 978, in json raise RequestsJSONDecodeError(e.msg, e.doc, e.pos) requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by cdnninja** [comment]
Make sure to view logs not just errors.

**Comment by Schrolli91** [comment]
> For me disabling geocode location fixes this problem.

Thats true for me too - disabling the geocoding, will fix the data loss

**Comment by cdnninja** [comment]
I put a potential fix in for this.

**Comment by andregreven** [comment]
Forgot to mention earlier: my connection (Hyundai - EU) is working flawlessly again last couple of weeks. Geolocation active.
