### ISSUE TITLE
登陆未知错误

### ISSUE THREAD

**Issue by suhanfeng** [Hyundai-Kia-Connect/kia_uvo#892]
此错误来自自定义集成。

日志记录器: custom_components.kia_uvo.config_flow
来源: custom_components/kia_uvo/config_flow.py:159
集成: Hyundai / Kia Connect (文档, 问题)
首次出现: 22:23:34 (2 次总计出现)
上次记录: 23:01:42

Unexpected exception
Traceback (most recent call last):
  File "/config/custom_components/kia_uvo/config_flow.py", line 159, in async_step_user
    await validate_input(self.hass, user_input)
  File "/config/custom_components/kia_uvo/config_flow.py", line 63, in validate_input
    token: Token = await hass.async_add_executor_job(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/hyundai_kia_connect_api/KiaUvoApiCN.py", line 158, in login
    device_id = self._get_device_id()
                ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/hyundai_kia_connect_api/KiaUvoApiCN.py", line 1012, in _get_device_id
    _check_response_for_errors(response)
  File "/usr/local/lib/python3.12/site-packages/hyundai_kia_connect_api/KiaUvoApiCN.py", line 103, in _check_response_for_errors
    raise APIError(f"Server returned: '{response['resMsg']}'")
hyundai_kia_connect_api.exceptions.APIError: Server returned: 'Invalid request body - Invalid parameter.'

**Comment by suhanfeng** [comment]
我是中国地区的，无法登陆，有小伙伴研究一下

**Comment by woshixuantao** [comment]
> 我是中国地区的，无法登陆，有小伙伴研究一下

国内的确实登录不了 换了地址 抓不了包
