### ISSUE TITLE
Server returned: '4007' 'Remote control unavailable

### ISSUE THREAD

**Issue by ridderr** [Hyundai-Kia-Connect/kia_uvo#894]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/kia_uvo/blob/master/README.md
**Region and Brand of car**
EU -  Kia Sportage 2023

**Version of the integration**
V.2.24.5

**Describe the bug**
See strange error message in logfile. Why should server return a 4007 error when Remote Control is on low battery? 

**Debug logs if an error occurred**

Logger: custom_components.kia_uvo.coordinator
Bron: custom_components/kia_uvo/coordinator.py:126
integratie: Hyundai / Kia Connect (documentatie, problemen)
Eerst voorgekomen: 16 juni 2024 om 18:20:15 (34 gebeurtenissen)
Laatst gelogd: 15:50:55

Force update failed, falling back to cached: Server returned: '4007' 'Remote control unavailable(low battery) - Remote control unavailable(low battery)'
Traceback (most recent call last):
  File "/config/custom_components/kia_uvo/coordinator.py", line 126, in _async_update_data
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 111, in check_and_force_update_vehicles
    self.force_refresh_vehicle_state(vehicle_id)
  File "/usr/local/lib/python3.12/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 124, in force_refresh_vehicle_state
    self.api.force_refresh_vehicle_state(self.token, vehicle)
  File "/usr/local/lib/python3.12/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 373, in force_refresh_vehicle_state
    state = self._get_forced_vehicle_state(token, vehicle)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 894, in _get_forced_vehicle_state
    _check_response_for_errors(response)
  File "/usr/local/lib/python3.12/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 129, in _check_response_for_errors
    raise APIError(
hyundai_kia_connect_api.exceptions.APIError: Server returned:  '4007' 'Remote control unavailable(low battery) - Remote control unavailable(low battery)'

**Comment by cdnninja** [comment]
What would you like to see?   The cars battery is low and the servers sent an error in reply.

**Comment by ridderr** [comment]
Thanks, yes indeed. I noticed when I wanted to enter the (dead) car.
Would it be possibe to have an entity for this with status OK, NEEDS ATTENTION,
