### ISSUE TITLE
v2.25.0 breaks

### ISSUE THREAD

**Issue by hmmbob** [Hyundai-Kia-Connect/kia_uvo#897]
**Region and Brand of car**
EU, Hyundai

**Version of the integration**
2.25.0

**Describe the bug**
Component won't start on version 2.25.0. Rollback to 2.24.6 works fine.

**Debug logs if an error occurred**
2024-06-26 11:28:36.628 ERROR (ImportExecutor_0) [homeassistant.loader] Unexpected exception importing platform custom_components.kia_uvo.sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/loader.py", line 1249, in _load_platform
cache[full_name] = self._import_platform(platform_name)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/loader.py", line 1281, in _import_platform
return importlib.import_module(f"{self.pkg_path}.{platform_name}")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/util/loop.py", line 131, in protected_loop_func
return func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 995, in exec_module
File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
File "/config/custom_components/kia_uvo/sensor.py", line 248, in <module>
value_fn=charging_current_mapper,
^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'charging_current_mapper' is not defined
2024-06-26 11:28:36.705 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to import_module inside the event loop by custom integration 'kia_uvo' at custom_components/kia_uvo/__init__.py, line 59: await hass.config_entries.async_forward_entry_setups(config_entry, PLATFORMS) (offender: /usr/src/homeassistant/homeassistant/loader.py, line 1281: return importlib.import_module(f"{self.pkg_path}.{platform_name}")), please create a bug report at https://github.com/Hyundai-Kia-Connect/kia_uvo/issues
Traceback (most recent call last):
File "<frozen runpy>", line 198, in _run_module_as_main
File "<frozen runpy>", line 88, in _run_code
File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module>
sys.exit(main())
File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main
exit_code = runner.run(runtime_conf)
File "/usr/src/homeassistant/homeassistant/runner.py", line 190, in run
return loop.run_until_complete(setup_and_run_hass(runtime_config))
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 672, in run_until_complete
self.run_forever()
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 639, in run_forever
self._run_once()
File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1988, in _run_once
handle._run()
File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run
self._context.run(self._callback, *self._args)
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 742, in async_setup_locked
await self.async_setup(hass, integration=integration)
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
result = await component.async_setup_entry(hass, self)
File "/config/custom_components/kia_uvo/__init__.py", line 59, in async_setup_entry
await hass.config_entries.async_forward_entry_setups(config_entry, PLATFORMS)
2024-06-26 11:28:36.713 ERROR (MainThread) [homeassistant.loader] Unexpected exception importing platform custom_components.kia_uvo.sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/loader.py", line 1249, in _load_platform
cache[full_name] = self._import_platform(platform_name)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/loader.py", line 1281, in _import_platform
return importlib.import_module(f"{self.pkg_path}.{platform_name}")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/util/loop.py", line 131, in protected_loop_func
return func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 995, in exec_module
File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
File "/config/custom_components/kia_uvo/sensor.py", line 248, in <module>
value_fn=charging_current_mapper,
^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'charging_current_mapper' is not defined
2024-06-26 11:28:36.744 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Hyundai Europe boblelieveld@gmail.com for kia_uvo
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/loader.py", line 1249, in _load_platform
cache[full_name] = self._import_platform(platform_name)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/loader.py", line 1281, in _import_platform
return importlib.import_module(f"{self.pkg_path}.{platform_name}")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/util/loop.py", line 131, in protected_loop_func
return func(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 995, in exec_module
File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
File "/config/custom_components/kia_uvo/sensor.py", line 248, in <module>
value_fn=charging_current_mapper,
^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'charging_current_mapper' is not defined
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
result = await component.async_setup_entry(hass, self)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/kia_uvo/__init__.py", line 59, in async_setup_entry
await hass.config_entries.async_forward_entry_setups(config_entry, PLATFORMS)
File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2031, in async_forward_entry_setups
await integration.async_get_platforms(platforms)
File "/usr/src/homeassistant/homeassistant/loader.py", line 1162, in async_get_platforms
import_future.result()
File "/usr/src/homeassistant/homeassistant/loader.py", line 1162, in async_get_platforms
import_future.result()
File "/usr/src/homeassistant/homeassistant/loader.py", line 1162, in async_get_platforms
import_future.result()
[Previous line repeated 2 more times]
File "/usr/src/homeassistant/homeassistant/loader.py", line 1150, in async_get_platforms
platforms.update(self._load_platforms(platform_names))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/loader.py", line 1075, in _load_platforms
platform_name: self._load_platform(platform_name)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/loader.py", line 1269, in _load_platform
raise ImportError(
ImportError: Exception importing custom_components.kia_uvo.sensor

**Comment by matt05d** [comment]
Yes, same issue here
No issue if I download to 2.24.6
Logs when trying to load up 2.25.0:

Logger: homeassistant.loader
Source: loader.py:1249
First occurred: 10:24:02 (6 occurrences)
Last logged: 10:44:42

Unexpected exception importing platform custom_components.kia_uvo.sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1249, in _load_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1281, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 131, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/kia_uvo/sensor.py", line 248, in <module>
    value_fn=charging_current_mapper,
             ^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'charging_current_mapper' is not defined

Logger: homeassistant.config_entries
Source: config_entries.py:594
First occurred: 10:24:02 (3 occurrences)
Last logged: 10:44:42

Error setting up entry Kia Europe myemailaddress@gmail.com for kia_uvo
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1249, in _load_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1281, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 131, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/kia_uvo/sensor.py", line 248, in <module>
    value_fn=charging_current_mapper,
             ^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'charging_current_mapper' is not defined

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/kia_uvo/__init__.py", line 59, in async_setup_entry
    await hass.config_entries.async_forward_entry_setups(config_entry, PLATFORMS)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2031, in async_forward_entry_setups
    await integration.async_get_platforms(platforms)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1162, in async_get_platforms
    import_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1162, in async_get_platforms
    import_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1162, in async_get_platforms
    import_future.result()
  [Previous line repeated 2 more times]
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1150, in async_get_platforms
    platforms.update(self._load_platforms(platform_names))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1075, in _load_platforms
    platform_name: self._load_platform(platform_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1269, in _load_platform
    raise ImportError(
ImportError: Exception importing custom_components.kia_uvo.sensor

**Comment by robyholmes** [comment]
Same here:
Logger: homeassistant.loader
Source: loader.py:1249
First occurred: 12:50:41 (4 occurrences)
Last logged: 13:02:29

Unexpected exception importing platform custom_components.kia_uvo.sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1249, in _load_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1281, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 131, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/kia_uvo/sensor.py", line 248, in <module>
    value_fn=charging_current_mapper,
             ^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'charging_current_mapper' is not defined

**Comment by PSXDupe** [comment]
Same issue here, thought it was my setup at first, but

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1249, in _load_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1281, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 131, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/kia_uvo/sensor.py", line 248, in <module>
    value_fn=charging_current_mapper,
             ^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'charging_current_mapper' is not defined
2024-06-26 14:05:02.585 WARNING (MainThread) [homeassistant.util.loop] Detected blocking call to import_module inside the event loop by custom integration 'kia_uvo' at custom_components/kia_uvo/__init__.py, line 59: await hass.config_entries.async_forward_entry_setups(config_entry, PLATFORMS) (offender: /usr/src/homeassistant/homeassistant/loader.py, line 1281: return importlib.import_module(f"{self.pkg_path}.{platform_name}")), please create a bug report at https://github.com/Hyundai-Kia-Connect/kia_uvo/issues

**Comment by jrnk** [comment]
Yes, sorry about this, function moving broke it, I can do this tonight!

**Comment by Dolphin1220** [comment]
How long will it take until there is an update that works again?
How can i roll back to an previous version if necessary? I don't know how to do this.

**Comment by PSXDupe** [comment]
> How long will it take until there is an update that works again? How can i roll back to an previous version if necessary? I don't know how to do this.

Download 2.24.6 from the release list and put that in your components folder.

**Comment by DJBenson** [comment]
> How long will it take until there is an update that works again? How can i roll back to an previous version if necessary? I don't know how to do this.

Go to HACS, find the repository (search for Kia) then in the top right hand corner, click the three dots and select "Redownload" and change the version to 2.24.6 then restart HA.

<img width="1469" alt="image" src="https://github.com/Hyundai-Kia-Connect/kia_uvo/assets/1013909/ce968f1d-a9e8-4e77-a4f5-001425ca6102">

<img width="609" alt="image" src="https://github.com/Hyundai-Kia-Connect/kia_uvo/assets/1013909/3361515f-378c-4047-a39e-dc9610fa0ef7">

**Comment by jrnk** [comment]
Fix should be in https://github.com/Hyundai-Kia-Connect/kia_uvo/pull/898 , entity sensor is working correctly now:
<img width="318" alt="Screenshot 2024-06-26 at 21 00 06" src="https://github.com/Hyundai-Kia-Connect/kia_uvo/assets/5436814/138dd429-4410-4cff-a5c6-62b06578a9c0">

**Comment by Dolphin1220** [comment]
Many Thanks, worked like a charm, everything is back not normal.

![grafik](https://github.com/Hyundai-Kia-Connect/kia_uvo/assets/123817278/5a0225aa-e5af-404b-879e-451436f633cb)

**Comment by PSXDupe** [comment]
> Many Thanks, worked like a charm, everything is back not normal.
> 
> ![grafik](https://private-user-images.githubusercontent.com/123817278/343311406-5a0225aa-e5af-404b-879e-451436f633cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0MzUwMDUsIm5iZiI6MTcxOTQzNDcwNSwicGF0aCI6Ii8xMjM4MTcyNzgvMzQzMzExNDA2LTVhMDIyNWFhLWU1YWYtNDA0Yi04NzllLTQ1MTQzNmY2MzNjYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyNlQyMDQ1MDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zZDZhNDA2ZTQ3NjczZjhhYTY4NjZmN2M2MmU5MDdjMDNkYjk5ODJmZWUxMTNiNWY4MmRhMGVmMzBlNWEzMTlmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VGDvm3-ZPEuwxu3Pnzt1yO3nZIAqB-b7RVzcw-yNUJ0)

Do you have access to the new Charging Current Limit?

**Comment by cdnninja** [comment]
Retry on the latest.  The changing current limit is a service call and only for EU.

**Comment by Dolphin1220** [comment]
@PSXDupe Yes, i have, i am from Austria (EU)

![grafik](https://github.com/Hyundai-Kia-Connect/kia_uvo/assets/123817278/8b869d72-57b1-4115-b59c-2eda30d07c15)

**Comment by hmmbob** [comment]
And I don't have it, which makes sense as I can't set it through the app either for my car 😉 

Closing as 2.25.1 fixed it.

**Comment by PSXDupe** [comment]
> @PSXDupe Yes, i have, i am from Austria (EU)
> 
> ![grafik](https://private-user-images.githubusercontent.com/123817278/343652342-8b869d72-57b1-4115-b59c-2eda30d07c15.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0NzMyODgsIm5iZiI6MTcxOTQ3Mjk4OCwicGF0aCI6Ii8xMjM4MTcyNzgvMzQzNjUyMzQyLThiODY5ZDcyLTU3YjEtNDExNS1iNTljLTJlZGEzMGQwN2MxNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyN1QwNzIzMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNTk5ZTFiMTE1YTAyMDNkZTBjOTc0MzU5NGNmZTAwODUyNzM2OWRjN2VmNjg4OWQ2Mzk4NWM0N2IyNTYxMDUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.KfG2evddZRc_6h6ckmGCUK2psd1ad6J1GYXKhDYe9nM)
> 
> And many more in total 50 Sensors.
> 
> This is my Dashboard in Home-Assistant: ![grafik](https://private-user-images.githubusercontent.com/123817278/343652800-33406853-2bf3-4e5f-a6d8-0f8527364f72.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0NzMyODgsIm5iZiI6MTcxOTQ3Mjk4OCwicGF0aCI6Ii8xMjM4MTcyNzgvMzQzNjUyODAwLTMzNDA2ODUzLTJiZjMtNGU1Zi1hNmQ4LTBmODUyNzM2NGY3Mi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyN1QwNzIzMDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NTkxYWFiMmQ3ZTAwNDM0Y2ZmMGRlZTMzYzljZTE1N2Y1YTkwZmUxYjhiNzViZDVmYjI3OTU0ZWIxNDJhNzQ0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kwcs0uxZw-aJBtGJcirb21GziMAZV80RlLW8LQ3B9m4)

That is not the new data added, the is AC Charging Limit, that was always there, the new option is "AC Charging Current", that allows you to change how fast the car will charge on AC. In the car you can set this to 100%, 90% or 60%

**Comment by MobilettoSoft** [comment]
I don't have it too, but maybe in my case it's due to the fact I got a plug-in hybrid MY2022 Tucson. I can set the charging current from the car but there's no setting in the bluelink app. No charging limit for me, too.
