### ISSUE TITLE
Error fetching kia_uvo data: Error communicating with API

### ISSUE THREAD

**Issue by CDAutomate** [Hyundai-Kia-Connect/kia_uvo#914]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/kia_uvo/blob/master/README.md
**Region and Brand of car**
Canada, Kia

**Version of the integration**
2.26.1

**Describe the bug**

Logger: custom_components.kia_uvo.coordinator
Source: helpers/update_coordinator.py:344
integration: Hyundai / Kia Connect ([documentation](https://github.com/Hyundai-Kia-Connect/kia_uvo), [issues](https://github.com/Hyundai-Kia-Connect/kia_uvo/issues))
First occurred: July 28, 2024 at 10:43:29 AM (3 occurrences)
Last logged: 7:47:10 AM
Error fetching kia_uvo data: Error communicating with API: Traceback (most recent call last): File "/usr/local/lib/python3.12/site-packages/requests/models.py", line 974, in json return complexjson.loads(self.text, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/simplejson/__init__.py", line 514, in loads return _default_decoder.decode(s) ^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/simplejson/decoder.py", line 386, in decode obj, end = self.raw_decode(s) ^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/simplejson/decoder.py", line 416, in raw_decode return self.scan_once(s, idx=_w(s, idx).end()) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0) During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/config/custom_components/kia_uvo/coordinator.py", line 126, in _async_update_data await self.hass.async_add_executor_job( File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run result = self.fn(*self.args, **self.kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 113, in check_and_force_update_vehicles self.update_vehicle_with_cached_state(vehicle_id) File "/usr/local/lib/python3.12/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 92, in update_vehicle_with_cached_state self.api.update_geocoded_location( File "/usr/local/lib/python3.12/site-packages/hyundai_kia_connect_api/ApiImpl.py", line 118, in update_geocoded_location response = response.json() ^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/requests/models.py", line 978, in json raise RequestsJSONDecodeError(e.msg, e.doc, e.pos) requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0) During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/config/custom_components/kia_uvo/coordinator.py", line 132, in _async_update_data await self.hass.async_add_executor_job( File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run result = self.fn(*self.args, **self.kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 85, in update_all_vehicles_with_cached_state self.update_vehicle_with_cached_state(vehicle_id) File "/usr/local/lib/python3.12/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 92, in update_vehicle_with_cached_state self.api.update_geocoded_location( File "/usr/local/lib/python3.12/site-packages/hyundai_kia_connect_api/ApiImpl.py", line 118, in update_geocoded_location response = response.json() ^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/requests/models.py", line 978, in json raise RequestsJSONDecodeError(e.msg, e.doc, e.pos) requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

Outlined here: https://github.com/fuatakgun/kia_uvo/blob/master/README.md

**To Reproduce**
Initialize Integration

**Expected behavior**
Integration initializes successfully and provides data

**Screenshots**

**Additional context**

**Comment by cdnninja** [comment]
Enable debug logs and post them.

**Comment by stephenmhall** [comment]
Not working for me either, logs showing 
hyundai_kia_connect_api.exceptions.RateLimitingError: Exceeds number of requests - Exceeds Number of Requests.
Maybe they have changed the amount allowed down?

**Comment by cdnninja** [comment]
That's a different error.

**Comment by CDAutomate** [comment]
2024-07-30 12:51:24.281 DEBUG (SyncWorker_7) [hyundai_kia_connect_api.KiaUvoApiCA] hyundai_kia_connect_api - Sign In Response {"responseHeader":{"responseCode":0,"responseDesc":"Success"},"result":{"accessToken":"eyJlbmMiOiJ3QlYyZjRzL2phQ0JpY05Sa3FvbHd3c2F1MzdQTDlUUGdMMUdYL1MwNDRyS213eWdaS0syZnhtc2wyb2dHdGc5OVFkQjdCdWFGY1h3Zm9lRW4zVVhkQWZUWjM3RXFZODB2REtPUy9xNjZ5R1FPTzV3eGYxR1ZnRk1CNGpoQm1uWnV3YWM0OUdTaUpFMEtCamN3bWpjY21OSEJTNWNCWkZxNjM3U0tJUWVyL3RjcVVHMHZvK2dIamdBZGQzLy9sTkdUOVhnV0RRY042ckJFdExJQkRVSlZsSkdMSlBuQm1iK3ZPWXYxbkJPVlZvcEhaNXgzWDhZNnltSDhBQTNBcnlyaFZKTTlOSW5mUlRBd2ZkTUhsVVlQSkcvWnNpczV6N0VDYnU0Z0V6STRydFhLcWs3N0N0cDAydXhTVENhcGx1aWhjUmpLOVh3RGVDbDUwNFNOQjJReTJ4YjNsd04vb0t3T3kxRzNvWGozeUhFMUV1UFlWL2doYVJDQ3RhOFVpM3hmTXFRc2FrUFBpQnRScEZHcVQ2SFQ3YXVFMjh1Ni9KWnV0SG1qZDlDb29BbXYxWHliQjA0T29oWjdlS0FCb0x6bEZUa2pvWWJDcE8xcCs2UVIyVEl0WklQNVRNakFFWTEzNnVCUnUxYmMxVFhxS2ZSNFRrVU9aTWVJVEpjRHpjcVZJdWVRaFlmYVlyV2dDZDBYMlpGb0NicU9ycTI5ZmdmSmJYRUc5QUkzTDRXdzFOOG41cUFWOFVPeEhCRGNJUE9zNmllOHlmenhHcXp6RTV1eXBmV1p0cTFTRktuMUdhREJUSDlsVFNNczhuVU5PWUhMNGJZSzg0OTVMbklDdmlQTVBCWFZGZndHd1NoY3lwSm1qV3I2NWYvVTZGK3N1clZHVlFqZjg3U1ViYktWYUZhTlNYSTQrQWFPUVRZdlJvb1FlZ2tuTnBLWEd0MXlvSDZkMmllL205MEQ3VVB1cUNmU28zbll1VVRReFFIM0VuOEJTNnZjekRtWUJOK2ZGbGhDQTVKZW1xRWF4U1UxTlp5K3B4ZTVvWVB2OGpTWVJqVjA5eXh3N1N3S1V2b3NDSnJ2WVFmaVJhSVlLbGhWWTU5b2hCS3RuYU1VelExc1I1OG1LYlNndzRWOUJjakJlK0Nhd3NqTHltNi9MelJYc3V4eVhlbk11VHBWa0FhWmJGakc1YTQ4c2V5eEhLMEduQnJVM0l0WFh3R3JodzJIU29udUo4YVVCb1A3RXVuV05KbUVob2ZKa0NGNzhtU0RwMWhuVnBZTUpRK2tpR2t4emN2U2RKQmt2OFcxeFZvblJMQzFwVUt1T3ZRNDVIZ1JwYzBFOUR3L1JvZ25FN2hKcWJld25nYkVTdE95Q2NCZWQvNTQ5cTdzaHBoL0pjUE91Yk9wMVcyRTR2WjlXS0N1K2V5NXpoK1M4a2lFUlVnQi9SRVN0a2d1SG5VRktrd0NLMG1MMVNpQ2c9PSIsImtleSI6IkVRdHRMRjRGL0YxS2hzd2J5eFJzWUczNERlUFRNRStSc2xSQ0JqRlFiSkxGaG5oeUl2YXRRMWMrY0lzYXIyakdQLzhZUjdhZ2hNZ3FjRzkyUXpWT1FRPT0ifQ==","scope":["profile"],"tokenType":"bearer","expireIn":86400,"refreshToken":"eyJlbmMiOiJrcWRYelhRYkNxMi84d1ZRdEp0L3pYMXI0eitkNUVBLzhHODJ2L3NEVWVka2Z6d3F2S3lXbXhHUW83S01SZVFXWUxFaXhoNHpSTUxNQ0hkRkdPc055SjhpUnpXdWl6MVU0clFIcDRaZVBqd3BVVHFVa1l4UXVTU2lzM1ZoOEsvNHRLMkRXekNMa2FQSTd5OWFTOWRhRXJnN1FXKzNpODZ3RFZYVzlESzVNZXpRZE1zTG9Zd0o4ZlQzWERlU25TWk5pUVY1OVNrb2J1SGRBL1k5ejZlY3BDNWhVNnh3ekNPZFFuRWVTd2NicEpCOWFmM0c2VGx1VjIrdHJvM3luc2hwdnpMaVZyUFJVNnFmanpvTGQ4UnBTSWhSUGFXMlkwU2FvT0g5d1JRNEQ0eHl0c1F5aHVhMTNIc1NFM3dhU09JU3Y4d2pBblgzS0JKOWZMbTlZSTRXc3puM2p0aWFPNnc0V1daN2kveWNjVTBaOXJXbEhMdjJSYjJSenN2ZUZ5MEQxbzNFTE5aYjhpUk9NWkcyZEJYZXB3azRhZTdobVlHeVZiNzhqZ2xib3pvSzJPYncwMGY2NStMUzg1aXMwWnE4YUs1N0NFeTFHK1lsRERkSFhoZjZ5Ti84Q3RZbE1OTnZzQk1QNHc1TFIzZ3pJYkg5U2RzcEpuYk8zRXpaL1pOUGdzbmh0czZOYXZUYzYrRHRZRjh4ZjZVbDdjNmtJVS9lVklSSVpsaHZXUUtNNzJBS09odFQ5VllzSjY4RnlOWFliTUM2K3FBZlR0NnBIb0p0RXNZZ2RZOGhOT1ZNQ3hOYzByNUIvT0IzQkI5K1ZRSTVUR01QYTZYM1pDWFZlbDY3elVTbkIxUDRTVXB5MnJ0WmNiN2hpNmUxaDB6MUUvRVRiNFpFUjZLL2FtT3FzdEt2Y0NFaTFUUUNieVhFQTZ1WGp0d3lwcG5EcDNCYndZVFhzajhmcVFvbGN2c3VxZ3NuRUZ6bkRHc3RtekhwUk1ZME5WckdudkxjVWFBRkdBWHdHVU81VzZPVG1WZWhuRzJTZzFzL3RSNFFQSFhkREJIaUR0MFBFL1hFeXdKckhzcllqWE4zbnJyV0c1blF1RVlNNTBvdlhOb0t5RG5CL0dkV0RIWXdHcnY1cEoveUNlRVZidHljeEVhVUM4bXhKNHpieHoxMVZqVFB4bVZhekFmUnRUWGI2czF3V2hNekZ0b0NnT1dnWXA4N1B5UWJraW1tbUJsZGNNa29wbjVURjMwa2RaSW9lZTM2MFRoWmNUc1JUeXBwb2F3L1lLTkFDSjZSTDRYV0FFRjkyWmFlYVdrZy9oU3RKY05DTTVDK3pPQjc1SDBGTFlJa0ZJcWJzQjNPYVRpQ1hpU1d0MVdEWmRtcC9peTdFTXdwdk1GY1Y5clJvK0JEK0dzejlacDV1QUJ2MTlkQ01MOFMzcmo3UlN5LzE3OFdxRUczMEJka2ppSDljSzh6NGc9PSIsImtleSI6Impvb3dwQmhJMjRTbDZ5TllSYjlJNEFNR09zZVpjQXh3UmE3dXRFa1NOZUdjSEd4bUdCWUhDempweTA5OE5XMFA3T3NkQkJPMHU4RFBaaDZjajBTZElnPT0ifQ==","signature":""}}
2024-07-30 12:51:24.281 DEBUG (SyncWorker_7) [hyundai_kia_connect_api.KiaUvoApiCA] hyundai_kia_connect_api - Access Token Value eyJlbmMiOiJ3QlYyZjRzL2phQ0JpY05Sa3FvbHd3c2F1MzdQTDlUUGdMMUdYL1MwNDRyS213eWdaS0syZnhtc2wyb2dHdGc5OVFkQjdCdWFGY1h3Zm9lRW4zVVhkQWZUWjM3RXFZODB2REtPUy9xNjZ5R1FPTzV3eGYxR1ZnRk1CNGpoQm1uWnV3YWM0OUdTaUpFMEtCamN3bWpjY21OSEJTNWNCWkZxNjM3U0tJUWVyL3RjcVVHMHZvK2dIamdBZGQzLy9sTkdUOVhnV0RRY042ckJFdExJQkRVSlZsSkdMSlBuQm1iK3ZPWXYxbkJPVlZvcEhaNXgzWDhZNnltSDhBQTNBcnlyaFZKTTlOSW5mUlRBd2ZkTUhsVVlQSkcvWnNpczV6N0VDYnU0Z0V6STRydFhLcWs3N0N0cDAydXhTVENhcGx1aWhjUmpLOVh3RGVDbDUwNFNOQjJReTJ4YjNsd04vb0t3T3kxRzNvWGozeUhFMUV1UFlWL2doYVJDQ3RhOFVpM3hmTXFRc2FrUFBpQnRScEZHcVQ2SFQ3YXVFMjh1Ni9KWnV0SG1qZDlDb29BbXYxWHliQjA0T29oWjdlS0FCb0x6bEZUa2pvWWJDcE8xcCs2UVIyVEl0WklQNVRNakFFWTEzNnVCUnUxYmMxVFhxS2ZSNFRrVU9aTWVJVEpjRHpjcVZJdWVRaFlmYVlyV2dDZDBYMlpGb0NicU9ycTI5ZmdmSmJYRUc5QUkzTDRXdzFOOG41cUFWOFVPeEhCRGNJUE9zNmllOHlmenhHcXp6RTV1eXBmV1p0cTFTRktuMUdhREJUSDlsVFNNczhuVU5PWUhMNGJZSzg0OTVMbklDdmlQTVBCWFZGZndHd1NoY3lwSm1qV3I2NWYvVTZGK3N1clZHVlFqZjg3U1ViYktWYUZhTlNYSTQrQWFPUVRZdlJvb1FlZ2tuTnBLWEd0MXlvSDZkMmllL205MEQ3VVB1cUNmU28zbll1VVRReFFIM0VuOEJTNnZjekRtWUJOK2ZGbGhDQTVKZW1xRWF4U1UxTlp5K3B4ZTVvWVB2OGpTWVJqVjA5eXh3N1N3S1V2b3NDSnJ2WVFmaVJhSVlLbGhWWTU5b2hCS3RuYU1VelExc1I1OG1LYlNndzRWOUJjakJlK0Nhd3NqTHltNi9MelJYc3V4eVhlbk11VHBWa0FhWmJGakc1YTQ4c2V5eEhLMEduQnJVM0l0WFh3R3JodzJIU29udUo4YVVCb1A3RXVuV05KbUVob2ZKa0NGNzhtU0RwMWhuVnBZTUpRK2tpR2t4emN2U2RKQmt2OFcxeFZvblJMQzFwVUt1T3ZRNDVIZ1JwYzBFOUR3L1JvZ25FN2hKcWJld25nYkVTdE95Q2NCZWQvNTQ5cTdzaHBoL0pjUE91Yk9wMVcyRTR2WjlXS0N1K2V5NXpoK1M4a2lFUlVnQi9SRVN0a2d1SG5VRktrd0NLMG1MMVNpQ2c9PSIsImtleSI6IkVRdHRMRjRGL0YxS2hzd2J5eFJzWUczNERlUFRNRStSc2xSQ0JqRlFiSkxGaG5oeUl2YXRRMWMrY0lzYXIyakdQLzhZUjdhZ2hNZ3FjRzkyUXpWT1FRPT0ifQ==
2024-07-30 12:51:24.281 DEBUG (SyncWorker_7) [hyundai_kia_connect_api.KiaUvoApiCA] hyundai_kia_connect_api - Refresh Token Value eyJlbmMiOiJrcWRYelhRYkNxMi84d1ZRdEp0L3pYMXI0eitkNUVBLzhHODJ2L3NEVWVka2Z6d3F2S3lXbXhHUW83S01SZVFXWUxFaXhoNHpSTUxNQ0hkRkdPc055SjhpUnpXdWl6MVU0clFIcDRaZVBqd3BVVHFVa1l4UXVTU2lzM1ZoOEsvNHRLMkRXekNMa2FQSTd5OWFTOWRhRXJnN1FXKzNpODZ3RFZYVzlESzVNZXpRZE1zTG9Zd0o4ZlQzWERlU25TWk5pUVY1OVNrb2J1SGRBL1k5ejZlY3BDNWhVNnh3ekNPZFFuRWVTd2NicEpCOWFmM0c2VGx1VjIrdHJvM3luc2hwdnpMaVZyUFJVNnFmanpvTGQ4UnBTSWhSUGFXMlkwU2FvT0g5d1JRNEQ0eHl0c1F5aHVhMTNIc1NFM3dhU09JU3Y4d2pBblgzS0JKOWZMbTlZSTRXc3puM2p0aWFPNnc0V1daN2kveWNjVTBaOXJXbEhMdjJSYjJSenN2ZUZ5MEQxbzNFTE5aYjhpUk9NWkcyZEJYZXB3azRhZTdobVlHeVZiNzhqZ2xib3pvSzJPYncwMGY2NStMUzg1aXMwWnE4YUs1N0NFeTFHK1lsRERkSFhoZjZ5Ti84Q3RZbE1OTnZzQk1QNHc1TFIzZ3pJYkg5U2RzcEpuYk8zRXpaL1pOUGdzbmh0czZOYXZUYzYrRHRZRjh4ZjZVbDdjNmtJVS9lVklSSVpsaHZXUUtNNzJBS09odFQ5VllzSjY4RnlOWFliTUM2K3FBZlR0NnBIb0p0RXNZZ2RZOGhOT1ZNQ3hOYzByNUIvT0IzQkI5K1ZRSTVUR01QYTZYM1pDWFZlbDY3elVTbkIxUDRTVXB5MnJ0WmNiN2hpNmUxaDB6MUUvRVRiNFpFUjZLL2FtT3FzdEt2Y0NFaTFUUUNieVhFQTZ1WGp0d3lwcG5EcDNCYndZVFhzajhmcVFvbGN2c3VxZ3NuRUZ6bkRHc3RtekhwUk1ZME5WckdudkxjVWFBRkdBWHdHVU81VzZPVG1WZWhuRzJTZzFzL3RSNFFQSFhkREJIaUR0MFBFL1hFeXdKckhzcllqWE4zbnJyV0c1blF1RVlNNTBvdlhOb0t5RG5CL0dkV0RIWXdHcnY1cEoveUNlRVZidHljeEVhVUM4bXhKNHpieHoxMVZqVFB4bVZhekFmUnRUWGI2czF3V2hNekZ0b0NnT1dnWXA4N1B5UWJraW1tbUJsZGNNa29wbjVURjMwa2RaSW9lZTM2MFRoWmNUc1JUeXBwb2F3L1lLTkFDSjZSTDRYV0FFRjkyWmFlYVdrZy9oU3RKY05DTTVDK3pPQjc1SDBGTFlJa0ZJcWJzQjNPYVRpQ1hpU1d0MVdEWmRtcC9peTdFTXdwdk1GY1Y5clJvK0JEK0dzejlacDV1QUJ2MTlkQ01MOFMzcmo3UlN5LzE3OFdxRUczMEJka2ppSDljSzh6NGc9PSIsImtleSI6Impvb3dwQmhJMjRTbDZ5TllSYjlJNEFNR09zZVpjQXh3UmE3dXRFa1NOZUdjSEd4bUdCWUhDempweTA5OE5XMFA3T3NkQkJPMHU4RFBaaDZjajBTZElnPT0ifQ==
2024-07-30 12:51:24.479 DEBUG (SyncWorker_7) [hyundai_kia_connect_api.KiaUvoApiCA] hyundai_kia_connect_api - Get Vehicles Response {"responseHeader":{"responseCode":0,"responseDesc":"Success"},"result":{"vehicles":[{"vehicleId":"cAErzCvasR+azla/CY5jiw==","nickName":"Stinger","modelCode":"J5S6J5G1KG","modelName":"Stinger","modelYear":"2020","fuelKindCode":"G","trim":"","engine":"","exteriorColor":"C4S","dtcCount":0,"subscriptionStatus":"A","subscriptionEndDate":"20250629","mileageForNextService":9920.099999999999,"daysForNextService":"20250129","overviewMessage":"","defaultVehicle":true,"enrollmentStatus":"4","genType":"G1","photoUrl":"https://kiaconnect.ca/vin/2022/09/a65742f0b22d464a90cb7db8f350c16d_1662644333054.jpeg","valetParkingModeOn":1,"isBasicPackage":false,"vin":"3493"}]}}
2024-07-30 12:51:24.594 DEBUG (SyncWorker_50) [hyundai_kia_connect_api.KiaUvoApiCA] hyundai_kia_connect_api - get_cached_vehicle_status response {'responseHeader': {'responseCode': 0, 'responseDesc': 'Success'}, 'result': {'status': {'lastStatusDate': '20240730184929', 'airCtrlOn': False, 'engine': False, 'doorLock': True, 'doorOpen': {'frontLeft': 0, 'frontRight': 0, 'backLeft': 0, 'backRight': 0}, 'trunkOpen': False, 'airTempUnit': 'C', 'airTemp': {'value': '01H', 'unit': 0}, 'defrost': False, 'lowFuelLight': False, 'acc': False, 'hoodOpen': False, 'transCond': True, 'steerWheelHeat': 0, 'dte': {'value': 355.0, 'unit': 1}, 'tirePressureLamp': {'tirePressureLampAll': 0}, 'battery': {'batSoc': 74, 'batSignalReferenceValue': {}}, 'remoteIgnition': True, 'seatHeaterVentInfo': {}, 'sleepModeCheck': False, 'lampWireStatus': {'headLamp': {}, 'stopLamp': {}, 'turnSignalLamp': {}}, 'windowOpen': {}, 'engineRuntime': {}}}}
2024-07-30 12:51:24.594 DEBUG (SyncWorker_50) [hyundai_kia_connect_api.KiaUvoApiCA] hyundai_kia_connect_api - Old Vehicle Last Updated: None
2024-07-30 12:51:24.594 DEBUG (SyncWorker_50) [hyundai_kia_connect_api.KiaUvoApiCA] hyundai_kia_connect_api - Current Vehicle Last Updated: 2024-07-30 12:49:29-06:00
2024-07-30 12:51:24.721 DEBUG (SyncWorker_50) [hyundai_kia_connect_api.KiaUvoApiCA] hyundai_kia_connect_api - Get Service status data {'responseHeader': {'responseCode': 0, 'responseDesc': 'Success'}, 'result': {'maintenanceInfo': {'msopServiceOdometer': 40565.0, 'msopServiceOdometerUnit': 1, 'mtspServiceDate': '20240729', 'imatServiceOdometer': 50565.0, 'imatServiceOdometerUnit': 1, 'mtitServiceDate': '20250129', 'currentOdometer': 40644.9, 'currentOdometerUnit': 1, 'serviceOdometerDuration': 10000.0, 'serviceDaysDuration': 184, 'serviceMonthsThreshold': 6}}}
2024-07-30 12:51:24.840 DEBUG (SyncWorker_50) [hyundai_kia_connect_api.KiaUvoApiCA] hyundai_kia_connect_api - Received Pin validation response {'responseHeader': {'responseCode': 0, 'responseDesc': 'Success'}, 'result': {'pAuth': 'rlScCCFJRDMxdSTxkAdSkbdJTudBCYdv'}}
2024-07-30 12:51:31.106 DEBUG (SyncWorker_50) [hyundai_kia_connect_api.KiaUvoApiCA] hyundai_kia_connect_api - Get Vehicle Location {'responseHeader': {'responseCode': 0, 'responseDesc': 'Success'}, 'result': {'head': 178, 'coord': {'lat': 51.09804444, 'lon': -114.034175, 'alt': 1067.0, 'type': 0}, 'accuracy': {'hdop': 6, 'pdop': 10}, 'time': '20240730185127', 'speed': {'value': 0, 'unit': 0}}}
2024-07-30 12:51:31.106 DEBUG (SyncWorker_50) [hyundai_kia_connect_api.ApiImpl] hyundai_kia_connect_api - Running update geocode location with value: https://nominatim.openstreetmap.org/reverse?lat=51.09804444&lon=-114.034175&format=json&addressdetails=1&zoom=18
2024-07-30 12:51:31.434 DEBUG (SyncWorker_4) [hyundai_kia_connect_api.KiaUvoApiCA] hyundai_kia_connect_api - get_cached_vehicle_status response {'responseHeader': {'responseCode': 0, 'responseDesc': 'Success'}, 'result': {'status': {'lastStatusDate': '20240730184929', 'airCtrlOn': False, 'engine': False, 'doorLock': True, 'doorOpen': {'frontLeft': 0, 'frontRight': 0, 'backLeft': 0, 'backRight': 0}, 'trunkOpen': False, 'airTempUnit': 'C', 'airTemp': {'value': '01H', 'unit': 0}, 'defrost': False, 'lowFuelLight': False, 'acc': False, 'hoodOpen': False, 'transCond': True, 'steerWheelHeat': 0, 'dte': {'value': 355.0, 'unit': 1}, 'tirePressureLamp': {'tirePressureLampAll': 0}, 'battery': {'batSoc': 74, 'batSignalReferenceValue': {}}, 'remoteIgnition': True, 'seatHeaterVentInfo': {}, 'sleepModeCheck': False, 'lampWireStatus': {'headLamp': {}, 'stopLamp': {}, 'turnSignalLamp': {}}, 'windowOpen': {}, 'engineRuntime': {}}}}
2024-07-30 12:51:31.434 DEBUG (SyncWorker_4) [hyundai_kia_connect_api.KiaUvoApiCA] hyundai_kia_connect_api - Old Vehicle Last Updated: 2024-07-30 12:49:29-06:00
2024-07-30 12:51:31.434 DEBUG (SyncWorker_4) [hyundai_kia_connect_api.KiaUvoApiCA] hyundai_kia_connect_api - Current Vehicle Last Updated: 2024-07-30 12:49:29-06:00
2024-07-30 12:51:31.547 DEBUG (SyncWorker_4) [hyundai_kia_connect_api.KiaUvoApiCA] hyundai_kia_connect_api - Get Service status data {'responseHeader': {'responseCode': 0, 'responseDesc': 'Success'}, 'result': {'maintenanceInfo': {'msopServiceOdometer': 40565.0, 'msopServiceOdometerUnit': 1, 'mtspServiceDate': '20240729', 'imatServiceOdometer': 50565.0, 'imatServiceOdometerUnit': 1, 'mtitServiceDate': '20250129', 'currentOdometer': 40644.9, 'currentOdometerUnit': 1, 'serviceOdometerDuration': 10000.0, 'serviceDaysDuration': 184, 'serviceMonthsThreshold': 6}}}
2024-07-30 12:51:31.547 DEBUG (SyncWorker_4) [hyundai_kia_connect_api.ApiImpl] hyundai_kia_connect_api - Running update geocode location with value: https://nominatim.openstreetmap.org/reverse?lat=51.09804444&lon=-114.034175&format=json&addressdetails=1&zoom=18
2024-07-30 12:51:34.242 DEBUG (MainThread) [custom_components.kia_uvo.coordinator] Finished fetching kia_uvo data in 10.376 seconds (success: False)

**Comment by rmunroe** [comment]
Any updates to this issue or known workarounds?

**Comment by cdnninja** [comment]
It's a duplicate issue but one work around is disable geo location.  More debug statements need to be added to see what is going wrong.

**Comment by theriaultjulien** [comment]
I have a similar issue, I get this error in Home Assistant after adding the integration:
`Failed setup, will retry: Config Not Ready: Error communicating with API: Traceback (most recent call last): File "/usr/local/lib/python3.12/site-packages/requests/models.py", line 974, in json return complexjson.loads(self.text, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/simplejson/__init__.py", line 514, in loads return _default_decoder.decode(s) ^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/simplejson/decoder.py", line 386, in decode obj, end = self.raw_decode(s) ^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.12/site-packages/simplejson/decoder.py", line 416, in raw_decode return...`

In DEBUG logs I can see that my credentials are fine and the API seems to be working:
`2024-08-14 21:42:16.929 DEBUG (SyncWorker_2) [hyundai_kia_connect_api.KiaUvoApiCA] hyundai_kia_connect_api - Sign In Response {"responseHeader":{"responseCode":0,"responseDesc":"Success"},"result":`

And I can see it gets info on my car:
`2024-08-14 21:42:17.137 DEBUG (SyncWorker_2) [hyundai_kia_connect_api.KiaUvoApiCA] hyundai_kia_connect_api - Get Vehicles Response {"responseHeader":{"responseCode":0,"responseDesc":"Success"},"result":{"vehicles":[{"vehicleId":"I//VimX+uagOj9lPXpY7aw==","nickName":"Niro","modelCode":"TOW5ZHZ7ZHH532","modelName":"Niro","modelYear":"2024","fuelKindCode":"E","trim":"","engine":"","exteriorColor":"SWP","dtcCount":0,"subscriptionStatus":"A","subscriptionEndDate":"20270808","mileageForNextService":11707.3,"daysForNextService":"20250211","overviewMessage":"","defaultVehicle":true,"enrollmentStatus":"4","genType":"G3","valetParkingModeOn":1,"mainBatteryType":0,"isBasicPackage":false,"isWarrantyExpired":"0","vin":"9012"}]}}`

Right after this there's this line:
`2024-08-14 21:42:17.615 DEBUG (MainThread) [custom_components.kia_uvo.coordinator] Finished fetching kia_uvo data in 1.192 seconds (success: False)`

Here's the complete log file:
[home-assistant_2024-08-15T01-58-13.448Z.log](https://github.com/user-attachments/files/16620555/home-assistant_2024-08-15T01-58-13.448Z.log)


Geo location is disabled by default.

**Comment by cdnninja** [comment]
I tried to improve some logging. Could you update to latest and see if logs have more detail?

**Comment by theriaultjulien** [comment]
I updated to latest and tried again, here are the logs
[home-assistant_2024-08-15T03-16-24.482Z.log](https://github.com/user-attachments/files/16621063/home-assistant_2024-08-15T03-16-24.482Z.log)

**Comment by cdnninja** [comment]
What version is this just to confirm?

**Comment by theriaultjulien** [comment]
v.2.26.2
![image](https://github.com/user-attachments/assets/85bb7861-60a3-402e-91e4-745c3cebda34)

Idk if this info is useful, but my home-assistant installation is brand new, I just created a HA VM just to try this integration out, I don't have any other custom integrations or anything.

**Comment by cdnninja** [comment]
Please try latest and report back with logs.

**Comment by theriaultjulien** [comment]
Hi, updated to latest (2.26.4) and retried, here are the logs, now there's much more stuff!
[home-assistant_2024-08-16T17-51-12.526Z.log](https://github.com/user-attachments/files/16639949/home-assistant_2024-08-16T17-51-12.526Z.log)

**Comment by cdnninja** [comment]
This is a different issue from OP.   Does a "force update" work from the native app?

**Comment by theriaultjulien** [comment]
Okay. Should I open another issue then?

You mean on the Kia Connect app, do a refresh?
It doesn't work, it refreshes like every 6-8 hours. That's why I wanted to try this integration, their app sucks and does not update at all.

**Comment by cdnninja** [comment]
The integration is failing for you because the native api is failing.  Is your car outside within cell service?

**Comment by theriaultjulien** [comment]
I see... Yes the car is parked outside, plugged in and in a city with good cell service. Could it be a problem with the car then? Should I talk to my dealership? lol getting off track sorry

**Comment by cdnninja** [comment]
If the native app fails when you click that update button yes talk to manufacturer. No need to talk to them about the integration as the product they make doesn't work.

**Comment by cdnninja** [comment]
Keep this integration disabled while you do that in case it's maxing out calls.

**Comment by theriaultjulien** [comment]
Thanks for your help I will check with my dealership.

**Comment by cdnninja** [comment]
As the OP hasn't returned I am going to close this for now.  The comment from OP is also duplicate to other thread. @theriaultjulien  if you have more questions please open a new issue.
