### ISSUE TITLE
Seems like a limit has been introduced in the API

### ISSUE THREAD

**Issue by adorobis** [Hyundai-Kia-Connect/kia_uvo#918]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/kia_uvo/blob/master/README.md
**Region and Brand of car**
EU, Poland, Kia Sorento
**Version of the integration**
2.26.1

**Describe the bug**
The integration does not load since a few days. When I try to login via the mobile app I get an error message:
"The maximum number of daily vehicle checks has been exceeded. Please be avvare that using 3rd party apps may contribute to exceeding this limit. "

**Debug logs if an error occurred**
Here is the error in the HA log:
```
2024-08-07 22:37:58.135 ERROR (MainThread) [custom_components.kia_uvo.coordinator] Unexpected error fetching kia_uvo data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/kia_uvo/coordinator.py", line 144, in _async_update_data
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 85, in update_all_vehicles_with_cached_state
    self.update_vehicle_with_cached_state(vehicle_id)
  File "/usr/local/lib/python3.12/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 90, in update_vehicle_with_cached_state
    self.api.update_vehicle_with_cached_state(self.token, vehicle)
  File "/usr/local/lib/python3.12/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 341, in update_vehicle_with_cached_state
    _check_response_for_errors(response)
  File "/usr/local/lib/python3.12/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 128, in _check_response_for_errors
    raise error_code_mapping[response["resCode"]](response["resMsg"])
hyundai_kia_connect_api.exceptions.NoDataFound: No Data Found v2 - No Data Found v2

```
Outlined here: https://github.com/fuatakgun/kia_uvo/blob/master/README.md

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by cdnninja** [comment]
It has always had limits.  What's your polling frequency set to?

**Comment by adorobis** [comment]
I haven't set it at all so I assume it is 1 minute as this is HA default. Or is it any different for this integration? So far I did not have this issue so I'm happy to adjust to what the limits are

**Comment by cdnninja** [comment]
One minute was never the integration default.   Without you checking these numbers not much else we can do.   Defaults have changed over the years of this integration as well.

**Comment by adorobis** [comment]
> One minute was never the integration default.

Sorry, it was my assumption without checking. I have edited the reply and I have 30 minutes refresh and force update every 1440 minutes. So not sure what has happened or what the limits actually are. I now have to wait anyway as I can't even login via the mobile app. For now I've disabled the integration.

**Comment by adorobis** [comment]
OK, my account is now unlocked, I can log in via the monile app. But the integration still does not work. Here is the debug log, not really meaningful for me so far:
```
2024-08-12 11:53:59.016 DEBUG (SyncWorker_0) [hyundai_kia_connect_api.KiaUvoApiEU] hyundai_kia_connect_api - Get Device ID request: https://prd.eu-ccapi.kia.com:8080/api/v1/spa/notifications/register {'ccsp-service-id': 'fdc85c00-0a2f-4c64-bcb4-2cfb1500730a', 'ccsp-application-id': 'a2b8469b-30a3-4361-8e13-6fceea8fbe74', 'Stamp': 'oYa3/zyroR0vT6ZgagTzPJcFq9FRkgRPjU5ih3eFC/Og5gc/7ggOgn7OQsDF18g=', 'Content-Type': 'application/json;charset=UTF-8', 'Host': 'prd.eu-ccapi.kia.com:8080', 'Connection': 'Keep-Alive', 'Accept-Encoding': 'gzip', 'User-Agent': 'okhttp/3.12.0'} {'pushRegId': '34351388a48a4d1a5f6b4f8ec389d39301d0c96ad9128ecd98406e8f3dcbaa99', 'pushType': 'APNS', 'uuid': '902b89af-192b-49b2-9f67-2d9a2dd6170c'}
2024-08-12 11:53:59.203 DEBUG (SyncWorker_0) [hyundai_kia_connect_api.KiaUvoApiEU] hyundai_kia_connect_api - Get Device ID response: {'retCode': 'S', 'resCode': '0000', 'resMsg': {'deviceId': '9b7824f7-3350-4441-97fb-e228e365d489'}, 'msgId': 'd42e920f-1fa5-4ed6-85fe-cd0268baec99'}
2024-08-12 11:53:59.203 DEBUG (SyncWorker_0) [hyundai_kia_connect_api.KiaUvoApiEU] hyundai_kia_connect_api - Get cookies request: https://prd.eu-ccapi.kia.com:8080/api/v1/user/oauth2/authorize?response_type=code&state=test&client_id=fdc85c00-0a2f-4c64-bcb4-2cfb1500730a&redirect_uri=https://prd.eu-ccapi.kia.com:8080/api/v1/user/oauth2/redirect&lang=en
2024-08-12 11:53:59.349 DEBUG (SyncWorker_0) [hyundai_kia_connect_api.KiaUvoApiEU] hyundai_kia_connect_api - Get cookies response: {'account': 'MTA0N2I4ZjYtYmZlZi00NDMxLWE4MTgtYWJlNWM0OGJjYmFl.53cab1bcd4b73d8fc0ef616020fbde8bb4cf6156', 'TS012b00dd': '01cbaa6f70873550a76e06610f7146cd25a8dbb367a04a6eaa04f6412cc71bdf1ae2fa502977c9f75f7f21ffd5e3f7e2735f2a84406c3317adf882eb8a10a4717af632aa1e'}
2024-08-12 11:53:59.589 DEBUG (SyncWorker_0) [hyundai_kia_connect_api.KiaUvoApiEU] hyundai_kia_connect_api - Sign In Response: {'errId': '3d1d6928-2fbd-42c3-8c9b-c5cb87434fa1', 'errCode': '4003', 'errMsg': 'Invalid values'}
2024-08-12 11:53:59.590 DEBUG (SyncWorker_0) [hyundai_kia_connect_api.KiaUvoApiEU] hyundai_kia_connect_api - get_authorization_code_with_redirect_url failed
2024-08-12 11:53:59.703 DEBUG (SyncWorker_0) [hyundai_kia_connect_api.KiaUvoApiEU] hyundai_kia_connect_api - IntegrationInfo Response: {'userId': '1047b8f6-bfef-4431-a818-abe5c48bcbae', 'serviceId': 'fdc85c00-0a2f-4c64-bcb4-2cfb1500730a', 'serviceName': 'UVO'}
2024-08-12 11:53:59.854 DEBUG (SyncWorker_0) [hyundai_kia_connect_api.KiaUvoApiEU] hyundai_kia_connect_api - LoginForm https://eu-account.kia.com/auth/realms/eukiaidm/protocol/openid-connect/auth?client_id=572e0304-5f8d-4b4c-9dd5-41aa84eed160&scope=openid%20profile%20email%20phone&response_type=code&hkid_session_reset=true&redirect_uri=https://prd.eu-ccapi.kia.com:8080/api/v1/user/integration/redirect/login&ui_locales=en&state=fdc85c00-0a2f-4c64-bcb4-2cfb1500730a:1047b8f6-bfef-4431-a818-abe5c48bcbae - Response:     <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
2024-08-12 11:54:00.079 DEBUG (SyncWorker_0) [hyundai_kia_connect_api.KiaUvoApiEU] hyundai_kia_connect_api - LoginFormSubmit https://eu-account.kia.com/auth/realms/eukiaidm/login-actions/authenticate?session_code=0WDbP7_jTBfAkk1Jhf-tanjlZN8Bgasedc9JrItu0Lc&execution=8eee4545-fa39-4c5c-8722-20e40c8b1710&client_id=572e0304-5f8d-4b4c-9dd5-41aa84eed160&tab_id=DnMZHA0h8xw - Response 302 - {'Date': 'Mon, 12 Aug 2024 09:54:00 GMT', 'Content-Length': '0', 'Connection': 'keep-alive', 'Cache-Control': 'no-store, must-revalidate, max-age=0', 'Set-Cookie': 'KEYCLOAK_LOCALE=en; Version=1; Path=/auth/realms/eukiaidm/; Secure; HttpOnly, KC_RESTART=; Version=1; Expires=Thu, 01-Jan-1970 00:00:10 GMT; Max-Age=0; Path=/auth/realms/eukiaidm/; Secure; HttpOnly, KEYCLOAK_IDENTITY=eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJmMWRhYjQ1Ni0zNGFjLTQxYmItODkwMC05NjNmODVlZjk5NTAifQ.eyJleHAiOjE3Mjg2NDA0NDAsImlhdCI6MTcyMzQ1NjQ0MCwianRpIjoiMDMxMDA2MjEtOTVjZi00N2UwLWE1ZWItZTUxMjJkMGY5NmQwIiwiaXNzIjoiaHR0cHM6Ly9ldS1hY2NvdW50LmtpYS5jb20vYXV0aC9yZWFsbXMvZXVraWFpZG0iLCJzdWIiOiJlNWZjMTJlYS1hMWYxLTQ3ZGQtOTE2ZC05MjBiZGUwYmQ4ZmEiLCJ0eXAiOiJTZXJpYWxpemVkLUlEIiwic2Vzc2lvbl9zdGF0ZSI6IjI2YTM4MmY4LTBlMzYtNDVhMi05MjY1LTljMjAxMjkyMTgyZCIsInNpZCI6IjI2YTM4MmY4LTBlMzYtNDVhMi05MjY1LTljMjAxMjkyMTgyZCIsInN0YXRlX2NoZWNrZXIiOiJoQmFYRmdHYUx2MnpHaEplT0FES3Vkeks5UlVlVzJvVDRpQ1owbnk5M2VBIn0.LfT5qizjciYJ0qeLI201rchL8RHCpzCcSaCeoVP11Qg; Version=1; Expires=Fri, 11-Oct-2024 09:54:00 GMT; Max-Age=5184000; Path=/auth/realms/eukiaidm/; SameSite=None; Secure; HttpOnly, KEYCLOAK_IDENTITY_LEGACY=eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJmMWRhYjQ1Ni0zNGFjLTQxYmItODkwMC05NjNmODVlZjk5NTAifQ.eyJleHAiOjE3Mjg2NDA0NDAsImlhdCI6MTcyMzQ1NjQ0MCwianRpIjoiMDMxMDA2MjEtOTVjZi00N2UwLWE1ZWItZTUxMjJkMGY5NmQwIiwiaXNzIjoiaHR0cHM6Ly9ldS1hY2NvdW50LmtpYS5jb20vYXV0aC9yZWFsbXMvZXVraWFpZG0iLCJzdWIiOiJlNWZjMTJlYS1hMWYxLTQ3ZGQtOTE2ZC05MjBiZGUwYmQ4ZmEiLCJ0eXAiOiJTZXJpYWxpemVkLUlEIiwic2Vzc2lvbl9zdGF0ZSI6IjI2YTM4MmY4LTBlMzYtNDVhMi05MjY1LTljMjAxMjkyMTgyZCIsInNpZCI6IjI2YTM4MmY4LTBlMzYtNDVhMi05MjY1LTljMjAxMjkyMTgyZCIsInN0YXRlX2NoZWNrZXIiOiJoQmFYRmdHYUx2MnpHaEplT0FES3Vkeks5UlVlVzJvVDRpQ1owbnk5M2VBIn0.LfT5qizjciYJ0qeLI201rchL8RHCpzCcSaCeoVP11Qg; Version=1; Expires=Fri, 11-Oct-2024 09:54:00 GMT; Max-Age=5184000; Path=/auth/realms/eukiaidm/; Secure; HttpOnly, KEYCLOAK_SESSION=eukiaidm/e5fc12ea-a1f1-47dd-916d-920bde0bd8fa/26a382f8-0e36-45a2-9265-9c201292182d; Version=1; Expires=Fri, 11-Oct-2024 09:54:00 GMT; Max-Age=5184000; Path=/auth/realms/eukiaidm/; SameSite=None; Secure, KEYCLOAK_SESSION_LEGACY=eukiaidm/e5fc12ea-a1f1-47dd-916d-920bde0bd8fa/26a382f8-0e36-45a2-9265-9c201292182d; Version=1; Expires=Fri, 11-Oct-2024 09:54:00 GMT; Max-Age=5184000; Path=/auth/realms/eukiaidm/; Secure, KEYCLOAK_REMEMBER_ME=username:adorobis%40gmail.com; Version=1; Expires=Tue, 12-Aug-2025 09:54:00 GMT; Max-Age=31536000; Path=/auth/realms/eukiaidm/; Secure; HttpOnly', 'P3P': 'CP="This is not a P3P policy!"', 'X-XSS-Protection': '1; mode=block', 'Location': 'https://prd.eu-ccapi.kia.com:8080/api/v1/user/integration/redirect/login?user_id=e5fc12ea-a1f1-47dd-916d-920bde0bd8fa&locale=en&state=fdc85c00-0a2f-4c64-bcb4-2cfb1500730a%3A1047b8f6-bfef-4431-a818-abe5c48bcbae&session_state=26a382f8-0e36-45a2-9265-9c201292182d&code=6847f09f-da18-463d-93a6-e029cd2c9ebf.26a382f8-0e36-45a2-9265-9c201292182d.4713f684-f667-4bd3-b1e9-67706072d32d', 'X-Frame-Options': 'SAMEORIGIN', 'Referrer-Policy': 'no-referrer', 'Content-Security-Policy': "frame-src 'self'; frame-ancestors 'self'; object-src 'none';", 'X-Robots-Tag': 'none', 'Strict-Transport-Security': 'max-age=15724800; includeSubDomains', 'X-Content-Type-Options': 'nosniff'}
2024-08-12 11:54:00.480 DEBUG (SyncWorker_0) [hyundai_kia_connect_api.KiaUvoApiEU] hyundai_kia_connect_api - Redirect User Id https://prd.eu-ccapi.kia.com:8080/api/v1/user/integration/redirect/login?user_id=e5fc12ea-a1f1-47dd-916d-920bde0bd8fa&locale=en&state=fdc85c00-0a2f-4c64-bcb4-2cfb1500730a%3A1047b8f6-bfef-4431-a818-abe5c48bcbae&session_state=26a382f8-0e36-45a2-9265-9c201292182d&code=6847f09f-da18-463d-93a6-e029cd2c9ebf.26a382f8-0e36-45a2-9265-9c201292182d.4713f684-f667-4bd3-b1e9-67706072d32d - Response https://prd.eu-ccapi.kia.com:8080/web/v1/user/integration/auth?&locale=en - <!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,shrink-to-fit=no,maximum-scale=1,user-scalable=0"><meta name="theme-color" content="#ffffff"><link href="https://fonts.googleapis.com/css?family=Nanum+Gothic:400,700,800&amp;subset=korean" rel="stylesheet"><link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"><link rel="manifest" href="/web/v1/user/manifest.json"><link rel="icon" href="/web/v1/user/favicon_kia.ico" type="image/x-icon"><!--[if lt IE 10]><script src="/web/v1/user/fetch.js"></script><![endif]--><title></title><link href="/web/v1/user/static/css/main.112e5716.chunk.css" rel="stylesheet"></head><body><noscript>You need to enable JavaScript to run this app.</noscript><div id="root"></div><script>!function(u){function e(e){for(var o,r,t=e[0],a=e[1],n=e[2],c=0,l=[];c<t.length;c++)r=t[c],f[r]&&l.push(f[r][0]),f[r]=0;for(o in a)Object.prototype.hasOwnProperty.call(a,o)&&(u[o]=a[o]);for(p&&p(e);l.length;)l.shift()();return s.push.apply(s,n||[]),i()}function i(){for(var e,o=0;o<s.length;o++){for(var r=s[o],t=!0,a=1;a<r.length;a++){var n=r[a];0!==f[n]&&(t=!1)}t&&(s.splice(o--,1),e=d(d.s=r[0]))}return e}var r={},f={34:0},s=[];function d(e){if(r[e])return r[e].exports;var o=r[e]={i:e,l:!1,exports:{}};return u[e].call(o.exports,o,o.exports,d),o.l=!0,o.exports}d.e=function(n){var e=[],r=f[n];if(0!==r)if(r)e.push(r[2]);else{var o=new Promise(function(e,o){r=f[n]=[e,o]});e.push(r[2]=o);var t,c=document.createElement("script");c.charset="utf-8",c.timeout=120,d.nc&&c.setAttribute("nonce",d.nc),c.src=d.p+"static/js/"+({0:"Locale0",1:"Locale1",2:"Locale10",3:"Locale11",4:"Locale12",5:"Locale13",6:"Locale14",7:"Locale15",8:"Locale16",9:"Locale17",10:"Locale18",11:"Locale19",12:"Locale2",13:"Locale20",14:"Locale21",15:"Locale22",16:"Locale23",17:"Locale24",18:"Locale25",19:"Locale26",20:"Locale27",21:"Locale28",22:"Locale29",23:"Locale3",24:"Locale4",25:"Locale5",26:"Locale6",27:"Locale7",28:"Locale8",29:"Locale9",30:"agreement_cert",31:"agreement_genesis",33:"resident_registration"}[n]||n)+"."+{0:"135572d7",1:"02bbc223",2:"8a486ce4",3:"2c8d260b",4:"f2f50bf5",5:"a74c7c2e",6:"4557d172",7:"d830feb5",8:"f5c32266",9:"41676ac2",10:"6beaa081",11:"c0355a15",12:"0a1766e3",13:"818890c0",14:"fe136a58",15:"27cab8e2",16:"8b905774",17:"775a2b4a",18:"366fe4df",19:"4973cf91",20:"d5572b34",21:"fda85f81",22:"92215e70",23:"2e15a85e",24:"5bc8da1c",25:"10571cc3",26:"1fa139e9",27:"18c4e8ce",28:"bebc38af",29:"7305d798",30:"152afe09",31:"c4aa3f4a",33:"d8f22e04"}[n]+".chunk.js",t=function(e){c.onerror=c.onload=null,clearTimeout(l);var o=f[n];if(0!==o){if(o){var r=e&&("load"===e.type?"missing":e.type),t=e&&e.target&&e.target.src,a=new Error("Loading chunk "+n+" failed.\n("+r+": "+t+")");a.type=r,a.request=t,o[1](a)}f[n]=void 0}};var l=setTimeout(function(){t({type:"timeout",target:c})},12e4);c.onerror=c.onload=t,document.head.appendChild(c)}return Promise.all(e)},d.m=u,d.c=r,d.d=function(e,o,r){d.o(e,o)||Object.defineProperty(e,o,{enumerable:!0,get:r})},d.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})},d.t=function(o,e){if(1&e&&(o=d(o)),8&e)return o;if(4&e&&"object"==typeof o&&o&&o.__esModule)return o;var r=Object.create(null);if(d.r(r),Object.defineProperty(r,"default",{enumerable:!0,value:o}),2&e&&"string"!=typeof o)for(var t in o)d.d(r,t,function(e){return o[e]}.bind(null,t));return r},d.n=function(e){var o=e&&e.__esModule?function(){return e.default}:function(){return e};return d.d(o,"a",o),o},d.o=function(e,o){return Object.prototype.hasOwnProperty.call(e,o)},d.p="/web/v1/user/",d.oe=function(e){throw console.error(e),e};var o=window.webpackJsonp=window.webpackJsonp||[],t=o.push.bind(o);o.push=e,o=o.slice();for(var a=0;a<o.length;a++)e(o[a]);var p=t;i()}([])</script><script src="/web/v1/user/static/js/35.345ba019.chunk.js"></script><script src="/web/v1/user/static/js/main.81d10e10.chunk.js"></script></body></html>
2024-08-12 11:54:00.661 DEBUG (SyncWorker_0) [hyundai_kia_connect_api.KiaUvoApiEU] hyundai_kia_connect_api - silentsignin Response {'redirectUrl': 'https://prd.eu-ccapi.kia.com:8080/api/v1/user/oauth2/redirect?code=W3PCFNCSMD-MG1BB1BJLAG&state=test', 'popup': False, 'method': '', 'upgrade': False, 'integrated': False, 'deleteAccountLink': ''}
2024-08-12 11:54:00.661 DEBUG (SyncWorker_0) [hyundai_kia_connect_api.KiaUvoApiEU] hyundai_kia_connect_api - Get Access Token Data: {'Authorization': 'Basic ZmRjODVjMDAtMGEyZi00YzY0LWJjYjQtMmNmYjE1MDA3MzBhOnNlY3JldA==', 'Stamp': 'oYa3/zyroR0vT6ZgagTzPJcFq9FRkgRPjU5ih3eFC/Og5gc/7ggOgn7OQsDF18g=', 'Content-type': 'application/x-www-form-urlencoded', 'Host': 'prd.eu-ccapi.kia.com:8080', 'Connection': 'close', 'Accept-Encoding': 'gzip, deflate', 'User-Agent': 'okhttp/3.12.0'}grant_type=authorization_code&redirect_uri=https%3A%2F%2Fprd.eu-ccapi.kia.com%3A8080%2Fapi%2Fv1%2Fuser%2Foauth2%2Fredirect&code=W3PCFNCSMD-MG1BB1BJLAG
2024-08-12 11:54:00.800 DEBUG (SyncWorker_0) [hyundai_kia_connect_api.KiaUvoApiEU] hyundai_kia_connect_api - Get Access Token Response: {'access_token': 'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJwaWQiOiI1YmIyYzcyMDlhOTk0MzA0MTk0MzZlYzQiLCJ1aWQiOiI4NWU1OGEwMy1mNjcyLTQwMWMtYjlhMi0zMjMzNWE0YzA3ZWQiLCJzaWQiOiJmZGM4NWMwMC0wYTJmLTRjNjQtYmNiNC0yY2ZiMTUwMDczMGEiLCJleHAiOjE3MjM1NDI4NDAsImlhdCI6MTcyMzQ1NjQ0MCwiaXNzIjoidXZvIn0.Ens_BpTDIJ8-IWSXq2v7EYUOHt-Gcyc4elxjRO2JiXDaswxbsIAEh76pbg1cxocEHv2PMxz6uWxXLqznGB5Ln241PlpYQVqOWz6nbmaj6giOUUECo9Fsh6-hr1ed6GIcZPgVP-zzsByc2mn1a17uhkoVxIwMcXkuMQvk8OZBRmJM5Kqk-82_9hzvPIRS-OObG3tBFwt3Ox6YvNauSykA4rhD2TGqFL8xVk4HPze65TaHOozI0wOByN1MhRhE9j32b68rFWdguc4rWJIkREfGA-6O-loW_T98xfdozufDVUNmMb26VdWrdg1uivEjO2tZ4zuDVuGQYRWsyvrWJTZvcQ', 'token_type': 'Bearer', 'refresh_token': 'SWQLFV9CVYO_VPU99D-ZBW', 'expires_in': 86400}
2024-08-12 11:54:00.800 DEBUG (SyncWorker_0) [hyundai_kia_connect_api.KiaUvoApiEU] hyundai_kia_connect_api - Access Token Value Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJwaWQiOiI1YmIyYzcyMDlhOTk0MzA0MTk0MzZlYzQiLCJ1aWQiOiI4NWU1OGEwMy1mNjcyLTQwMWMtYjlhMi0zMjMzNWE0YzA3ZWQiLCJzaWQiOiJmZGM4NWMwMC0wYTJmLTRjNjQtYmNiNC0yY2ZiMTUwMDczMGEiLCJleHAiOjE3MjM1NDI4NDAsImlhdCI6MTcyMzQ1NjQ0MCwiaXNzIjoidXZvIn0.Ens_BpTDIJ8-IWSXq2v7EYUOHt-Gcyc4elxjRO2JiXDaswxbsIAEh76pbg1cxocEHv2PMxz6uWxXLqznGB5Ln241PlpYQVqOWz6nbmaj6giOUUECo9Fsh6-hr1ed6GIcZPgVP-zzsByc2mn1a17uhkoVxIwMcXkuMQvk8OZBRmJM5Kqk-82_9hzvPIRS-OObG3tBFwt3Ox6YvNauSykA4rhD2TGqFL8xVk4HPze65TaHOozI0wOByN1MhRhE9j32b68rFWdguc4rWJIkREfGA-6O-loW_T98xfdozufDVUNmMb26VdWrdg1uivEjO2tZ4zuDVuGQYRWsyvrWJTZvcQ
2024-08-12 11:54:00.800 DEBUG (SyncWorker_0) [hyundai_kia_connect_api.KiaUvoApiEU] hyundai_kia_connect_api - Get Refresh Token Data: grant_type=refresh_token&redirect_uri=https%3A%2F%2Fwww.getpostman.com%2Foauth2%2Fcallback&refresh_token=SWQLFV9CVYO_VPU99D-ZBW
2024-08-12 11:54:00.917 DEBUG (SyncWorker_0) [hyundai_kia_connect_api.KiaUvoApiEU] hyundai_kia_connect_api - Get Refresh Token Response: {'access_token': 'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJwaWQiOiI1YmIyYzcyMDlhOTk0MzA0MTk0MzZlYzQiLCJ1aWQiOiI4NWU1OGEwMy1mNjcyLTQwMWMtYjlhMi0zMjMzNWE0YzA3ZWQiLCJzaWQiOiJmZGM4NWMwMC0wYTJmLTRjNjQtYmNiNC0yY2ZiMTUwMDczMGEiLCJleHAiOjE3MjM1NDI4NDAsImlhdCI6MTcyMzQ1NjQ0MCwiaXNzIjoidXZvIn0.Ens_BpTDIJ8-IWSXq2v7EYUOHt-Gcyc4elxjRO2JiXDaswxbsIAEh76pbg1cxocEHv2PMxz6uWxXLqznGB5Ln241PlpYQVqOWz6nbmaj6giOUUECo9Fsh6-hr1ed6GIcZPgVP-zzsByc2mn1a17uhkoVxIwMcXkuMQvk8OZBRmJM5Kqk-82_9hzvPIRS-OObG3tBFwt3Ox6YvNauSykA4rhD2TGqFL8xVk4HPze65TaHOozI0wOByN1MhRhE9j32b68rFWdguc4rWJIkREfGA-6O-loW_T98xfdozufDVUNmMb26VdWrdg1uivEjO2tZ4zuDVuGQYRWsyvrWJTZvcQ', 'token_type': 'Bearer', 'expires_in': 86400}
2024-08-12 11:54:01.046 DEBUG (SyncWorker_0) [hyundai_kia_connect_api.KiaUvoApiEU] hyundai_kia_connect_api - Get Vehicles Response: {'retCode': 'S', 'resCode': '0000', 'resMsg': {'vehicles': [{'vin': 'KNARH81GBP5130681', 'vehicleId': '4f40d36f-2c8c-4d8f-9008-002c13ab0594', 'vehicleName': 'SORENTO', 'type': 'HV', 'tmuNum': '-', 'nickname': 'SORENTO', 'year': '2023', 'master': True, 'carShare': 0, 'regDate': '2022-11-23 11:36:44.768', 'detailInfo': {'inColor': 'WK', 'outColor': 'SWP', 'saleCarmdlCd': 'HC', 'bodyType': '3', 'saleCarmdlEnNm': 'SORENTO'}, 'protocolType': 0, 'ccuCCS2ProtocolSupport': 0}]}, 'msgId': 'e19e6e2d-c852-45d6-a4ed-2ad5d45fca48'}
2024-08-12 11:54:01.214 DEBUG (SyncWorker_3) [hyundai_kia_connect_api.KiaUvoApiEU] hyundai_kia_connect_api - get_cached_vehicle_status response: {'retCode': 'F', 'resCode': '5921', 'resMsg': 'No Data Found v2 - No Data Found v2', 'msgId': '577a1b86-8817-4793-b8aa-272b51437fcd'}
2024-08-12 11:54:01.386 DEBUG (SyncWorker_13) [hyundai_kia_connect_api.KiaUvoApiEU] hyundai_kia_connect_api - get_cached_vehicle_status response: {'retCode': 'F', 'resCode': '5921', 'resMsg': 'No Data Found v2 - No Data Found v2', 'msgId': '776ef790-ed42-416c-88f3-d5aa8b5b3a76'}
2024-08-12 11:54:01.388 DEBUG (MainThread) [custom_components.kia_uvo.coordinator] Finished fetching kia_uvo data in 2.373 seconds (success: False)
```
Any ideas what could be wrong?

**Comment by okurz** [comment]
I was also affected by the API access limit around the time when you reported the issue which automatically recovered on the next day but happened 3 times since then. The API is accessed from my mobile app, home assistant and an installation of https://github.com/evcc-io/evcc/ . I have since extended the polling intervals in home assistant and evcc which might prevent this issue.

Your logs look to me like the authentication now fails maybe repeatedly. Have you tried https://github.com/Hyundai-Kia-Connect/kia_uvo/blob/master/README.md#troubleshooting again after waiting a night?

**Comment by adorobis** [comment]
Yes, I have followed the troubleshooting guide except last step, to create a new account. No success so far. I might try a bit later.

**Comment by adorobis** [comment]
I have forgotten about the integration for a few weeks and after the integration got an update I've re-enabled it and it works all ok again. Without the re-authentication needed. So not sure what the problem really was...
