### ISSUE TITLE
Car battrey level not working

### ISSUE THREAD

**Issue by maco2035** [Hyundai-Kia-Connect/kia_uvo#924]
**Region and Brand of car**
USA 2023 Ioniq 6 SEL

**Version of the integration**
2.26.6

**Describe the bug**
I am unable to see any updates around the 12v battery system in home assistant at all. See attached screenshots.

**Debug logs if an error occurred**
Not able to find anything in the logs about this.
```
2024-08-29 17:43:29.037 DEBUG (SyncWorker_35) [hyundai_kia_connect_api.HyundaiBlueLinkAPIUSA] hyundai_kia_connect_api - Get Vehicles Response 
```
``` json
{
    "enrolledVehicleDetails":[
        {
            "packageDetails":[
                {
                    "assetNumber":"REDACTED",
                    "subscriptionType":"Trial",
                    "displayCategory":"Basic||YES",
                    "packageId":"REDACTED",
                    "term":"REDACTED",
                    "renewalDate":"REDACTED",
                    "packageType":"Basic",
                    "startDate":"REDACTED"
                },
                {
                   "assetNumber":"REDACTED",
                   "subscriptionType":"Trial",
                   "displayCategory":"Advanced||YES",
                   "packageId":"REDACTED",
                   "term":"REDACTED",
                   "renewalDate":"REDACTED"
                   ,"packageType":"Advanced",
                   "startDate":"REDACTED"
                },
                {
                    "assetNumber":"REDACTED",
                    "subscriptionType":"Trial",
                    "displayCategory":"Map & Multimedia Over-the-Air Updates||NO",
                    "packageId":"REDACTED",
                    "term":"REDACTED",
                    "renewalDate":"REDACTED",
                    "packageType":"Map & Multimedia Over-the-Air Updates",
                    "startDate":"REDACTED"
               }
           ],
     "vehicleDetails":
         {
           "svrStatus":"NONE",
           "fatcAvailable":"Y",
           "color":"GREEN",
           "remoteStartWakeupDays":"seven",
           "enrollmentDate":"REDACTED",
           "maintSyncCapable":"YES",
           "brandIndicator":"H",
           "deviceStatus":"ENROLLED",
           "setOffPeak":"1",
           "mapProvider":"REDACTED",
           "interiorColor":"NNB",
           "accessoryCode":"REDACTED",
           "trim":"SEL",
           "modelCode":"IONIQ 6",
           "nadid":"REDACTED",
           "ubiCapabilityInd":"N",
           "mit":"REDACTED",
           "regid":"REDACTED",
           "vin":"REDACTED",
           "blueLink":"Y",
           "waypointInd":"NO",
           "billingInd":"MONTHLY",
           "enrollmentId":"REDACTED",
           "sideMirrorHeatCapable":"YES",
           "ownersuccession":"REDACTED",
           "odometer":"REDACTED",
           "imat":"REDACTED",
           "nickName":"REDACTED",
           "additionalVehicleDetails": 
               {
                   "temperatureRange":"true",
                   "tmuSleepMode":"No",
                   "enableHCAModule":"Y",
                   "maxTemp":82,
                   "icpParking":1,
                   "remoteLockConsentForRemoteStart":"No",
                   "calendarVehicleSyncEnable":"REDACTED",
                   "windowSafetyOption2":"3",
                   "vehicleModemType":"REDACTED",
                   "icpAACapable":"Y",
                   "productName":"Bluelink+",
                   "icpDriveThru":0,
                   "dkType":"2.0-Standard",
                   "dynamicSOCText":"Use the slider above to set a charge limit. Charging will stop when this battery level is reached. The limit cannot be set lower than 50% This setting will override all other charge settings if set.",
                   "battDrainFunctOnOff":"N",
                   "enableRoadSideAssitanceAAAModule":"Y",
                   "idleSpeedValetAlert":"N"
                   "evAlarmOptionInfo":"Yes",
                   "mapOtaAccepted":"N",
                   "v2LRemainTimeOption":"N",
                   "dkCapable":"Y",
                   "combinedHeatSettingsEnable":"Y",
                   "chargePortDoorOption":"N",
                   "icpChargingStation":0,
                   "hyundaiHome":"N",
                   "wifiHotspotCapable":"Y",
                   "tmuSleepInMin":3.6333333333333333,
                   "v2LOption":"N",
                   "dkEnrolled":"N",
                   "icpAvntCapable":"Y",
                   "enableEVTrip":"Y",
                   "minTemp":62,
                   "v2GOption":"N",
                   "icpFuelStation":0,
                   "targetSOCLevelMax":100,
                   "batteryPreconditioningOpton":"1",
                   "remoteLockConsentForRemoteStartCapable":"No",
                   "eaPromotion": 
                       {
                           "expireOn":"REDACTED",                 
                           "enrollmentCode":"REDACTED"},
                           "msCapableOption":"N",
                           "icpCPCapable":"Y",
                           "enableValetActivate":"Y",
                           "frunkOption":"N",
                           "energyConsoleCapable":"REDACTED",
                           "cpoVehicle":"REDACTED"
                       },
                     "evStatus":"E",
                     "modelYear":"2023",
                     "transmissiontype":"AUTO",                   
                     "steeringWheelHeatCapable":"YES",
                     "bluelinkEnrolled":true,
                     "targetSOCLevel":"50",
                     "vehicleGeneration":"2",
                     "rearWindowHeatCapable":"YES",
                     "preferredDealerCode":"REDACTED",
                     "hmaModel":"REDACTED",
                     "series":"IONIQ 6",
                     "enrollmentStatus":"ACTIVE",
                     "starttype":"KEY",
                     "enrollmentType":"INDIVIDUAL",
                     "userprofilestatus":"Y",
                     "sapColorCode":"RG9",
                     "bluelinkEnabled":true,
                     "odometerUpdateDate":"REDACTED"
               },
               "roleDetails":
                   [
                       {
                          "roleCode":"SD",
                          "roleName":"Secondary Driver"
                       }
                  ],
                  "responseHeaderMap":{}}
                  ],
                  "addressDetails":
                      [
                          {
                              "city":"REDACTED",
                              "street":"REDACTED",
                              "postalCode":"REDACTED",
                              "type":"REDACTED",
                              "region":"REDACTED"
                          }
                      ],
                  "user":
                      {
                          "accountId":"REDACTED",
                          "firstName":"REDACTED",
                          "lastName":"REDACTED",
                          "phonesOptIn":
                             [
                                 {
                                    "number":"REDACTED",
                                    "primaryPhoneIndicator":"YES",
                                   "fccOptIn":"YES",
                                   "type":"MOBILE"
                                }
                            ],
                         "loginId":"REDACTED",
                         "additionalUserDetails":
                             {
                                 "userProfileUpdate":"N",
                                 "timezoneOffset":-4,
                                 "billingAccountNumber":"REDACTED",
                                 "appRating":"REDACTED",
                                 "geoLocationConsent":"REDACTED","
                                 emailVerifyStatus":"N",
                                 "timezoneAbbr":"EDT",
                                 "otaAcceptance":"N",
                                 "telematicsPhoneNumber":"REDACTED"
                              },
                              "tncFlag":"N",
                              "phones"
```

**To Reproduce**
N/A

**Expected behavior**
The entity should be reporting the data to Home assistant.

**Screenshots**

![Screenshot from 2024-08-29 14-45-54](https://github.com/user-attachments/assets/2c3d133b-22c8-43d3-a4c0-f6d669f085d7)
![image](https://github.com/user-attachments/assets/e9bdae40-03fd-43b1-b04d-aab1fdc326b3)

**Additional context**

**Comment by cdnninja** [comment]
Is the battery dead? If so it stops reporting.    

What is your force scan interval set to?  It looks like your car isn't sleeping.

**Comment by maco2035** [comment]
Car did die, so I had to jump it that I understand, but I don't think it should be no reporting it after it is jumped.
Force Scan is at 90 mins
![image](https://github.com/user-attachments/assets/347c7041-0240-4e15-8fdc-3e525294a709)

**Comment by cdnninja** [comment]
For some reason Kia stops reporting the data when this occurs.   Sometimes restarting the integration solves this.  I can't remember what current default force scan is but it's much higher than that. 

I would increase your force scan to 600 minutes or so.  Each force scan takes battery power.  These cars are flawed in that they won't keep charging the 12v even when low unless you drive the car.

**Comment by maco2035** [comment]
Yeah I let the car sit for a week, and the car was dead, but the HV battery has power. Which boggled my mind. I think I need to get the 12V battery to be replace, But I wanted to monitor it a bit more aggressively.

**Comment by maco2035** [comment]
However even after restarting HA, and reloading the integration, it still hasn't sent any data

**Comment by cdnninja** [comment]
Until Kia decides to send the data again not much we can do.  They will eventually though.

**Comment by maco2035** [comment]
Hey I don't know if this will help, but in my logs I saw this:
```python
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/kia_uvo/coordinator.py", line 145, in _async_update_data
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 85, in update_all_vehicles_with_cached_state
    self.update_vehicle_with_cached_state(vehicle_id)
  File "/usr/local/lib/python3.12/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 90, in update_vehicle_with_cached_state
    self.api.update_vehicle_with_cached_state(self.token, vehicle)
  File "/usr/local/lib/python3.12/site-packages/hyundai_kia_connect_api/HyundaiBlueLinkAPIUSA.py", line 473, in update_vehicle_with_cached_state
    state["vehicleDetails"] = self._get_vehicle_details(token, vehicle)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/hyundai_kia_connect_api/HyundaiBlueLinkAPIUSA.py", line 149, in _get_vehicle_details
    for entry in response["enrolledVehicleDetails"]:
                 ~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'enrolledVehicleDetails'
```

```python
 hyundai_kia_connect_api - Unable to get vehicle location: {'errorSubCode': 'C400_1', 'systemName': 'IDM', 'functionName': 'validatePIN', 'errorSubMessage': 'Missing Fields: blueLinkServicePin or pinToken', 'errorMessage': 'Please check to see that all required fields are populated and try again.', 'errorCode': 400, 'serviceName': 'CheckCustomerUserPin'} 
 ```

**Comment by cdnninja** [comment]
Unrelated error.   Did you provide your pin to the integration?
