### ISSUE TITLE
2.27.0 Unable to start after reboot 

### ISSUE THREAD

**Issue by peter4200** [Hyundai-Kia-Connect/kia_uvo#945]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/kia_uvo/blob/master/README.md
**Region and Brand of car**
Ionic 5 AWD 2021

**Version of the integration**
2.27.0

**Describe the bug**
After update of the integration to version 2.27 there are som missing modules

**Debug logs if an error occurred**
Logger: homeassistant.setup
Kilde: setup.py:334
Første forekomst: 19.39.35 (1 forekomster)
Senest logget: 19.39.35

Setup failed for custom integration 'kia_uvo': Unable to import component: No module named 'hyundai_kia_connect_api'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 334, in _async_setup_component
    component = await integration.async_get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1027, in async_get_component
    self._component_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1007, in async_get_component
    comp = await self.hass.async_add_import_executor_job(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1067, in _get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/kia_uvo/__init__.py", line 14, in <module>
    from hyundai_kia_connect_api.exceptions import *
ModuleNotFoundError: No module named 'hyundai_kia_connect_api'

Outlined here: https://github.com/fuatakgun/kia_uvo/blob/master/README.md

**To Reproduce**
Restart the integration / Home Assistant

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by peter4200** [comment]
Reinstall of version 2.26.8 seems to work

**Comment by cdnninja** [comment]
Can you replicate the issue?

**Comment by peter4200** [comment]
no, I can not :-) Now I'm on 2.27.0 and everything seems to work again

**Comment by Ulrar** [comment]
Same here with the newer HA : 

```
Unable to install package hyundai_kia_connect_api==3.23.6: error: No virtual environment found; run `uv venv` to create an environment, or pass `--system` to install into a non-virtual environment
```

```
 Setup failed for custom integration 'kia_uvo': Requirements for kia_uvo not found: ['hyundai_kia_connect_api==3.23.6']. 
```

One note is I'm using the linuxserver image (to run as non root), so it's possible this issue comes from a linuxserver specificity, but I have a lot of other integrations working fine, this one is the only one affected it seems.

**Comment by peter4200** [comment]
Downgrade the package 2.26.8 and then, update to 2.27.0 did the trick for me

**Comment by cdnninja** [comment]
This implies it isn't correctly installing the package.  More of a host issue than anything.  Could also manually install it with pip.

**Comment by cdnninja** [comment]
This doesn't seem like an integration issue though.

**Comment by Ulrar** [comment]
This is solved in the latest linuxserver image, see https://github.com/linuxserver/docker-homeassistant/issues/107
