### ISSUE TITLE
Unknown error during setup

### ISSUE THREAD

**Issue by Frankenberrypi** [Hyundai-Kia-Connect/kia_uvo#958]
**Region and Brand of car**
US, Hyundai 

**Version of the integration**
2.28.1

**Describe the bug**
On setup the GUI reports "Unknown error occurred"

**Debug logs if an error occurred**
```
Logger: homeassistant.config_entries
Source: config_entries.py:594
First occurred: 11:44:08 AM (1 occurrences)
Last logged: 11:44:08 AM

Error setting up entry Hyundai USA email@gmail.com for kia_uvo
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 594, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/kia_uvo/__init__.py", line 52, in async_setup_entry
    await coordinator.async_config_entry_first_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 281, in async_config_entry_first_refresh
    await self._async_refresh(
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/kia_uvo/coordinator.py", line 126, in _async_update_data
    await self.hass.async_add_executor_job(
asyncio.exceptions.CancelledError
```

**To Reproduce**
Setup a new instance selecting the US region and Hyundai brand.

**Expected behavior**
Add new device.

**Screenshots**
![image](https://github.com/user-attachments/assets/f32db001-0401-475a-959f-33f42d3cbef0)

**Additional context**
My best guess is that this has something to do with authorization.  When I log with the app or website it asks to send a verification code via text or email, maybe that's missing now.

**Comment by cdnninja** [comment]
This doesn't support mfa. Maybe try disable that and see if it works?

**Comment by Frankenberrypi** [comment]
I was unable to find a setting in my account, so contacted support.  Their response was "Due to the security of your account, we cannot disable or turn off two-factor authentication."  I can't think of any other workarounds.

**Comment by drbroccoli** [comment]
> I was unable to find a setting in my account, so contacted support. Their response was "Due to the security of your account, we cannot disable or turn off two-factor authentication." I can't think of any other workarounds.

I've discovered this integration and have the exact same issue. As far as I know Hyundai requires 2FA on ALL accounts now, there is no way to disable. Does this mean this integration dies?

**Comment by cdnninja** [comment]
It means someone in the USA needs to sniff the traffic.  See how the mfa prompt impacts the calls and create the code.   

I assume it doesn't mfa all the time for the mobile app just first login? 

If it does all the time then yes would kill this since every few days would need a redo.

**Comment by drbroccoli** [comment]
> It means someone in the USA needs to sniff the traffic. See how the mfa prompt impacts the calls and create the code.
> 
> I assume it doesn't mfa all the time for the mobile app just first login?
> 
> If it does all the time then yes would kill this since every few days would need a redo.

Ah, you are correct, it does not ask for MFA every time you open it, just the initial login. I am in the USA with a Hyundai, not really sure what I am doing but I am happy to help if I can!

**Comment by Frankenberrypi** [comment]
No, it suddenly logged in OK with no additional problems.  I have no
explanation for why.
