### ISSUE TITLE
Set AC charging current 

### ISSUE THREAD

**Issue by eekhoorn** [Hyundai-Kia-Connect/kia_uvo#984]
Niro EV - EU

Version 2.3.1

When setting the AC  charging current to 60%

Log:
Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:245
integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 18:10:27 (2 occurrences)
Last logged: 18:10:34

[140481066258000] Unexpected exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 245, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2802, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2845, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/kia_uvo/services.py", line 162, in async_handle_set_charging_current
    await coordinator.set_charging_current(vehicle_id, int(current_level))
  File "/config/custom_components/kia_uvo/coordinator.py", line 270, in set_charging_current
    action_id = await self.hass.async_add_executor_job(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 178, in set_charging_current
    return self.api.set_charging_current(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 1327, in set_charging_current
    _check_response_for_errors(response)
  File "/usr/local/lib/python3.12/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 129, in _check_response_for_errors
    raise error_code_mapping[response["resCode"]](response["resMsg"])
hyundai_kia_connect_api.exceptions.DeviceIDError: Invalid request body - Invalid deviceId.

**Comment by eekhoorn** [comment]
Additional HA message: Failed to perform the action kia_uvo/set_charging_current. Invalid request body - Invalid deviceId.

**Comment by eekhoorn** [comment]
Yes, still having issues with this.

**Comment by cdnninja** [comment]
Please try latest.

**Comment by eekhoorn** [comment]
Still not working with latest

**Comment by mastameista** [comment]
I also have an issue with my EV9 setting AC charging current, e.g. from 60 to 100%. The charging current is changed on the car side but after executing the action, the whole integration crashes and all entities are "unavailable". 

This error originated from a custom integration.

Logger: homeassistant
Source: custom_components/kia_uvo/coordinator.py:175
integration: Hyundai / Kia Connect (documentation, issues)
First occurred: 8:55:12 PM (1 occurrences)
Last logged: 8:55:12 PM

Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/config/custom_components/kia_uvo/coordinator.py", line 175, in async_await_action_and_refresh
    await self.hass.async_add_executor_job(
    ...<5 lines>...
    )
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.13/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 223, in check_action_status
    return self.api.check_action_status(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self.token, self.get_vehicle(vehicle_id), action_id, synchronous, timeout
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 1747, in check_action_status
    state = self.check_action_status(
        token, vehicle, action_id, synchronous=False
    )
  File "/usr/local/lib/python3.13/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 1769, in check_action_status
    _check_response_for_errors(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 129, in _check_response_for_errors
    raise error_code_mapping[response["resCode"]](response["resMsg"])
hyundai_kia_connect_api.exceptions.DeviceIDError: Invalid request body - Invalid deviceId.

**Comment by cdnninja** [comment]
Please try latest release and let me know if fixed.  Was this actually erroring on the second run of the action not the first?

**Comment by mastameista** [comment]
I'll do. No, it was on the first run.

**Comment by mastameista** [comment]
@cdnninja great work! I can now set ac charging current successfully. This is great, thx a lot!

**Comment by cdnninja** [comment]
Excellent great to hear!

**Comment by cdnninja** [comment]
Next release will solve that.
