### ISSUE TITLE
Integration crashes each night after charging

### ISSUE THREAD

**Issue by stintov** [Hyundai-Kia-Connect/kia_uvo#990]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/kia_uvo/blob/master/README.md
**Region and Brand of car**
Kia EV9
**Version of the integration**
2.31.0 , although this has happened for a long time so not just this version.

**Describe the bug**
Each morning after an overnight charge all the sensors say unavailable. Simply reloading the integration bring it back to life.

**Debug logs if an error occurred**
Not sure where to find the debug logs?
Outlined here: https://github.com/fuatakgun/kia_uvo/blob/master/README.md

**To Reproduce**
Charge overnight
**Expected behavior**
Not to crash
**Screenshots**

**Additional context**

**Comment by fuatakgun** [comment]
Enable debug log, before the night, let it crash and share the logs with us. until then, there is nothing we can do

**Comment by stintov** [comment]
Logger: homeassistant
Source: custom_components/kia_uvo/coordinator.py:175
integration: Kia Uvo / Hyundai Bluelink ([documentation](https://github.com/Hyundai-Kia-Connect/kia_uvo), [issues](https://github.com/Hyundai-Kia-Connect/kia_uvo/issues))
First occurred: 14 December 2024 at 23:28:07 (1 occurrences)
Last logged: 14 December 2024 at 23:28:07

Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/config/custom_components/kia_uvo/coordinator.py", line 175, in async_await_action_and_refresh
    await self.hass.async_add_executor_job(
    ...<5 lines>...
    )
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.13/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 215, in check_action_status
    return self.api.check_action_status(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self.token, self.get_vehicle(vehicle_id), action_id, synchronous, timeout
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/local/lib/python3.13/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 1727, in check_action_status
    state = self.check_action_status(
        token, vehicle, action_id, synchronous=False
    )
  File "/usr/local/lib/python3.13/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 1749, in check_action_status
    _check_response_for_errors(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 129, in _check_response_for_errors
    raise error_code_mapping[response["resCode"]](response["resMsg"])
hyundai_kia_connect_api.exceptions.DeviceIDError: Invalid request body - Invalid deviceId.

**Comment by stintov** [comment]
Also

Logger: custom_components.kia_uvo.coordinator
Source: helpers/update_coordinator.py:379
integration: Kia Uvo / Hyundai Bluelink ([documentation](https://github.com/Hyundai-Kia-Connect/kia_uvo), [issues](https://github.com/Hyundai-Kia-Connect/kia_uvo/issues))
First occurred: 14 December 2024 at 23:28:06 (16 occurrences)
Last logged: 06:58:07

Unexpected error fetching kia_uvo data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 379, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/kia_uvo/coordinator.py", line 145, in _async_update_data
    await self.hass.async_add_executor_job(
        self.vehicle_manager.update_all_vehicles_with_cached_state
    )
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.13/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 86, in update_all_vehicles_with_cached_state
    self.update_vehicle_with_cached_state(vehicle_id)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 91, in update_vehicle_with_cached_state
    self.api.update_vehicle_with_cached_state(self.token, vehicle)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 342, in update_vehicle_with_cached_state
    _check_response_for_errors(response)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 129, in _check_response_for_errors
    raise error_code_mapping[response["resCode"]](response["resMsg"])
hyundai_kia_connect_api.exceptions.DeviceIDError: Invalid request body - Invalid deviceId.

It's fine after reloading the integration

**Comment by stintov** [comment]
Have I provided the correct logs please?

**Comment by stintov** [comment]
I added this code into configuration.yaml and restarted HA as per the read me. 

logger:
  default: warning
  logs:
    custom_components.kia_uvo: debug
    hyundai_kia_connect_api: debug

After the crash I posted the logs a I saw.

![image](https://github.com/user-attachments/assets/138183b0-a71e-4d52-8b5a-2f9aa3fefe78)

I have enabled logging via the GUI this time, lets see what happens.

**Comment by Hans-Solo-Dolo** [comment]
Did this issue get resolved? Can you mark as resolved if so?

**Comment by stintov** [comment]
Hi, no it did not. I’m new to Home Assistant and don’t know how to gather the logs requested. I’ve turned on debug mode but now what? Are there specific integration logs you need? If so where do I find these please?  All anybody does is tell me to read the read me but if you do read the read me you’ll see it’s not very helpful in the bottom section that he’s talking about enabling debug mode.

Warm Regards

Austin Tovey
07917 418530
________________________________

**Comment by stintov** [comment]
Yes, but no one will help me understand how to collect the relevant logs that have been requested the release notes. Don’t tell you exactly what to do.

Warm Regards

Austin Tovey
07917 418530
________________________________

**Comment by cdnninja** [comment]
Enable debug logs. Wait for it to happen, then capture logs: https://www.bing.com/search?pglt=297&q=get+logs+home+assistant

**Comment by cdnninja** [comment]
Please see if this is still occurring.   A few bug fixes lately.
