### ISSUE TITLE
Integration fails to load

### ISSUE THREAD

**Issue by croldan72** [Hyundai-Kia-Connect/kia_uvo#994]
Unsure if this is similar or related to Bug 989. 

**Region and Brand of car**: USA, CT. Hyundai Ioniq 5

**Version of the integration**: 2.31.0

**Describe the bug**
Integration doesn't load. "Needs Attention" Error when going to devices and services, followed by the following truncated message:
Failed setup, will retry: Config Not Ready: Error communicating with API: Traceback (most recent call last): File "/config/custom_components/kia_uvo/coordinator.py", line 126, in _async_update_data await self.hass.async_add_executor_job( ...<2 lines>... ) File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run result = self.fn(*self.args, **self.kwargs) File "/usr/local/lib/python3.13/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 116, in...

---------------------------

**Debug logs if an error occurred**: See below. Let me know if you need anything else. 

This error originated from a custom integration.

Logger: custom_components.kia_uvo.coordinator
Source: custom_components/kia_uvo/coordinator.py:135
integration: Hyundai / Kia Connect (documentation, issues)
First occurred: 12:25:10 PM (1 occurrences)
Last logged: 12:25:10 PM

Cached update failed: Traceback (most recent call last): File "/config/custom_components/kia_uvo/coordinator.py", line 126, in _async_update_data await self.hass.async_add_executor_job( ...<2 lines>... ) File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run result = self.fn(*self.args, **self.kwargs) File "/usr/local/lib/python3.13/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 116, in check_and_force_update_vehicles self.update_vehicle_with_cached_state(vehicle_id) ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^ File "/usr/local/lib/python3.13/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 91, in update_vehicle_with_cached_state self.api.update_vehicle_with_cached_state(self.token, vehicle) ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.13/site-packages/hyundai_kia_connect_api/HyundaiBlueLinkApiUSA.py", line 684, in update_vehicle_with_cached_state state["vehicleStatus"] = self._get_vehicle_status(token, vehicle, False) ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.13/site-packages/hyundai_kia_connect_api/HyundaiBlueLinkApiUSA.py", line 178, in _get_vehicle_status status = dict(response["vehicleStatus"]) ~~~~~~~~^^^^^^^^^^^^^^^^^ KeyError: 'vehicleStatus' During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/config/custom_components/kia_uvo/coordinator.py", line 135, in _async_update_data await self.hass.async_add_executor_job( self.vehicle_manager.update_all_vehicles_with_cached_state ) File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run result = self.fn(*self.args, **self.kwargs) File "/usr/local/lib/python3.13/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 86, in update_all_vehicles_with_cached_state self.update_vehicle_with_cached_state(vehicle_id) ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^ File "/usr/local/lib/python3.13/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 91, in update_vehicle_with_cached_state self.api.update_vehicle_with_cached_state(self.token, vehicle) ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.13/site-packages/hyundai_kia_connect_api/HyundaiBlueLinkApiUSA.py", line 684, in update_vehicle_with_cached_state state["vehicleStatus"] = self._get_vehicle_status(token, vehicle, False) ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^ File "/usr/local/lib/python3.13/site-packages/hyundai_kia_connect_api/HyundaiBlueLinkApiUSA.py", line 178, in _get_vehicle_status status = dict(response["vehicleStatus"]) ~~~~~~~~^^^^^^^^^^^^^^^^^ KeyError: 'vehicleStatus'
Traceback (most recent call last):
  File "/config/custom_components/kia_uvo/coordinator.py", line 126, in _async_update_data
    await self.hass.async_add_executor_job(
    ...<2 lines>...
    )
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.13/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 116, in check_and_force_update_vehicles
    self.update_vehicle_with_cached_state(vehicle_id)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 91, in update_vehicle_with_cached_state
    self.api.update_vehicle_with_cached_state(self.token, vehicle)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/hyundai_kia_connect_api/HyundaiBlueLinkApiUSA.py", line 684, in update_vehicle_with_cached_state
    state["vehicleStatus"] = self._get_vehicle_status(token, vehicle, False)
                             ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/hyundai_kia_connect_api/HyundaiBlueLinkApiUSA.py", line 178, in _get_vehicle_status
    status = dict(response["vehicleStatus"])
                  ~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'vehicleStatus'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/config/custom_components/kia_uvo/coordinator.py", line 135, in _async_update_data
    await self.hass.async_add_executor_job(
        self.vehicle_manager.update_all_vehicles_with_cached_state
    )
  File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.13/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 86, in update_all_vehicles_with_cached_state
    self.update_vehicle_with_cached_state(vehicle_id)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 91, in update_vehicle_with_cached_state
    self.api.update_vehicle_with_cached_state(self.token, vehicle)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/hyundai_kia_connect_api/HyundaiBlueLinkApiUSA.py", line 684, in update_vehicle_with_cached_state
    state["vehicleStatus"] = self._get_vehicle_status(token, vehicle, False)
                             ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/hyundai_kia_connect_api/HyundaiBlueLinkApiUSA.py", line 178, in _get_vehicle_status
    status = dict(response["vehicleStatus"])
                  ~~~~~~~~^^^^^^^^^^^^^^^^^
KeyError: 'vehicleStatus'

**Comment by cdnninja** [comment]
Do all cars in the native app load?

**Comment by croldan72** [comment]
Yes/ no... 

We just purchased a second car and the Bluelink Subscription is still being activated (free for 3 months). I just activated it this morning, so the car and details load, but I can't do anything just yet (lock/ unlock, etc).

**Comment by cdnninja** [comment]
That is the cause.

**Comment by migmax1995** [comment]
I've got the same error here everything was working for a few minutes and then I got the same problem clicking reload no longer fetches data and connection

**Comment by croldan72** [comment]
> That is the cause.

Thank you. For my issue, I waited until the new car was active in Bluelink and was functional. As you indicated, that must have been the cause as it is working now.
